### ISSUE TITLE
Minimize bundle size

### ISSUE THREAD

**Issue by arlair** [angular/universal-starter#10]
Hi, I tried this out and noticed the bundle.js created was 1.7 meg.

I had a quick look and found that Webpack has a -p option that will uglify the output. People who know Webpack, may have better ideas.

I realise Angular 2 is in development, but you could add this as a default or an option to make the bundle size a little less scary ;)

Cheers.

**Comment by gdi2290** [comment]
The angular team isn't finished working on the production version of Angular 2 which would address the biggest issue, filesize. Adding production to website would also slow down the build process when developing your app

**Comment by valorkin** [comment]
waat? http://valor-software.github.io/ng2-bootstrap/index-bs4.html
angular2 with dependencies 642 KB (156KB gzipped)
what is comparable to ng1

**Comment by gdi2290** [comment]
I'm going to close this for now. I'm planning on updating the build system for this starter but I won't make a production version until the beta
