### ISSUE TITLE
how to use universal with system.js

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal-starter#100]
existing branch(systemjs) is not working even after updating to latest angular2 and universal

**Comment by MarkPieszak** [comment]
Are you getting this error?

```
module.js:341
    throw err;
    ^

Error: Cannot find module '/universal-starter/dist/src/server.js'

```

**Comment by kuldeepkeshwar** [comment]
yes

**Comment by MarkPieszak** [comment]
I'm working on this one now, I have it past that error but need to figure out a few other things. That branch hasn't been updated in quite a while. Sorry for the delay!

**Comment by vinodbhargava** [comment]
@kuldeepkeshwar were you able to get any solution for this?

**Comment by kuldeepkeshwar** [comment]
no , i moved to webpack

**Comment by MarkPieszak** [comment]
Oh sorry I never checked in the System branch fixes! I was almost finished too. Give me a day or two I'll let you know when it's done @vinodbhargava

**Comment by sunild** [comment]
Any word on this? I'd love to see a working example with SystemJS so I can get server rendering working on an existing project. My earlier attempts at this failed miserably, b/c it was impossible to resolve all of the issues w/unknown providers.

I'm hoping a slimmed down example will shed some light on why I couldn't get it working :)

**Comment by jeffwhelpley** [comment]
I am going to close this as we are tracking System.js support here:

https://github.com/angular/universal/issues/283

Just note, however, that with the recent push in the community toward Webpack, this issue is lower priority for now. Feel free to add your 2 cents to the issue on the Universal repo, though.
