### ISSUE TITLE
Does not bootstrap after project structure changes

### ISSUE THREAD

**Issue by egaspro** [angular/universal-starter#105]
Hey, 
that's a great work you're doing with angular-universal guys.

I am playing with this repo for some time and when i tried to change structure of this project i encountered an issue: html is supplied from server, but the client no longer bootstraps into the hidden `<app></app>`.

Folder structure:
 / Universal-Starter
 /-/ client <--- was "src"
 /-/- client.ts
 /-/- index.html
 /-/-/ app <--- old app.component.ts split into these files
 /-/-/- app.ts
 /-/-/- app.css <--- (currently not used - just inline styles in app.ts [separate issue])
 /-/-/- app.html
 /-/-/-/ shared
 /-/-/-/- xLarge.directive.ts
 /-/-/-/ about
 /-/-/-/- about.directive.ts
 /-/-/-/ home
 /-/-/-/- home.directive.ts
 /-/ server <--- new folder
 /-/- server.ts <---- moved  from old "src" folder
 /- etc <--- other files - the same

Other changes:
* new packages - "html-loader" (also "css-loader", "style-loader")
* webpack.config.js -> commonConfig.module.loaders -> added a line `{ test: /\.html$/, loader: "html" },` ; changed entry options to fit new structure
* server.ts changed lines
  * changed `import {App} from '../client/app/app';`
  * added `const CLIENT = path.resolve(ROOT, 'client');`
  * changed `app.set('views', CLIENT);` (old `app.set('views', __dirname);` )
  * changed `preboot: { appRoot: 'app' }` (config in ngApp function)
  * changed `res.render(path.resolve(CLIENT, 'index'), config);` (in ngApp function)

If i wrap my bootstrap call in function and call something like `window.go() && preboot.complete()` client gets bootstrapped correctly, otherwise it adds "display: block;" on a `<body>` element and no content gets rendered in hidden <app> element. Seems like preboot can not point that hidden element to bootstrap into.

I tried playing with url options in ExpressEngineConfig type config in server.ts with no luck. Maybe there  is something that i am missing?

P.S. Separate issue is setting up webpack for css files (tryed using css-loader `{ test: /\.css$/, loader: "style!css" }` ) and it seems style-loader has inner use of 'window'.

Thanks for taking your time looking into this little problem i am having :)

Environment:
- Angular version: 2.0.0-rc.1
- Browser: Firefox 46
- Language: TypeScript 1.8.9
- OS:  Windows
- Platform: NodeJs

**Comment by gdi2290** [comment]
do you have a link to your repo with the changes?

**Comment by egaspro** [comment]
I've just imported it to my github: https://github.com/egaspro/angular-starter-tryout

**Comment by jeffwhelpley** [comment]
@egaspro obviously a lot has changed since this was posted. Please get the latest and try again. In general, when you move around the file structure, you are going to have to modify your webpack config and perhaps some other configs. Let me know if you run into any further issue.
