### ISSUE TITLE
nodemon constantly restarting

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#106]
Hello,

On the latest pull (today with all node modules reinstalled) I am experiencing an issue with nodemon constantly restarting I think..I am attaching a screenshot.
![screen shot 2016-06-14 at 10 03 32](https://cloud.githubusercontent.com/assets/2866604/16035461/80e9783c-3217-11e6-8e56-04b6705d6b8f.png)

**Comment by joaogarin** [comment]
I think this most an issue with nodemon. https://github.com/remy/nodemon/issues/844 I am actually on node 5.0.0 but I am getting this issue.

**Comment by mikkeldamm** [comment]
it is not a nodemon issue. Its because the bundle.js file was renamed to index.js. See the fix here: https://github.com/angular/universal-starter/pull/107

**Comment by MarkPieszak** [comment]
Nice catch Mikkel

**Comment by joaogarin** [comment]
Cool will close this one then!;)
