### ISSUE TITLE
AnimationBuilder module not found when upgrading to @angular-2.0.0-rc.2

### ISSUE THREAD

**Issue by vinodbhargava** [angular/universal-starter#110]
Hi,

I am getting compile time exception in universal when upgrading the starter project to angular 2.0.0-rc.2

Details are as below -

Node Version - 6.2.1
npm Version - 3.9.5

Dependencies in my package.json -

```
"dependencies": {
    "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/platform-server": "2.0.0-rc.2",
    "@angular/router": "2.0.0-rc.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.2",
    "angular2-in-memory-web-api": "0.0.11",
    "angular2-universal": "^0.103.0",
    "body-parser": "^1.15.0",
    "express": "^4.13.3",
    "html-pdf": "^2.0.1",
    "parse5": "^1.5.0",
    "preboot": "~2.0.10",
    "rxjs": "5.0.0-beta.6",
    "webshot": "^0.18.0"
  },
  "devDependencies": {
    "nodemon": "^1.8.1",
    "rimraf": "^2.5.2",
    "ts-loader": "^0.8.1",
    "typescript": "^1.8.7",
    "typings": "~0.8.1",
    "webpack": "^1.12.10",
    "webpack-dev-server": "^1.14.0",
    "webpack-merge": "^0.8.4"
  }

```

Exception -
![error_2](https://cloud.githubusercontent.com/assets/17468172/16218386/def9e9b0-379a-11e6-888c-186d85cefd05.PNG)

Please suggest.

**Comment by gdi2290** [comment]
universal doesn't support rc.2 at the moment

**Comment by vinodbhargava** [comment]
Any tentative timeline?

**Comment by gdi2290** [comment]
it's delayed a little bit because I want to also support the latest router

**Comment by vinodbhargava** [comment]
Hi Patrick @gdi2290, i took the reference of https://github.com/angular/universal/pull/448, and integrated this with angular 2.0.0-rc.2, however got below issues when try to run the project -

1. Reference to wrong import in node.ts file 
    (universal-master\modules\universal\src\node\platform\node.ts)
    `import {BrowserDetails} from '@angular/platform-browser/src/animate/browser_details';`  (Line no 8) - This breaks the server during start up only.

2. I tried removing the reference from the above file, then tried compiling universal code and was able to bring up the server.

3. Once the server was up, i tried to access `http://localhost:3000` and encountered with below error -
![universal_error_4](https://cloud.githubusercontent.com/assets/17468172/16303540/ca7c043e-396e-11e6-8595-73a3503ac502.PNG)

Also, can you please share any tentative date for universal's official support for angular rc2/rc3.

**Comment by gdi2290** [comment]
@vinodbhargava universal supports rc.2 and rc.3 now as of `0.103.2`
https://github.com/angular/universal-starter/commit/894f700f8123c032277991dbb15885f73a2e5fa3

**Comment by vinodbhargava** [comment]
Thanks @gdi2290
