### ISSUE TITLE
Routes and ROUTE_PROVIDER 

### ISSUE THREAD

**Issue by tettus** [angular/universal-starter#111]
Dear team,  do you have any working example of using routes instead of Route config from deprecated module

**Comment by MarkPieszak** [comment]
Hey Tettus, not yet the newest router (that just came out with rc2) is currently in Alpha, but Universal will be set up to work with it at some point no doubt!

**Comment by tettus** [comment]
Thank you very much for quick reply. 

Sent from my HTC

----- Reply message -----

**Comment by MarkPieszak** [comment]
@tettus The repo has been updated the other day to use the latest router3alpha
