### ISSUE TITLE
how to handle DOM api with universal

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal-starter#112]
how to handle use-cases related to DOM API
- cookies (read/write)
- localStorage

there can be scenarios where one have to read/write cookies .
Right now while server-side rendering `document` object is not available

**Comment by Hongbo-Miao** [comment]
[Angular 2 Universal Patterns](https://www.youtube.com/watch?v=TCj_oC3m6_U wi) explains.

**Comment by jeffwhelpley** [comment]
We have discussed this in other issues, but to recap:

universal service is a feature request: 
https://github.com/angular/universal/issues/309

use DI swapping for abstracting out localStorage and some equivalent (redis, etc.) on the server side.

for accessing cookies on the server side, get a handle to the request with `Zone.current.get('req')`. this will be improved in the future.
