### ISSUE TITLE
Error: Cannot find module '@angular/router-deprecated'

### ISSUE THREAD

**Issue by mmgyce** [angular/universal-starter#113]
I think this come from the Universal repo, it depends on router-deprecated which is removed since rc 3

**Comment by vinodbhargava** [comment]
For temporary solution you can install router-deprecated package till the team comes up with the update.

**Comment by MarkPieszak** [comment]
The starter uses router v3 alpha, maybe you need to wipe out node_modules and reinstall?

**Comment by gdi2290** [comment]
yeah, I forgot to remove it within universal can you make a PR to add it back here until I publish a patch

**Comment by mmgyce** [comment]
Ok , I already submitted a PR with the change, thanks
