### ISSUE TITLE
Solution problem: adding SEO meta tags to <head> 

### ISSUE THREAD

**Issue by kaaboeld** [angular/universal-starter#114]
Feature request for adding meta tags to <head/>
https://gist.github.com/kaaboeld/851bc3190eec67f6723c6054751ee2dc

This option passes the SEO test of Facebook.

**Comment by gdi2290** [comment]
we probably would name it MetaTagService rather than SEO

**Comment by jeffwhelpley** [comment]
Closing this as we already have an open issue in the Universal repo for this:

https://github.com/angular/universal/issues/309

**Comment by matiishyn** [comment]
hi guys
https://github.com/angular/universal/issues/309 is closed but it's not clear to me how can I update meta keywords/description tags.

When I try to use `angular2-meta.ts` service, method:
`this.meta.updateTag('name=description', {name: 'description', content: 'New description'});`
then I got this error 
`Error in SSR, serving for direct CSR
EXCEPTION: This method is not implemented in Parse5DomAdapter: getElementsByTagName
ORIGINAL STACKTRACE:
Error: This method is not implemented in Parse5DomAdapter: getElementsByTagName
    at ...
`

Please help me, how can I update `meta` tags?
