### ISSUE TITLE
need to click many times on home to have the view displayed

### ISSUE THREAD

**Issue by mathilde-pellerin** [angular/universal-starter#116]
Hi,

I just updated my app (which is more or less nothing more than the starter) to the new angular 2.0.0-rc.3 with the new router and the last version of angular-universal.
This new version allows us to use `styleUrls` which is nice!

But on the first load, there is no view loaded on startup:
![no view loaded on startup](https://cloud.githubusercontent.com/assets/3293937/16458245/53e7c428-3e16-11e6-8298-b841e01f07c0.png)
I have to click few times on home to get it finally loaded:
![home finally loaded](https://cloud.githubusercontent.com/assets/3293937/16458288/7d219648-3e16-11e6-98a7-2ba1b079a849.png)

And I have these two errors on the console:

> Uncaught reflect-metadata shim is required when using class decoratorscheckReflect 
> Failed to parse SourceMap: http://localhost:3000/dist/client/toSubscriber.js.map

I don't know if it is related to the problem or not, as for the moment I didn't find a a way to use dev tools with bundle from webpack...

Any help / advices would be really appreciated :)

**Comment by anop72** [comment]
If you try to fresh clone this repos. Everything is working.

I think it might be some minor wrong in your code.

**Comment by mathilde-pellerin** [comment]
You are totally right: I just found out that I didn't update my webpack config as you did!
Sorry about that.
