### ISSUE TITLE
Confused about express.static()

### ISSUE THREAD

**Issue by pokakhoaitay** [angular/universal-starter#117]
Assuming that i will deploy this project to my real server.
Follow the `server.ts` file, the root folder for express serve static files is whole `universal-start` folder (<=>`app.use(express.static(ROOT, {index: false}));`), then, i attemp to type this on the browser address bar: `http://ng-domain/src/server.ts`, the browser will download the source file, which should be prevent.

I am confused, @gdi2290, can you please explain more?

**Comment by gdi2290** [comment]
that was only there for development and should be changed for production

**Comment by pokakhoaitay** [comment]
I knew that. I mean do you intended implement it to this kit? Or dose this kit just is a very simple to understand  how the angular universal works? Since i need starter project that i can start to learn and enough for me to understand what i should to do to build a real project by my own that can good works on production.
Thanks!

**Comment by gdi2290** [comment]
there will be a fullstack angular2 starter release by the end of the month via http://www.meetup.com/AngularJS-MTV/events/232040136/

**Comment by pokakhoaitay** [comment]
wow...This is a very good news. I didn't known it. Waiting for your awesome works.
So, we will have a fullstack angular2 starter project  after that event meetup right?

**Comment by gdi2290** [comment]
ya or at the end of the month at the latest

**Comment by gdi2290** [comment]
kool, I limited the public files via https://github.com/angular/universal-starter/commit/cf1b8f77c9757eba22df1806107f604500045921

**Comment by pokakhoaitay** [comment]
@gdi2290, can you please get me a bit of info about  fullstack angular2 starter that you mentioned recently?
Thanks!!!

**Comment by gdi2290** [comment]
ya sorry I ended up not publishing it yet. NgModule delayed it since the structure on an ngApp completely changed

**Comment by pokakhoaitay** [comment]
yeah :) We are waiting for the good news from you, from that project. Thanks!

**Comment by ng-fullstack** [comment]
Hm... sorry but do we have any news for the fullstack angular 2 starter that you guys are talking about?

**Comment by gdi2290** [comment]
I merged most stuff to universal-starter. It's missing an auth example and redis/api etc

**Comment by pokakhoaitay** [comment]
That's cool! But not sure if you have a plan to integrate those missing stuff into universal-starter?
