### ISSUE TITLE
TS compile fails and rxjs cannot be found

### ISSUE THREAD

**Issue by indcoder** [angular/universal-starter#118]
A whole lot if these errors
   
    ERROR in C:\Users\indcoder\Documents\GitHub\universal-starter\typings\browser\ambient\node\node.d.ts
    (1162,9): error TS2300: Duplicate identifier 'mtime'.

    ERROR in C:\Users\indcoder\Documents\GitHub\universal-starter\typings\browser\ambient\node\node.d.ts
    (1163,9): error TS2300: Duplicate identifier 'ctime'.

    ERROR in C:\Users\indcoder\Documents\GitHub\universal-starter\typings\browser\ambient\node\node.d.ts
    (1164,9): error TS2300: Duplicate identifier 'birthtime'.

    ERROR in C:\Users\indcoder\Documents\GitHub\universal-starter\typings\browser\ambient\node\node.d.ts
    (1176,9): error TS2300: Duplicate identifier 'bytesWritten'.

    ERROR in C:\Users\indcoder\Documents\GitHub\universal-starter\typings\browser\ambient\node\node.d.ts
    (1429,9): error TS2300: Duplicate identifier 'root'.

    ERROR in C:\Users\indcoder\Documents\GitHub\universal-starter\typings\browser\ambient\node\node.d.ts
    (1433,9): error TS2300: Duplicate identifier 'dir'.

Also
[nodemon] starting `node dist/server/index.js`
module.js:442
    throw err;
    ^

Error: Cannot find module 'rxjs/observable/of'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\indcoder\Documents\GitHub\universal-starter\node_modules\@angular\router\src\router.js:17:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by MarkPieszak** [comment]
What version of TS are you using? What about Node&npm?
Also do you have typings 1.* ^ installed as well?

**Comment by indcoder** [comment]
`tsc --version`
version 1.8.10

npm --version
3.9.5

node --version 
v6.2.2

typings 
v1.3.1

**Comment by gdi2290** [comment]
remove the `typings` folder and run `npm run postinstall`

**Comment by indcoder** [comment]
Ran the postinstall and then ran npm start. Same issue

**Comment by gdi2290** [comment]
the problem is that you have an old version of typings with old config.
remove/update your `typings.json` to reflect the one is this repo
remove your `typings` folder
remove/update your `package.json` to reflect `typings` version in this repo
don't use your global `typings` unless it's version 1.x.x
