### ISSUE TITLE
Cannot start the project

### ISSUE THREAD

**Issue by JayKan** [angular/universal-starter#119]
After running `npm i` and `npm start`, app crashed due to missing module `methods`. (Please see attached screenshot for exact error).

![screen shot 2016-07-07 at 6 51 04 pm](https://cloud.githubusercontent.com/assets/1400300/16675289/88479b44-4474-11e6-92a4-a339203ffc8c.png)

Any ideas on how to resolve this?

- npm@3.3.12
- node@5.2.0

Thanks,
Jay

**Comment by gdi2290** [comment]
can you run
`rm -rf node_modules`
`npm cache clean`
`npm install`
this is either a problem with npm or node

**Comment by JayKan** [comment]
Thanks @gdi2290. I was able to resolve this issue by upgrading my node to 6.2.0 :)
