### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by daslicht** [angular/universal-starter#12]
Hi,
is it possible to start an Angular 2 App as client side only and later transform it as Universal App?
What do I need to be aware of ?
Or is it better to start as Universal App?

**Comment by gdi2290** [comment]
You can convert a client-side app to a universal one. You would have to use the renderer when interacting with the DOM
for example rather than this
```typescript
@Directive({
  selector: '[x-large]' // using [ ] means selecting attributes
})
export class XLarge {
  constructor(element: ElementRef) {
    // simple DOM manipulation to set font size to x-large
    // `nativeElement` is the direct reference to the DOM element
    element.nativeElement.style.fontSize = 'x-large';
  }
}
```
you would need to do this
```typescript
@Directive({
  selector: '[x-large]'
})
class XLarge {
  constructor(element: ElementRef, renderer: Renderer) {
    // we must interact with the dom through Renderer for webworker/server to see the changes
    renderer.setElementStyle(element, 'fontSize', 'x-large');
  }
}

```

**Comment by daslicht** [comment]
Ok that sounds feasible. 
So instead of learning anything now I can just start by creating a client side app only to get started with Angular 2 at all.

Thank you !

**Comment by daslicht** [comment]
The test rest can just be the same ?

**Comment by gdi2290** [comment]
are you talk about test case or testing a REST service?
