### ISSUE TITLE
There are bugs with the new version

### ISSUE THREAD

**Issue by medozs** [angular/universal-starter#123]
It renders twice now when server rendering (once at the server, once at the client), and Augury doesn't recognize the app as Angular2 Components. 
The old version of the pack didn't have these issues. 
Also: how to solve "DEPRECATION WARNING: `buildClientScripts` is no longer supported and will be removed in next release." warning?

**Comment by jeffwhelpley** [comment]
Rendering on both sides is normal. Preboot should handle the transition from server view to client view. There have been many updates since this has been posted. Please check again and let me know if you see any other issues.
