### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by Junik** [angular/universal-starter#124]
After start "universal-starter" in visual studio code with Node.js launch setting and program entry point "server.ts" all work  but in debug console  EXCEPTION.

**DEBUG CONSOLE :**
Listening on: http://localhost:3000
EXCEPTION: Error: Uncaught (in promise): Error: Protocol "c:" not supported. Expected "http:"
STACKTRACE:
Error: Uncaught (in promise): Error: Protocol "c:" not supported. Expected "http:"
    at resolvePromise (C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:496:32)
    at C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:473:14
    at ZoneDelegate.invoke (C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:281:29)
    at Object.NgZoneImpl.NgZoneImpl._a.inner.inner.fork.onInvoke (C:\git\universal-starter-master\node_modules\@angular\core\src\zone\ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:280:35)
    at Zone.run (C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:174:44)
    at C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:529:58
    at ZoneDelegate.invokeTask (C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:314:38)
    at Object.NgZoneImpl.NgZoneImpl._a.inner.inner.fork.onInvokeTask (C:\git\universal-starter-master\node_modules\@angular\core\src\zone\ng_zone_impl.js:44:41)
    at ZoneDelegate.invokeTask (C:\git\universal-starter-master\node_modules\zone.js\dist\zone-node.js:313:43)

**launch.json** 
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/server.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/dist/server"
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command.PickProcess}",
            "port": 5858,
            "sourceMaps": false,
            "outDir": null
        }
    ]
}
```
**tasks.json**
```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-w", "-p", "."],
    "showOutput": "silent",
    "isWatching": true,
    "problemMatcher": "$tsc-watch"
}
```

I will be very grateful if someone can help solve it.

**Comment by MarkPieszak** [comment]
@Junik Is this a project based off of the Angular CLI by any chance?
What version of Universal are you using in your app also?

**Comment by MarkPieszak** [comment]
You're also trying to access a `ts` file as the program.

    "program": "${workspaceRoot}/src/server.ts"

You need to point to your `dist` folders compiled `.js` file like this:
Then once you do `npm run build` and the files have been built, you'll be able to do **F5** to start the project with VSCode.

    "program": "${workspaceRoot}/dist/server/index.js",
