### ISSUE TITLE
data is not showing after rendered from the server

### ISSUE THREAD

**Issue by amitgaikwad712** [angular/universal-starter#126]
We have used this seed project for our website development.
  due to "prebootComplete" in client.ts, it is showing data and after some time it will remove the css of it and data is getting hide.
after commenting the "ngApp().then(prebootComplete);" it will work fine but this will not generate any click event , keyup event in DOM object.

**Comment by jeffwhelpley** [comment]
When you comment out `ngApp().then(prebootComplete)` then you are only seeing the server view. You need that in order for preboot to switch from server to client view. Try changing the preboot `buffer` settings to false and see if that changes anything. Can you share with me your code?
