### ISSUE TITLE
Deploying production build

### ISSUE THREAD

**Issue by beckmeindia** [angular/universal-starter#128]
Hey, 
       I ran **npm run build** and in the dist folder it said "cannot find src/index" on adding it manually, the error vanished. Was it a bug against my compilation or a standard error that can be ignored?

Also I was curious to know that if I want to deploy on Google Cloud Platform for node.js would the way be the standard procedure for a node.js application as laid out in this: https://cloud.google.com/nodejs/

Thanks,
Rahul

**Comment by goelinsights** [comment]
+1 I've struggled with this on Google Cloud or in deploying production build using the Heroku 1 click deployment

**Comment by jeffwhelpley** [comment]
@MarkPieszak have you tried deploying the starter on any other environment? If not, we should try a couple and potentially make some adjustments. Let's talk about this today.

**Comment by jeffwhelpley** [comment]
Please note that in general, we want to document and potentially add configuration to make it easy to deploy the starter. In addition to Google Cloud, let's make sure we try this out with Heroku (from #122) and a couple other popular services.

**Comment by MarkPieszak** [comment]
@jeffwhelpley I haven't in a while, but I can try to deploy it to Heroku or something and see how it goes.

I think I remember others having trouble with it as well though...

**Comment by beckmeindia** [comment]
Thanks @MarkPieszak 
I was having a little tough time finding documentation for angular-universal (have looked at the doc file).
Could you suggest something that's more elaborate?

Thanks and it works great with Heroku
