### ISSUE TITLE
ERROR in ./src/bootstrap.ts

### ISSUE THREAD

**Issue by jeyachanthuruj** [angular/universal-starter#13]
When i try to `npm run build` in the command this error will appear.

````bash
jeyachanthuruj@JeyarathnamJ:~/Workspace/ngUnivers/universal-starter$ npm run build

> angular2-universal-starter@1.0.1 build /home/jeyachanthuruj/Workspace/ngUnivers/universal-starter
> webpack

ts-loader: Using typescript@1.7.3 and /home/jeyachanthuruj/Workspace/ngUnivers/universal-starter/tsconfig.json
Hash: 06903815e07b1afaab6c
Version: webpack 1.12.9
Time: 186ms
    + 1 hidden modules

ERROR in ./src/bootstrap.ts
Module build failed: TypeError: undefined is not a function
    at ensureTypeScriptInstance (/home/jeyachanthuruj/Workspace/ngUnivers/universal-starter/node_modules/ts-loader/index.js:147:38)
    at Object.loader (/home/jeyachanthuruj/Workspace/ngUnivers/universal-starter/node_modules/ts-loader/index.js:365:14)

````

**Comment by gdi2290** [comment]
this might be a problem with ts-loader and typescript 1.7

**Comment by mikkeldamm** [comment]
Yeah, it seems to be working when forcing typescript in version **1.6.2**

**Comment by jeyachanthuruj** [comment]
Thanks, I'll try.

**Comment by angelUniversal** [comment]
<pre>
--- a/package.json
+++ b/package.json
@@ -35,7 +35,7 @@
     "ts-loader": "^0.5.6",
     "ts-node": "^0.2.4",
     "tsd": "^0.6.5",
-    "typescript": "^1.6.2",
+    "typescript": "~1.6.2",
     "webpack": "^1.12.2",
     "webpack-dev-server": "^1.12.1"
   }
</pre>
for tag 1.0.1 Angular 2.0.0-alpha.45

**Comment by anymos** [comment]
Good morning,

Same here, even with the modification. This is an install from scratch


> angular2-universal-starter@1.0.1 prestart /Users/tantr/REPOS/universal-starter
> npm run build


> angular2-universal-starter@1.0.1 build /Users/tantr/REPOS/universal-starter
> webpack

ts-loader: Using typescript@1.7.5 and /Users/tantr/REPOS/universal-starter/tsconfig.json
Hash: 06903815e07b1afaab6c
Version: webpack 1.12.9
Time: 117ms
    + 1 hidden modules

ERROR in ./src/bootstrap.ts
Module build failed: TypeError: compiler.parseConfigFile is not a function
    at ensureTypeScriptInstance (/Users/tantr/REPOS/universal-starter/node_modules/ts-loader/index.js:147:38)
    at Object.loader (/Users/tantr/REPOS/universal-starter/node_modules/ts-loader/index.js:365:14)

> angular2-universal-starter@1.0.1 start /Users/tantr/REPOS/universal-starter
> ts-node server.ts

/Users/tantr/REPOS/universal-starter/node_modules/ts-node/dist/ts-node.js:32
    return ts.parseConfigFile(config, ts.sys, fileName);
              ^

**Comment by gdi2290** [comment]
I rebuilt the build process and removed ts-node can you try again and open a new issue if there are problems
