### ISSUE TITLE
Getting errors on running npm install

### ISSUE THREAD

**Issue by Subway19** [angular/universal-starter#135]
![capture1](https://cloud.githubusercontent.com/assets/14835320/17272099/5f327c8a-56ab-11e6-98da-b48657ca97a4.PNG)
![capture](https://cloud.githubusercontent.com/assets/14835320/17272101/6137f65e-56ab-11e6-818c-928a78ad01d9.PNG)

installed typings globally still getting error. Tried npm install both on node v6 and v4.4.7

**Comment by MarkPieszak** [comment]
Are you behind a proxy or anything? It looks like your `Unable to connect`
Does it work when you manually put in `typings install` in the command line at this directory?

**Comment by Subway19** [comment]
@MarkPieszak ` typings install` gives following error. Yes, i am behind proxy, however i have set up npm and node for proxy. I am able to run` npm install `in other projects on my system. Does i have to configure proxy for typings or something like that?
![capture](https://cloud.githubusercontent.com/assets/14835320/17272507/6f5ebaa6-56b5-11e6-9571-7c7041e96a44.PNG)

**Comment by MarkPieszak** [comment]
Yes you need to have access to that address I believe (api.typings.org). Give that a shot and it should clear it right up.

Typings will soon be gone anyway once the starter moves to Typescript 2 & `@types`. Everything will be in the package.json and downloaded via npm. :)

**Comment by Subway19** [comment]
Well, how to set up proxy for typings?

**Comment by Subway19** [comment]
@MarkPieszak  Ok. Thanks for the quick replies. This resolved the issue --- https://github.com/typings/typings/issues/106. We are working  for Server-Side rendering of Client's Web Application in Angular 2 .  :)

**Comment by MarkPieszak** [comment]
Glad you got it working! Enjoy. 👍
