### ISSUE TITLE
How to import jQuery plugins in Angular Universal

### ISSUE THREAD

**Issue by shoudaos** [angular/universal-starter#137]
please help with this issue. 
In **angular2-webpack-starter** for importing jquery plugins i'm doing this:
in webpack.config define jquery variables in **ProvidePlugin**:
**jQuery: 'jquery',
$: 'jquery',**
... and etc.
And in `ts` component i'm importing the plugin, for example:
`import 'jquery.backstretch'`
And all works fine, in console.log it shows the lib.

**Can you help what to do in angular2 universal webpack???**

i'm doing the same, but it throws the error when starting dist/server/index.js
```
ReferenceError: jQuery is not defined
    at Object.<anonymous> (/Users/artem/projects/universal-starter/node_modules/jquery.backstretch/jquery.backstretch.js:1472:3)
```

**Comment by MarkPieszak** [comment]
You're in the wrong repo :)
Make an issue here at the angular2 webpack starter : https://github.com/AngularClass/angular2-webpack-starter/issues

**Comment by shoudaos** [comment]
Why? it is the question for angular universal, am i wrong?

**Comment by MarkPieszak** [comment]
Just noticed you are referring to Universal at the bottom :)
So at the moment, jQuery or most any other DOM related things won't work with Universal since Node has no concept of them. I think eventually we'll try to add some sort of support so that, at the very least it doesn't error out on the server-side. (Or switch out to jsdom as a parser for those who want to use jQuery) You can follow issue https://github.com/angular/universal/issues/490

For now, I recommend avoiding anything jQuery!

**Comment by drejohnson** [comment]
Couldn't you require jQuery within the` isBrowser` conditional?

**Comment by MarkPieszak** [comment]
You could do a lot of **if** statements for each time, if you're not using jQuery very much this could be a decent solution you're right. @drejohnson 

I think we're hoping we have a more well-rounded solution for these kinds of things in the future. 

```
import { isBrowser } from 'angular2-universal';

if (isBrowser) {
  var jquery = require('jquery');
}
```

**Comment by jeffwhelpley** [comment]
So, the sort answer here is to abstract out all code referencing jQuery either using `isBrowser` or (preferably) using DI abstraction so your code references an abstract interface class which is implemented differently on the client and server.

However, one heads up to be aware of is that further out in the future (say months away, so don't hold your breath), we are working on some advanced functionality for pre-rendering (i.e. so only for static site generation) which would include DOM emulation and thus would allow for jQuery.

For now, just abstract it out.

**Comment by ohabash** [comment]
what is `angular2-universal`? my universal app works fine without it. Above suggests I need it, but i cant compile it without the following errors.

>/node_modules/angular2-platform-node/node-platform.d.ts(1,10): error TS2305: Module '"/node_modules/@angular/platform-browser/platform-browser"' has no exported member 'AnimationDriver'.


>/node_modules/angular2-platform-node/node-renderer.d.ts(2,10): error TS2305: Module '"/node_modules/@angular/platform-browser/platform-browser"' has no exported member 'AnimationDriver'.


>/node_modules/angular2-platform-node/tokens.d.ts(1,10): error TS2305: Module '"/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.


>/node_modules/angular2-universal/browser/universal-module.d.ts(1,23): error TS2305: Module '"/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by uibhanu5** [comment]
i have angular 6 app done with server side rendering im facing issues in server please help me to solve this.

Error: jQuery requires a window with a document
Error: jQuery requires a window with a document
Error TypeError: window.scroll is not a function
