### ISSUE TITLE
Upgrade @angular/router

### ISSUE THREAD

**Issue by GabrielDelepine** [angular/universal-starter#140]
Hi,

The starter is currently running ```"@angular/router": "3.0.0-alpha.8",```.

It would be nice to have it out of the box with ```"@angular/router": "3.0.0-beta.2"```.

from **alpha.8** to **beta.2**

**Comment by manekinekko** [comment]
it's coming in https://github.com/angular/universal-starter/pull/141

**Comment by Hongbo-Miao** [comment]
This can be closed
