### ISSUE TITLE
latest universal-starter cannot run

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/universal-starter#144]
My node version is v6.3.1, npm is v3.10.3
After clone the lastest version starter including [this PR](https://github.com/angular/universal-starter/commit/cf4bb7127b2a5ea8b75a786ed8d8c7a7848efccf). (Before this PR, the universal-starter runs well)

And I did `npm install -g typescript@beta` before.
`npm i` then `npm start`, got the error 

**At the front, there are some other typings error, please check the [full log](https://jpst.it/LR0u)**

> npm ERR! Darwin 15.6.0
> npm ERR! argv "/Users/xxx/.nvm/versions/node/v6.3.1/bin/node" "/Users/xxx/.nvm/versions/node/v6.3.1/bin/npm" "run" "build"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! universal-starter@2.0.0 build: `webpack`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the universal-starter@2.0.0 build script 'webpack'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the universal-starter package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     webpack
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs universal-starter
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls universal-starter
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/xxx/universal-starter/npm-debug.log
> 
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/Users/xxx/.nvm/versions/node/v6.3.1/bin/node" "/Users/xxx/.nvm/versions/node/v6.3.1/bin/npm" "start"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! universal-starter@2.0.0 prestart: `npm run build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the universal-starter@2.0.0 prestart script 'npm run build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the universal-starter package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs universal-starter
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls universal-starter
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/xxx/universal-starter/npm-debug.log

**Comment by manekinekko** [comment]
do have `webpack` installed?

**Comment by Hongbo-Miao** [comment]
https://github.com/angular/universal-starter/commit/a40f0d1b24d04a62a72bd1199ad0334405a76534 fixed, now it works well!

**Comment by zenithtekla** [comment]
I run into the same issue, even after going through your fix

`npm start

> universal-starter@2.0.0 prestart C:\Users\PhucTran\uninode
> npm run build


> universal-starter@2.0.0 prebuild C:\Users\PhucTran\uninode
> rimraf dist


> universal-starter@2.0.0 build C:\Users\PhucTran\uninode
> webpack


C:\Users\PhucTran\uninode\node_modules\ts-node\src\index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
webpack.config.ts (1,15): Cannot find name 'require'. (2304)
webpack.config.ts (2,12): Cannot find name 'require'. (2304)
webpack.config.ts (3,22): Cannot find name 'require'. (2304)
webpack.config.ts (70,12): Cannot find name '__dirname'. (2304)
webpack.config.ts (75,30): Cannot find name '__dirname'. (2304)
webpack.config.ts (82,20): Cannot find name 'require'. (2304)
webpack.config.ts (83,1): Cannot find name 'module'. (2304)
webpack.config.ts (101,33): Cannot find name '__dirname'. (2304)
    at getOutput (C:\Users\PhucTran\uninode\node_modules\ts-node\src\index.ts:253:17)
    at C:\Users\PhucTran\uninode\node_modules\ts-node\src\index.ts:263:16
    at Object.compile (C:\Users\PhucTran\uninode\node_modules\ts-node\src\index.ts:398:17)
    at Module.m._compile (C:\Users\PhucTran\uninode\node_modules\ts-node\src\index.ts:299:46)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\PhucTran\uninode\node_modules\ts-node\src\index.ts:302:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PhucTran\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! universal-starter@2.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the universal-starter@2.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the universal-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs universal-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls universal-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PhucTran\uninode\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PhucTran\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! universal-starter@2.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the universal-starter@2.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the universal-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs universal-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls universal-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PhucTran\uninode\npm-debug.log
`

**Comment by gdi2290** [comment]
@zenithtekla can you try again with a clean install and pull latest
https://github.com/angular/universal-starter/compare/0c3294a16e783bc9ea7d8a1526ac06e768a9d8bd...master

delete node_modules
run `npm cache clean`
