### ISSUE TITLE
Choice of loader for JSON files

### ISSUE THREAD

**Issue by DamonGant** [angular/universal-starter#149]
You should consider using a loader that returns JSON objects when loading JSON files via import for the server config, since that is the default behavior for Node's require and might [confuse people](http://stackoverflow.com/a/39000803/1754827).

If you're trying to keep the parts as close as possible (I mean, I've never considered bundling a server with webpack before), maybe this caveat should be noted in the readme.

**Comment by Hongbo-Miao** [comment]
I met this issue:

So usually for a node.js app we can do this:
import * as config from '../config.json';
console.log(config.api);

But now we need do like
import * as config from '../config.json';
const json = JSON.parse(config);  // <- need this line
console.log(json.api);

**Comment by gdi2290** [comment]
thanks for the issue. I added json-loader
