### ISSUE TITLE
No server-side rendering?

### ISSUE THREAD

**Issue by manfredsteyer** [angular/universal-starter#15]
Hi,

I think, I don't get it. I've cloned this repo and did a ``npm install`` as well as a ``npm start``. Everything seems to work fine - the server is started at port 3000 and I can access it with a browser.

But when I trace the received html, I don't see anything that has been pre-rendered at server-side. I just see angular2-code that is executed at client-side, things like in the next listing. And it doesn't work without javascript.

Do I have to enable server-side rendering in this starter-kit?
Have I done something wrong?

Best wishes,
Manfred

```
<body>

  <app>
    Loading...
  </app>

  <script src="/node_modules/reflect-metadata/Reflect.js"></script>
  <script src="/node_modules/zone.js/dist/zone.js"></script>
  <script src="/__build__/bundle.js"></script>
</body>
```

**Comment by angelUniversal** [comment]
works for me tag 1.0.1 Angular 2.0.0-alpha.45 Linux
