### ISSUE TITLE
Gap events are ignored

### ISSUE THREAD

**Issue by Honn** [angular/universal-starter#150]
I might be missing some setup, but I can't seem to get the gap events handling to work.

To experiment a bit I tried throttling the browser and changing the data-bound input field on the home screen before index.js has loaded. I expected Universal to rerun the events, but once the js takes over the field is reset back to it's default value instead of what I had typed. I've tried setting preboot in main.node.ts to true and to { appRoot: 'app' }, but I get the same result.

Is there some additional setup required to handle gap-events? If so it would be great with documentation of what it is.

**Comment by Honn** [comment]
I saw there will be a new version of Angular Universal in a few days with full preboot integration, so perhaps this issue will go way once that comes.

**Comment by MarkPieszak** [comment]
It might, I haven't experienced this one myself, usually slowing it down has no issues. What version of Preboot are you currently using?
@jeffwhelpley Haven't ran into this one myself, not sure if you have? Might be gone in 4.*

**Comment by jeffwhelpley** [comment]
@Honn definitely wait for the next version. Once that is out, there will only be a couple reasons why an event is not captured or replayed:

1. Inline preboot isn't included or init() within inline code is not run to start listening for events.
2. preboot.complete() not called to replay events
3. The specific event you are trying to capture is not in the default list of events
4. Your client side view is drastically different than your server view for some reason.

The first two should be covered by the universal lib itself so you shouldn't have to worry about them. For number 3, it is really easy to add custom events. Just read this: https://github.com/angular/preboot. For number 4, the very simple workaround whenever you see events being captured but not replayed correctly is to add a unique ID attribute to your element that has the event. In most cases, preboot can figure out the client side element to run the events against without an ID, but the fallback for whenever it gets confused is to see if there is an client element with an ID attribute value that matches the server element ID attribute value.

Again, all this is for the latest preboot, so wait until the RC5 changes are done with universal in a couple days and then you can try this out and let us know.

**Comment by jeffwhelpley** [comment]
OK, if you get the latest this should be fixed. Please re-open this if that is not the case.
