### ISSUE TITLE
ngFor template not rendered in child route

### ISSUE THREAD

**Issue by Junik** [angular/universal-starter#151]
After add  *ngFor to Component template  repeater template not rendered on server.
and in view-source:
`
...
 
...
`
Can someone help?

**Comment by MarkPieszak** [comment]
What are you trying to loop through, can you post some of the data and what your ngFor looks like as well? The class / etc. thanks!

**Comment by Junik** [comment]
``` typescript
@Component({
  selector: 'page-tree',
  template: `<div  *ngFor="let item of items">test #{{item}}</div>`
})
export class PageTreeComponent {
    public items:Array<string>=["1","2","3","4","5"]
}

```

in view-source -> It came from the server  or when do not bootstrap app in client side (client.ts):  
``` html
 <page-tree><!--template bindings={}--></page-tree>
```

when inspect element
``` html
<page-tree>
<!--template bindings={}-->
<div>test #1</div>
<div>test #2</div>
<div>test #3</div>
<div>test #4</div>
<div>test #5</div>
</page-tree>
```

**Comment by MarkPieszak** [comment]
@Junik Is everything working ok now? Apologies been swamped.

**Comment by Junik** [comment]
Hi, yes it is my fall error in constructor of 'PageEditorComponent'. End error related to third party lib.

**Comment by ymachupicchuy** [comment]
Hi, what was the problem now and how did you fix it? I have a similar problem.
