### ISSUE TITLE
Upgrade to RC6

### ISSUE THREAD

**Issue by Junik** [angular/universal-starter#154]
Please upgrade to Angular RC6

**Comment by MarkPieszak** [comment]
Support for the latest rc5/6 angular (with NgModules) will be coming soon,  you can follow https://github.com/angular/universal/issues/511 to track when it's finished & published to npm.

**Comment by Hongbo-Miao** [comment]
@Junik Check https://github.com/angular/universal-starter/commit/45f8fcd053c235f5a6ad7300d9a818ba885f4261
