### ISSUE TITLE
How do i can use NgModule?

### ISSUE THREAD

**Issue by pokakhoaitay** [angular/universal-starter#155]
I read this guide for NgModule: [https://angular.io/docs/ts/latest/guide/ngmodule.html](url)
But it seems that the @angular/core has no any member called NgModule exported.
Or was I missed somethings else? What i need to config to get ngModule available?
Thanks!
--------
**UPDATE: ** I heard that NgModule will be available in angular 2 rc.5/6. I will try to update the packages

**Comment by MarkPieszak** [comment]
@pokakhoaitay Also Universal itself needs to be updated to work with rc5/6, so at the moment I'd just create your application normally, then you can add in Universal.

You can track https://github.com/angular/universal/issues/511 if you'd like to see when it gets published. Best of luck!
