### ISSUE TITLE
Can't Start Application

### ISSUE THREAD

**Issue by medozs** [angular/universal-starter#156]
Hello, 
I can't start the app, and I get this error. Can you help?
![capture](https://cloud.githubusercontent.com/assets/16297164/18504035/2a97d3f2-7a2e-11e6-96a2-7e6a3fd27b35.PNG)

Thank You.

**Comment by bohacc** [comment]
I have the same issue (windows 10, node 4.3.1, npm 3.7.3)

**Comment by mmgyce** [comment]
Add this to tsconfig.json, it works to me
```json
{
    "compilerOptions": {
        "types": ["node"]
    }
}
```

**Comment by bohacc** [comment]
Yes, now work, thanks

**Comment by medozs** [comment]
It now compiles and starts without errors, however, I get the app stuck at "Hello Angular2 App" and Angular2 is not loading. Any help?

**Comment by Hongbo-Miao** [comment]
this can be closed now, it has been fixed in latest version
https://github.com/angular/universal-starter/blob/master/tsconfig.json#L20
