### ISSUE TITLE
Livereload

### ISSUE THREAD

**Issue by crebuh** [angular/universal-starter#157]
I wondering if it is possible to reload the application in the browser automatically when running `npm start` and `npm run watch` in two separate terminals?

Isn't this working by default or I'm just missing something? e.g. when working with the Angular CLI with Webpack, the livereload process is already included.

anybody with same issues?

**Comment by crebuh** [comment]
I added the following to the webpack.config.js fiel

     var LiveReloadPlugin = require('webpack-livereload-plugin');

in the plugins sections of the commonConfig

    new LiveReloadPlugin({
      appendScriptTag : true
    })

The browser is now reloaded automatically. The only remaining issue is that the page is reloaded twice. On the first attempt localhost is unavailable and on the second attempt the page is loaded correctly.

**Comment by jeffwhelpley** [comment]
@crebuh this is because you are reloading based on file changes instead of source file changes. You need to wait until the server restarts before you do the live reload.
