### ISSUE TITLE
Routing doesn't work, just displays 'Hello Universal App'

### ISSUE THREAD

**Issue by medozs** [angular/universal-starter#159]
Can someone help? Can someone provide me with example that uses routing and controls?

**Comment by MarkPieszak** [comment]
Think we'll be updating the example some more in the coming days to spruce it up!

**Comment by davidmontgom** [comment]
I added routing..worked but i get this in the logs:

Error: Template parse errors:
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("
    <div class="container">
    <main>
        [ERROR ->]<router-outlet></router-outlet>
        
    </m"): App@4:8
    at TemplateParser.parse (/Users/davidmontgomery/Documents/frontend/green2/node_modules/@angular/compiler/bundles/compiler.umd.js:8530:21)
    at RuntimeCompiler._compileTemplate (/Users/davidmontgomery/Documents/frontend/green2/node_modules/@angular/compiler/bundles/compiler.umd.js:16905:53)


Also view source does not show the the html elements.  My rc4 worked

**Comment by MarkPieszak** [comment]
Might of just set it up wrong or something. No worries, yes just wait I'll try and update it today if I can, on a 10 hour plane ride, if the wifi is decent I'll fix it up.

**Comment by gdi2290** [comment]
thanks for the issue. I updated the repo with router included
