### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#16]
I am getting an error in ubuntu that says 

 Unable to compile TypeScript

server.ts (1,26): Cannot find module 'express'. (2307)
server.ts (13,18): Cannot find name '__dirname'. (2304)
server.ts (18,24): Cannot find name '__dirname'. (2304)
server.ts (21,15): Parameter 'req' implicitly has an 'any' type. (7006)
server.ts (21,20): Parameter 'res' implicitly has an 'any' type. (7006)
----------------------------------

npm ERR! Linux 2.6.32-042stab103.6
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-universal-starter@1.0.1 start: `ts-node server.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-universal-starter@1.0.1 start script 'ts-node server.ts'.
npm ERR! This is most likely a problem with the angular2-universal-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node server.ts
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-universal-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/joao/angular-universal/npm-debug.log

Its running fine on mac os =/

Express is installed and present in node_modules so that is not the issue.

**Comment by valorkin** [comment]
rm -rf node_modules
and follow https://github.com/angular/universal-starter#installation
npm node ts versions?

**Comment by gdi2290** [comment]
run `tsd install node express --save`

**Comment by joaogarin** [comment]
Thanks @gdi2290 fixed it =)
