### ISSUE TITLE
error TS2430: Interface 'ErrorConstructor' incorrectly extends interface 'ErrorStackTraceLimit'

### ISSUE THREAD

**Issue by goriunov** [angular/universal-starter#163]
Hello . 
 I am using npm 3.10.3  node v6.5.0 
 I am getting an error when i try to run npm start

Child
    Hash: 95f608ca927f991115b2
    Version: webpack 2.1.0-beta.22
    Time: 16573ms
       Asset     Size  Chunks             Chunk Names
    index.js  3.55 MB       0  [emitted]  main
     [317] ./src async 160 bytes {0} [built]
        + 533 hidden modules
    
    ERROR in /Users/goriunov/Desktop/Uneversal/universal-starter/node_modules/typescript/lib/lib.es5.d.ts
    (898,11): error TS2430: Interface 'ErrorConstructor' incorrectly extends interface 'ErrorStackTraceLimit'.
      Types of property 'stackTraceLimit' are incompatible.
        Type 'number' is not assignable to type '(limit: number) => void'.
Child
    Hash: e35d5441a7dbe542ed4e
    Version: webpack 2.1.0-beta.22
    Time: 8692ms
       Asset     Size  Chunks             Chunk Names
    index.js  10.4 kB       0  [emitted]  main
        + 16 hidden modules
    
    ERROR in /Users/goriunov/Desktop/Uneversal/universal-starter/node_modules/typescript/lib/lib.es5.d.ts
    (898,11): error TS2430: Interface 'ErrorConstructor' incorrectly extends interface 'ErrorStackTraceLimit'.
      Types of property 'stackTraceLimit' are incompatible.
        Type 'number' is not assignable to type '(limit: number) => void'.

**Comment by gdi2290** [comment]
thanks, should be fixed via https://github.com/angular/universal-starter/commit/9669dd70d2e2223171e0e3615920cf96251a3e4b
