### ISSUE TITLE
How to integrate a testing environment

### ISSUE THREAD

**Issue by crebuh** [angular/universal-starter#165]
Hi guys,

really great project that you have established with angular universal. For my own project I want to include some tests. There are so many different configurations out there (e.g. https://angular.io/docs/ts/latest/guide/webpack.html#!#common-configuration), but I'm not sure how to make it work with the current project structure. 

In general most of the projects have splitted config files for dev, prod and testing. But the universal-starter project is merging the config for client and server.

Do you have any advice how to start? For example I used the karma.config and karma-test-shim settings from the Angular Docs (link from above) and added them to the project. I also modified the webpack.config file and added this:

``
var testConfig = {
  devtool: 'inline-source-map',
  resolve: {
    extensions: ['', '.ts', '.js', 'json']
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader']
      },
      {
        test: /\.html$/,
        loader: 'html'
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'null'
      },
      {
        test: /\.scss$/,
        exclude: root('/src'),
        loader: 'null'
      },
      {
        test: /\.scss$/,
        include: root('/src'),
        loader: 'raw'
      }
    ]
  }
};
``

But I dont know how to tell the karma-config file now how to use this settings?

**Comment by gdi2290** [comment]
for right now you have to create different entry files and in this repo the entry files are `client.ts`/`server.ts` so you would make `test.ts` that would use the same testing setup as you normally would in a normal browser app. I'm planning on adding an example to this repo and more testing helpers in the near future. Please create an issue at [angular/universal](https://github.com/angular/universal)

**Comment by crebuh** [comment]
Yes an example would be great I modify my setup now to have an test.ts file as entry point, but then I'm struggeling with the execution of the tests. It seems that there are some problems related to the filepath. 

What about the webpack config for the testing environment, would you add it like the other configs and merge it at the end like:

      // Testing
  webpackMerge({}, defaultConfig, commonConfig, testConfig)

Not sure that this is right, because in the karma-config then I'm doing something like this.

     var webpackConfig = require('./webpack.config');

     webpack: webpackConfig.testConfig,

I will also add and issue at the universal repo.

**Comment by jeffwhelpley** [comment]
Trying to cut down on noise, so I am going to close this and we will track creating an example with https://github.com/angular/universal/issues/544
