### ISSUE TITLE
How to add third party libraries ?

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/universal-starter#166]
Hi guys, 
I would like to import gsap into my angular universal starter. There is no @types/gsap for now, and I cannot find where in the starter I should import a third party library.
Can you help me with that ? 
Thanks =)

**Comment by MarkPieszak** [comment]
Do you mean how to install it? `npm i --D @types/gsap` to install to devDependencies?

**Comment by GrandSchtroumpf** [comment]
No, I mean gsap doesn't provide @types/gsap for now, so I only have the traditional .min.js file. And of course it is not enough to add it in a script in index.html. What would be the best way to import this library (or any other .min.js library) into my components ?

**Comment by flauc** [comment]
Hi @GrandSchtroumpf did you manage to resolve your problem? I'm also trying to import external libraries and  it isn't going that good.

**Comment by GrandSchtroumpf** [comment]
Hi @flauc, no I still not manage to import it. When I do `import 'gsap'` it looks into the right file, but I cannot run the server then with `npm start`. I don't know if this is something I should do with webpack or angular ...

**Comment by GrandSchtroumpf** [comment]
I ended by using a cdn...

**Comment by jeffwhelpley** [comment]
The solution here is pretty straightforward. Just create your own .d.ts file with the type definitions. Or you put the library JavaScript in a ts file and run:

```
tsc --declaration js.ts
```
