### ISSUE TITLE
Exception 200 - Ok

### ISSUE THREAD

**Issue by khanyuriy** [angular/universal-starter#168]
I call http.get() in AppComponent ngOnInit, server stops with 

200 - Ok
EXCEPTION: 200 - Ok
/home/khan/code/stroika/node_modules/zone.js/dist/zone-node.js:129
                        throw error;
                        ^
200 - Ok

**Comment by MarkPieszak** [comment]
What exact call are you trying to make can you some code so I can take a look and test it out?

**Comment by MarkPieszak** [comment]
Just tried this, and it seems to work fine, let me know if you're doing anything different

```
  ngOnInit () {
    this.http.get('http://jsonplaceholder.typicode.com/posts/1').subscribe((response) => {
      console.log(response);
    });
  }
```

**Comment by khanyuriy** [comment]
Thank you for your time.
I finally reproduced the error on clean starter project.
changes in app.ts
`
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw';
`
...
`
@Component({
  selector: 'home',
  template: 'Home component'
})
export class Home {
  constructor(private http: Http) {
    http.get('/test')
      .catch(this.handleError)
      .subscribe(response => {
      console.log(response.json())
    })
  }
  private handleError(error: any) {
		// In a real world app, we might use a remote logging infrastructure
		// We'd also dig deeper into the error to get a better message
		let errMsg = (error.message) ? error.message :
			error.status ? `${error.status} - ${error.statusText}` : 'Server error';
		console.error(errMsg); // log to console instead
		return Observable.throw(errMsg);
	}
}
`
catch handles non-error response

**Comment by khanyuriy** [comment]
oh... it seem that something changed in express since last used version. With end() it works.

**Comment by khanyuriy** [comment]
I finally reproduced the exception on clean starter project

app.ts 

import { Component } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw';

@Component({
  selector: 'app',
  template: `
  <p>Hello Angular Universal App</p>
  <router-outlet></router-outlet>
  `
})
export class App {

}

@Component({
  selector: 'home',
  template: 'Home component'
})
export class Home {
  constructor(private http: Http) {
    http.get('/test')
      .catch(this.handleError)
      .subscribe(response => {
      console.log(response.json())
    })
  }
  private handleError(error: any) {
		// In a real world app, we might use a remote logging infrastructure
		// We'd also dig deeper into the error to get a better message
		let errMsg = (error.message) ? error.message :
			error.status ? `${error.status} - ${error.statusText}` : 'Server error';
		console.error(errMsg); // log to console instead
		return Observable.throw(errMsg);
	}
}

my route in server.ts

app.get('/test', function(req, res) {
  res.send({title:'hello'});
});

**Comment by gdi2290** [comment]
res.**json(** _{ title:'hello' }_ **)**

you're not sending json (json is a string) so the server is erroring out.

**Comment by khanyuriy** [comment]
Hi, Patrick!
res.json() and res.json().end() not helped

**Comment by gdi2290** [comment]
ok here's the fix
https://github.com/angular/universal-starter/commit/32a73f1abdb8b304d7bea55f2e69b7d89fea36a5
the problem was that the server was responding with `connect ECONNREFUSED 127.0.0.1:80` since req.hostname was `127.0.0.1`
