### ISSUE TITLE
new package causes reload when navigating

### ISSUE THREAD

**Issue by medozs** [angular/universal-starter#169]
old package.json(from 2 days ago node-modules), when supplied with missing packages, work.  Probably a bug with the new version of the packages.

**Comment by MarkPieszak** [comment]
What do you mean by old package?

**Comment by medozs** [comment]
@MarkPieszak  package.json node_modules

**Comment by MarkPieszak** [comment]
Did you try removing the `node_modules`completely and then reinstall them?

**Comment by medozs** [comment]
@MarkPieszak I had the old modules from 2 days ago and just replace the folder and it worked.

**Comment by MarkPieszak** [comment]
Great, glad to hear it 👍

**Comment by medozs** [comment]
@MarkPieszak  actually, when I reinstalled the new package, it works fine now. It seems that the package I downloaded before was not the right one for the app, and the right one came few hours after.

**Comment by medozs** [comment]
Ignore this post!!
When I reinstalled the new package.json from here, it works fine now. This package wasn't there when I download the app, it was updated few hours after.
