### ISSUE TITLE
Grab routes from external API

### ISSUE THREAD

**Issue by Dralac** [angular/universal-starter#171]
This is more question than the issue, and it's about dynamic routes from external API. 

What I try to achieve is to grab the routes from external API, prepare them and use them with universal, which I managed. Anyway, if I request directly any other route than the home ( / ) route I get error that route doesn't exist because API call didn't finished and routes are not ready yet. 

So what I'm wondering is there some kind of condition ( or whatever ) to prevent loading the angular app before external API call is finished?

**Comment by MarkPieszak** [comment]
It should be waiting on any http calls etc before loading everything, or are you talking about something completely outside of angular? You might just need to run your code, then load your App if that's the case?

**Comment by Dralac** [comment]
Thanks @MarkPieszak, what I needed is just wait for 1 call that will grab async routes from API, so I guess your answer should do the job. I'll just try to run that call before bootstraping ng2.

**Comment by Dralac** [comment]
@MarkPieszak 

Please correct me if I'm wrong, but server.ts runs only when "npm start" runs or only one time when app is built?  If so, this might a be an issue.

Since I'm grabbing routes from external API ( and sharing with client side via cache) , I found out that after refreshing the page in browser, server.ts doesn't run at all, and changes I got from API aren't passed to client side ( I can get proper data only if I stop the server and run "npm start" again).
If I try to grab my routes from node.module.ts, it works on page refresh, but I'm unable to update server side routes from API response I got.

Is there a workaround for this, or I'm missing something?
