### ISSUE TITLE
https calls not working

### ISSUE THREAD

**Issue by arielhenryson** [angular/universal-starter#172]
In the new version  when I try to make a HTTPS request to third-party APIs server, I'm getting this error

{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
    at TLSSocket.g (events.js:291:16)
    at ZoneDelegate.invokeTask (/xxx/xxx/xxx/xxx/node_modules/zone.js/dist/zone-node.js:225:37)
    at Zone.runTask (/xxx/xxx/xxx/xxx/node_modules/zone.js/dist/zone-node.js:125:47)
    at TLSSocket.ZoneTask.invoke (/xxx/xxx/xxx/xxx/node_modules/zone.js/dist/zone-node.js:293:33)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }

the code is something like this
```
const request = require('request');
const url = "https://xxx.xxx.xxx";
request(url, function (err, response, body) {
   console.log(err);
   console.log(response);
   console.log(body);
});
```

**Comment by MarkPieszak** [comment]
Do you have a fresh repo, or have you completely removed your `node_modules` folder and then reinstalled everything?

Also can you try updating your Universal depdencies to the latest 2.0.10 version, wondering if those could be the problem as well.

    "angular2-platform-node": "~2.0.10",
    "angular2-universal": "~2.0.10",
    "angular2-universal-polyfills": "~2.0.10",
    "angular2-express-engine": "~2.0.10",

**Comment by arielhenryson** [comment]
Just to make sure I deleted my node_modules folder and updated  the universal  stuff as you suggest but the problem is still there.

**Comment by gdi2290** [comment]
can you try with zone.js 0.6.21?

**Comment by arielhenryson** [comment]
I rolled back Zone from 0.6.25 to 0.6.21 and now it's working again
i did a file compare between the versions and i see that in version 0.6.25 there is a new code in the zone-node.js related to HTTP so maybe that's is the problem

But I have a question.I don't understand why in the server-side Zone  takes control over global stuff. I understand why in the browser Zone it needs to be aware of a lot of stuff that is happening and that's why it's overwrite stuff that are related to the "window" object but I don't understand why in the sever side it's not working with some sort of namespace. Would it be better ?!  because  in the server side there is a lot of stuff that are not related to Angular like simple APIs endpoint. so I think that if in the server-side Zone will touch stuff that he is not supposed to touch and i would want to work with Angular universal, I would have to change my app to work in a micro services architecture where stuff that are not related to Angular will work on a different isolated process

**Comment by gdi2290** [comment]
cc @alxhub

**Comment by jeffwhelpley** [comment]
@gdi2290 is this related to #164?

**Comment by gdi2290** [comment]
if you want to isolate zone.js then you would want angular to run in an isolated process outside of your server app as you suggested. We use zone.js to track async calls that are being made before converting the app into a string to send down to the client. We also use it to proxy globals such as `document` (and more in the future) for when the developer doesn't have control over the implementation (3rd party modules) and doesn't want to split the code at the module level.  In the future, we can provide different workarounds for these globals and allow Zone.js to be optional if the developer's app also works without zone.js

**Comment by AlexYankee** [comment]
Same here - request to https results in "Socket hung up" with 0.6.25, something was definitely broken. Downgrading to 0.6.21 resolved issue, thanks  @arielhenryson

**Comment by gdi2290** [comment]
can you report these issues in the [angular/zone.js](https://github.com/angular/zone.js) repo

**Comment by gdi2290** [comment]
update to zone 0.6.26 should fix the issue

**Comment by arielhenryson** [comment]
I updated the version and the problem still exists

**Comment by gdi2290** [comment]
@arielhenryson  can you create an issue in zone.js and provide a repo that reproduces the problem

**Comment by John0x** [comment]
@gdi2290 the newest zone.js probably fixes this issue (stated in the zone.js issue).
