### ISSUE TITLE
npm run server fails

### ISSUE THREAD

**Issue by esakkikrishnan** [angular/universal-starter#173]
npm run server fails and shows me the following error:

npm run server

> universal-starter@2.0.0 server D:\EXP\JS\ANGULAR2\universal-starter
> nodemon dist/server/index.js

[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: D:\EXP\JS\ANGULAR2\universal-starter\dist/**/* src/index.html
[nodemon] starting `node dist/server/index.js`
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\esakkik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\
npm-cli.js" "run" "server"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! universal-starter@2.0.0 server: `nodemon dist/server/index.js`
npm ERR! Exit status 1

[npm-debug.txt](https://github.com/angular/universal-starter/files/480005/npm-debug.txt)

**Comment by MarkPieszak** [comment]
Do you have a fresh repo, or have you completely removed your `node_modules` folder and then reinstalled everything?

Also can you try updating your Universal depdencies to the latest 2.0.10 version, wondering if those could be the problem as well.

    "angular2-platform-node": "~2.0.10",
    "angular2-universal": "~2.0.10",
    "angular2-universal-polyfills": "~2.0.10",
    "angular2-express-engine": "~2.0.10",

**Comment by esakkikrishnan** [comment]
The issue is with my nodemon. Thanks anyway @MarkPieszak

**Comment by MarkPieszak** [comment]
Oh great, glad you figured it out!
