### ISSUE TITLE
npm start failed for something about webpack

### ISSUE THREAD

**Issue by RephoneYin** [angular/universal-starter#176]
I working on master branch. I really make me confused when I tried to start the server. Here is my output in termimal:

`
     E:\research\angular2\universal-starter>npm start
    
    > universal-starter@2.0.0 prestart E:\research\angular2\universal-starter
    > npm run build
    
    
    > universal-starter@2.0.0 prebuild E:\research\angular2\universal-starter
    > rimraf dist
    
    
    > universal-starter@2.0.0 build E:\research\angular2\universal-starter
    > webpack
    
    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
     - configuration[0].resolve has an unknown property 'root'. These properties are valid:
       object { modules?, descriptionFiles?, plugins?, mainFields?, aliasFields?, mainFiles?, extensions?, enforceExtension?, moduleExtensions?, enforceModuleExtension?, alias?, symlinks?, unsafeCache?, cachePredicate?, fileSystem?, resolver? }
     - configuration[0].resolve.extensions[0] should not be empty.
     - configuration[1].module has an unknown property 'preLoaders'. These properties are valid:
       object { rules?, loaders?, noParse?, unknownContextRequest?, unknownContextRegExp?, unknownContextRecursive?, unknownContextCritical?, exprContextRequest?, exprContextRegExp?, exprContextRecursive?, exprContextCritical?, wrappedContextRegExp?, wrappedContextRecursive?, wrappedContextCritical? }
       Options affecting the normal modules (`NormalModuleFactory`).
     - configuration[1].resolve has an unknown property 'root'. These properties are valid:
       object { modules?, descriptionFiles?, plugins?, mainFields?, aliasFields?, mainFiles?, extensions?, enforceExtension?, moduleExtensions?, enforceModuleExtension?, alias?, symlinks?, unsafeCache?, cachePredicate?, fileSystem?, resolver? }
     - configuration[1].resolve.extensions[0] should not be empty.
    
    npm ERR! Windows_NT 10.0.10586
    npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
    npm ERR! node v6.2.0
    npm ERR! npm  v3.8.9
    npm ERR! code ELIFECYCLE
    npm ERR! universal-starter@2.0.0 build: `webpack`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the universal-starter@2.0.0 build script 'webpack'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the universal-starter package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     webpack
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs universal-starter
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls universal-starter
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     E:\research\angular2\universal-starter\npm-debug.log
    
    npm ERR! Windows_NT 10.0.10586
    npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
    npm ERR! node v6.2.0
    npm ERR! npm  v3.8.9
    npm ERR! code ELIFECYCLE
    npm ERR! universal-starter@2.0.0 prestart: `npm run build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the universal-starter@2.0.0 prestart script 'npm run build'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the universal-starter package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run build
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs universal-starter
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls universal-starter
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     E:\research\angular2\universal-starter\npm-debug.log
    
    E:\research\angular2\universal-starter>
`

**Comment by matiishyn** [comment]
have the same issue

**Comment by matiishyn** [comment]
here's a temp fix:
https://github.com/angular/angular-cli/issues/2234#issuecomment-248174857
Webpack team is working on it

**Comment by Hongbo-Miao** [comment]
Got same issue, and
```bash
npm uninstall webpack --save-dev
npm install webpack@2.1.0-beta.22 --save-dev
```
does not work for me

**Comment by Hongbo-Miao** [comment]
Okay, so I got same issue but because of different thing.

Please check my answer here: http://stackoverflow.com/questions/39783856/failed-at-the-myproject1-0-0-build-script-webpack

**Comment by gdi2290** [comment]
thanks, should be fixed via https://github.com/angular/universal-starter/commit/2f1a70db9d5879d57ff6363956635e1052d1896c now
