### ISSUE TITLE
Unable to load templateUrl even with absolute path

### ISSUE THREAD

**Issue by akshaybabajob** [angular/universal-starter#177]
I am trying to load external html template but I am unable to do so.
Here is the code : 
  selector : 'home',
  templateUrl : 'src/components/home/home.component.html',
  //encapsulation: ViewEncapsulation.None,
  styles: [require('./home.scss').toString()]

Also the folder structure:
universal-starter/src/components/home/home.component.html

Any ideas? Tried all the possible path, even tried 'require'

**Comment by matt4446** [comment]
I have not got around to trying it, but I do remember reading about it:: 

http://stackoverflow.com/questions/37178192/angular2-what-is-the-meanings-of-module-id-in-component

**Comment by flauc** [comment]
Hi @akshaybabajob, this is how i do it and it work just fine: 

```ts
@Component({
    selector: 'something',
    template: require('../templates/something.html')
})
```

The `something.html` file is located in the templates folder of the parent directory. 

Btw there is nothing that you need to configure in your webconfig for this to work

**Comment by MarkPieszak** [comment]
@akshaybabajob  Yes, you want to use `styles` and `template` not URL.
This way Webpack will get the file for you, and return it as a String.

**Comment by jeffwhelpley** [comment]
Closing this for now, but please re-open if Mark's suggestion does not solve your problem.

**Comment by akshaybabajob** [comment]
Thanks everyone. It worked!
