### ISSUE TITLE
VS Code Debug

### ISSUE THREAD

**Issue by Junik** [angular/universal-starter#178]
Guys could you create help or best practice for creating VS Code environment  with debug configuration.
-Breakpoints in server side render workflow
-Breakpoints in client side workflow

**Comment by Junik** [comment]
Оk I leave it here.
 server side:
.vscode->launch.json
```
"configurations": [
             ...
            "sourceMaps": true, 
            "outDir": "${workspaceRoot}/dist/server",
            "smartStep":true
             ...
```

src->webpack.config.ts

```
var commonConfig = {
   devtool: 'source-map', //or any type of source maps
.....
 var defaultConfig = {
     output: {
     ...
                 devtoolModuleFilenameTemplate        : '[absolute-resource-path]',
                 devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
    ...
```
VS Code breakpoints work

client side:
  after this in chrome Developer tools source maps is available so breakpoints work as usually

**Comment by MarkPieszak** [comment]
@Junik The Starter actually comes with the .vscode files needed for debugging, are those default ones not working for you?

**Comment by MarkPieszak** [comment]
Actually you're right, doesn't seem to be working for client-side. A while back I was able to hit breakpoints for the client-side also...

**Comment by aecz** [comment]
Thanks @Junik. Works perfect now.
Please update VS Code launch.json/webpack.config.

**Comment by MarkPieszak** [comment]
Can you put in a quick PR with the fix?
