### ISSUE TITLE
Update to angular beta

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#18]
Would be great to get the repository working agains angular2 beta. I still run into some issues with typescript namely the one with "Typescript Module build failed: TypeError: compiler.parseConfigFile is not a function"

I think there is some issues with some breaking changes on ts-node. I am not sure.

**Comment by tamascsaba** [comment]
:+1:

**Comment by joaogarin** [comment]
forcing the typescript version to 1.6.2 fixes the issues I was talking about. So only thing remaining is really angular2 beta awesomeness=)

**Comment by sandyjoshi** [comment]
Close once PR #21 gets merged.

**Comment by gdi2290** [comment]
the repo has been updated to beta.0 but I still need to update it to beta.1
