### ISSUE TITLE
error TS2687: All declarations of 'prototype' must have identical modifiers.

### ISSUE THREAD

**Issue by bkinsey808** [angular/universal-starter#180]
I have the latest angular universal-starter and the latest typescript.

When I run `npm start` I get some errors:

```
ERROR in /home/bkinsey/opt/angular/universal-starter/node_modules/typescript/lib/lib.es2015.promise.d.ts
    (69,14): error TS2687: All declarations of 'prototype' must have identical modifiers.
    
...

```

etc.

**Comment by bkinsey808** [comment]
Installing the latest version of node fixed this for me. v6.6.0

**Comment by MarkPieszak** [comment]
Did you wipe your node_modules and reinstall?
Also, your tsconfig doesn't have lib : [es6] or anything does it?
Also, are you using npm 3.* or higher?

**Comment by jeffwhelpley** [comment]
Just checked and this seems alright to me, but please re-open if you are still having this issue.

**Comment by bkinsey808** [comment]
I did wipe node_modules. Originally I had `"lib": ["es6", "dom"],` in my tsconfig.json file. I tried some different values for this, and they seem to change the errors around but nothing has worked.

$ npm -v
3.10.3

With this: `"lib": ["dom"],`, I got

```
/home/bkinsey/opt/angular/universal-starter/node_modules/ts-node/src/index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
Cannot find global type 'Boolean'. (2318)
Cannot find global type 'Function'. (2318)
Cannot find global type 'IArguments'. (2318)
Cannot find global type 'Number'. (2318)
Cannot find global type 'Object'. (2318)
webpack.config.ts (129,10): Cannot find name 'Array'. (2304)
webpack.config.ts (130,44): Property 'concat' does not exist on type 'string[]'. (2339)
    at getOutput (/home/bkinsey/opt/angular/universal-starter/node_modules/ts-node/src/index.ts:253:17)
    at /home/bkinsey/opt/angular/universal-starter/node_modules/ts-node/src/index.ts:263:16
    at Object.compile (/home/bkinsey/opt/angular/universal-starter/node_modules/ts-node/src/index.ts:398:17)
    at Module.m._compile (/home/bkinsey/opt/angular/universal-starter/node_modules/ts-node/src/index.ts:299:46)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/bkinsey/opt/angular/universal-starter/node_modules/ts-node/src/index.ts:302:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

With `"lib": ["es5", "dom"],`, I get:
```
    ERROR in /home/bkinsey/opt/angular/universal-starter/node_modules/@types/node/index.d.ts
    (570,18): error TS2300: Duplicate identifier 'EventEmitter'.

etc...
```

I really wish I had some idea what was going on.

**Comment by jeffwhelpley** [comment]
@MarkPieszak can you take a look whenever you get a chance and then slack me so we can talk about it?

**Comment by MarkPieszak** [comment]
Sure I can take a look tomorrow @jeffwhelpley I wasn't able to repro it last I tried either.

**Comment by Ignigena** [comment]
I was getting this exact same issue after removing `node_modules` and re-installing with NPM 3 and Node 6.  I was able to solve this by removing the `typings` folder as well.

**Comment by JamesJoyceGit** [comment]
Remove %localappdata%\Microsoft\Typescript, then run: npm install -g typescript@2.1
