### ISSUE TITLE
async data does not render on server

### ISSUE THREAD

**Issue by khanyuriy** [angular/universal-starter#181]
to reproduce, is used the latest universal-starter clone
i added  text property and ngOnInit to App class 
...
text: string;
ngOnInit() {
    this.http.get('assets/text.txt')
      .subscribe(response => {
        console.log('text');
        this.text = response.text();
      })
  }
...
then i added binding to template 
`
 <p>Hello Angular Universal App</p>
  <p>{{text}}</p>
  <router-outlet></router-outlet>
`
and finally added text file "text.txt" to assets folder.
when i run the app, i can see that content of text.txt is displayed after app is loaded to browser.
how can i fix this ?

**Comment by MRokas** [comment]
Correct me if I'm wrong, but shouldn't server-side code use fs to retrieve content?

**Comment by khanyuriy** [comment]
You're right. This example just for reproduce the bug. I actually do async requests to mongodb, and getting no data rendered on a server. So it does not solve the SEO of SPA problem.

**Comment by aiboy** [comment]
Any attention to this issue? Also can't figure out what we need to do to force Angular-Universal to wait for http.get before rendering the page.

Find some information but it's all outdated.

**Comment by MarkPieszak** [comment]
Strange, it should automatically be waiting for those things since they are in the Zone, let me take a look. @aiboy

**Comment by aiboy** [comment]
@MarkPieszak thanks a lot

Heres a repo - https://github.com/ServerSideRender/angular-universal

There is a possibility that we misconfigured something, but what i get so far that by default angular-universal doesn't wait for Http to finish.

**Comment by MarkPieszak** [comment]
> For both these issues I disabled JavaScript to just see the server-rendered version only.

@khanyuriy I was unable to reproduce your issue, I tried a text file (in assets/text,txt) and it was able to grab the text from it without any issues. Is there something else you have going on that might be stopping these things from working? 

@aiboy I was also unable to reproduce this one, it seemed to work fine using the baseline Starter. It worked with & without the `async` pipe, I added the same api/article json api returning as well.

It looks like you're using the latest 2.0.11 version as well, not sure what could be causing this issue...

Server-side render:
![image](https://cloud.githubusercontent.com/assets/2574412/18880585/59da2994-84a6-11e6-8898-b0908876c500.png)

Client-side render: (console logged it there as well)
![image](https://cloud.githubusercontent.com/assets/2574412/18880895/7a744e36-84a7-11e6-90f5-bbcee8f78113.png)

**Comment by aiboy** [comment]
rmrf-ed node_modules and it didn't helped at all. What i see is "null" rendered at server side ( look at Http response from server for index.html )

![2016-09-27_18-54-17](https://cloud.githubusercontent.com/assets/1760346/18881429/4bc8a074-84ec-11e6-8b4b-4f648b559710.png)

PS: I see the article being rendered, but it's rendered later on, by client side request :/

**Comment by khanyuriy** [comment]
@MarkPieszak  hi! Thank you for your attention!
You can clone this repo https://github.com/khanyuriy/universal-starter.
npm i && npm run server
I switched off the javascript in chrome, and see that page come from server without async data.

**Comment by LendsMan** [comment]
Both our repos work the same: server doesn't "wait for all async to resolve before returning response".

**Comment by MarkPieszak** [comment]
@LendsMan @khanyuriy @aiboy 
Wow this is very strange, I'm now able to repro it on different repo & the one you provided Khan. 
But my original fork Starter repo, it works completely fine...

Investigating what the heck is going on here, give me some time, not sure if this is something to do with graceful-fs updating recently, or something else... nothing in Core / Universal has changed recently

**Comment by MarkPieszak** [comment]
@LendsMan @khanyuriy @aiboy @MRokas  
Took hours but I finally figured it out... But it was Zones that was incorrectly capturing these events.

Update your Zone.js from 0.6.21 to **0.6.23** and it'll fix the issue :dancers: :sparkles: 

https://github.com/angular/universal-starter/pull/183

**Comment by intergleam** [comment]
I have     "zone.js": "^0.8.14" and it doesn't work

**Comment by intergleam** [comment]
I have 
```
  ngOnInit() {
    this.http.get('assets/text.txt',{
      responseType: 'text' 
   })
      .subscribe(response => {
        console.log(response);
        this.message = response;
      })
  }

```
then I run `npm run build:ssr && npm run serve:ssr` as per readme, open http://localhost:4000 and I see an XHR to get text.txt
![image](https://user-images.githubusercontent.com/2155554/34981681-48a56b54-fab9-11e7-9419-4055b0cb9a73.png)

**Comment by intergleam** [comment]
weirdly if I use
```
  async ngOnInit() {
    this.message = 'temp message';
    var data = await this.http.get('https://api.github.com/users/github').toPromise();
    this.message = data['bio'];
  }
```
i still get XHR request but view-source:http://localhost:4000/ shows me 
```
...
<router-outlet></router-outlet><home><h3>How people build software.</h3>
...
```

**Comment by evgenyetoro** [comment]
I have the exact same issue? Is there a solution?

**Comment by jedrichards** [comment]
@intergleam The presence of a XHR on the client doesn't necessarily mean the server didn't also make the request while it was rendering.

**Comment by GabrielCoriiu** [comment]
I have the same issue. The server doesn't wait for my **async** request to resolve, but it waits for 5 seconds if I set a timeout in the ngOnInit() function. I find this weird...

```
ngOnInit(): void {
	contentfulClient.getEntries(query).then(entries => {
		[...]
	});

	//// if I uncomment the timeout, the server will wait for 5 seconds, 
	//// which gives plenty of time to the previous promise to resolve
	// setTimeout(() => {}, 5000);
}
```

**Comment by krlf** [comment]
+1
I have the same issue. Does not matter if I use TransferState feature or not (as it was mentioned https://github.com/angular/universal/issues/1049#issuecomment-423423574) the same result: if code is run in Node.js env then data is not fetched.

**Comment by intergleam** [comment]
check out this repo https://github.com/intergleam/universal-starter/tree/81e1c16ae5605da2b255638dbf48acbf1dd11de8
I did it with minimal changes to the original. You have to use HttpClient, not Http

**Comment by krlf** [comment]
As for me I've found out that SSR async data retrieval is not working when I use HTTP interceptor.

**Comment by ildar-icoosoft** [comment]
temporary fix:
```
const intervalId = setInterval(() => {}, 100);
this.http.get().subscribe(() => clearInterval(intervalId) )
```

**Comment by HighSoftWare96** [comment]
Any update on this issue? I've tried also by using the Routes Resolvers but it does not work anyway (see related: https://github.com/angular/universal/issues/736)
