### ISSUE TITLE
Unexpected value 'UniversalModule' error

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#182]
I made this simple change to the repo:

`server.ts`
```ts
Mongo.init().then(client => {
    let server = app.listen(process.env.PORT || 3000, () => {
        console.log(`Listening on: http://localhost:${server.address().port}`);
    });
});
```

Then i get this error: 

```
C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\compiler\bundles\compiler.umd.js:14126
                              throw new Error("Unexpected " + _this._getTypeDescriptor(importedType) + " '" + stringify(importedType) + "' imported by the module '" + stringify(moduleType) + "'");
                              ^

Error: Unexpected value 'UniversalModule' imported by the module 'MainModule'
```

Even if i just run Mongo.init() separate from app.listen just like this: 

```ts
    let server = app.listen(process.env.PORT || 3000, () => {
        console.log(`Listening on: http://localhost:${server.address().port}`);
    });

    Mongo.init().then(client => {
        console.log(client);
    });
``` 

I get the same error. 

This error has nothing to do with `Mongo.init()` it's just a simple promise that resolves when a connection has been established and I've tested it extensively. Also if i change `Mongo.init()` with any other promise i get the same error. 

Any help is most appreciated 👍

**Comment by flauc** [comment]
I've managed to resolve the error. The problem was that i was importing 'reflective-metadata' in a connected file in the project. I'm not sure why, but removing the import fixed the problem and i still had the needed functionality.

**Comment by MarkPieszak** [comment]
Good to hear! Sorry I forgot to respond the other day, and a lot of the team was away at AngularConnect all week.
