### ISSUE TITLE
Material 2 patch needs to be updated for alpha-9

### ISSUE THREAD

**Issue by qdouble** [angular/universal-starter#185]
Angular material is no longer using @angular2-material, it is now using @angular/material, so the patches here need to be updated: https://github.com/angular/universal-starter/blob/master/webpack.config.ts#L55

**Comment by qdouble** [comment]
Also individual packages no longer need to be used, a person can just use MaterialModule, so the only file that needs to be made to work is @angular/material/material.umd.js

**Comment by gdi2290** [comment]
move it from `preLoaders` to `loaders`

**Comment by qdouble** [comment]
@gdi2290, that solution isn't sufficient as I said, the packaging has change to @angular/material and the delivery is a different....

If I put the loader to `{ test: /angular\/material/, loader: 'imports-loader?window=>global' }`, or even `{ test: /angular\/material/, loader: 'imports-loader?document=>global' },` and put this `'@angular/material/',` in the includeClientPackages part, I will still get this error:

```bash
EXCEPTION: document is not defined                                                                                          
ORIGINAL STACKTRACE:                                                                                                        
ReferenceError: document is not defined                                                                                     
    at new RippleRenderer (/Users/qdouble/Sites/EXAMPLE_APPS/angular2webpack2-starter/node_modules/@angular/material/materia
l.umd.js:193:31)                                                                                                            
    at new MdRipple (/Users/qdouble/Sites/EXAMPLE_APPS/angular2webpack2-starter/node_modules/@angular/material/material.umd.
js:327:32)                                                                                                                  
    at AppView._View_MdButton1.createInternal (MdButton.ngfactory.js:63:24)                                                 
    at AppView.create (/Users/qdouble/Sites/EXAMPLE_APPS/angular2webpack2-starter/node_modules/@angular/core/bundles/core.um
d.js:9399:25)                                                                                                               
    at TemplateRef_.createEmbeddedView (/Users/qdouble/Sites/EXAMPLE_APPS/angular2webpack2-starter/node_modules/@angular/cor
e/bundles/core.umd.js:7487:18)  
.....
```
any ideas?

**Comment by gdi2290** [comment]
ya the `RippleRenderer` needs to use the `Renderer` and use the correct methods such as `Renderer#createElement` so the fix needs to happen with the material repo. I have solution for dealing with browser globals that I can update but it also needs to include `window.getComputedStyle`

**Comment by jvbianchi** [comment]
this issue might be related to https://github.com/angular/material2/issues/308

**Comment by gdi2290** [comment]
Material isn't supported for webworkers or universal right now everyone must follow this issue
https://github.com/angular/material2/issues/308
