### ISSUE TITLE
support webpack config for minification

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/universal-starter#186]
Please add webpack config options for minification, thanks!

Right now the browser loads a 3.4MB index.js file:

![image](https://cloud.githubusercontent.com/assets/3375461/19018433/687a7004-882e-11e6-9fea-8ed15d2c3289.png)

**Comment by mekya** [comment]
you can try to run 

`npm run build:prod`

It reduces index.js size to about 1MB

Welcome for better recommendations...

**Comment by TomerCohavi** [comment]
@mekya Any idea on how to reduce even more the bundle size? 1MB is super heavy especially on mobile.

**Comment by kuldeepkeshwar** [comment]
@TomerCohavi  use code splitting (lazy-routes) and AOT

**Comment by mekya** [comment]
@TomerCohavi 
one more addition: gzip, take a look at this blog post
http://blog.mgechev.com/2016/06/26/tree-shaking-angular2-production-build-rollup-javascript/

**Comment by TomerCohavi** [comment]
@kuldeepkeshwar Thanks!
@mekya I've managed to reduce it to ~350kb with gzip. Thanks!

**Comment by Hongbo-Miao** [comment]
I added the Webpack way using gzip here https://github.com/angular/universal-starter/pull/199

For lazy load, track https://github.com/angular/universal-starter/issues/175
For AOT, track https://github.com/angular/universal-starter/issues/197

**Comment by gdi2290** [comment]
there is a prod build now
