### ISSUE TITLE
Can't use templateURL for components

### ISSUE THREAD

**Issue by Exgaves** [angular/universal-starter#190]
"No ResourceLoader implementation has been provided. Can't read the url "/views/app/index.html""
This only happens when a component is loading the html from a url. If the HTML is in-lined its fine.
Also tried using "http://localhost:3000/views/app/index.html" with no success.

This error is thrown when the server attempts to render the page for a client. Is there something I need to load for the serverside to be able to resolve these url's?

**Comment by Hongbo-Miao** [comment]
Hi @Exgaves, take HomeComponent for example,

You can import like this
```
templateUrl: './home.component.html'
```

**Comment by MarkPieszak** [comment]
Are you using `angular2-template-loader` in your webpack config for all TS files? (Also making sure it's in your package.json)

    { test: /\.ts$/, loaders: ['ts-loader', 'angular2-template-loader'] },

If you're using the default starter here, it should work out of the box.

**Comment by percinor** [comment]
Did  in universal only can use  style.css file in component  styleUrls: ['./bootstrap.min.css'] ??   it can'nt  use in index.html  head <link rel="stylesheet" href="bootstrap.min.css"> like this.  so i always cannt get  http://localhost:3000/bootstrap.min.css  in console.

**Comment by MarkPieszak** [comment]
Try using `import` in your boot-client file @percinor to get it in there.
Also if you're trying to use Bootstrap, I suggest using ng2-bootstrap, not regular bootstrap.
