### ISSUE TITLE
How to run in production

### ISSUE THREAD

**Issue by davidmontgom** [angular/universal-starter#193]
# Hi,

How do use your app in production?  I find very unstable if exception and hpoing I am doing something wrong 

1) when I am ready to push I run the below:
npm run build

2) on my production server I then run:
npm start

3) I serve via nginx:

 server {

```
 listen 80 default_server;
 listen [::]:80 default_server;
 root /var/test/dist/client;

 # Add index.php to the list if you are using PHP
 index index.html index.htm index.php index.nginx-debian.html;

location /assets {
alias /var/test/src/assets;
autoindex off;
```

}

```
 location / {
     proxy_set_header   X-Real-IP $remote_addr;
     proxy_pass         http://127.0.0.1:3000;
     proxy_set_header   Host $host;
 }
```

location /browser-sync {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_pass         http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
    }
 }

If error I get this
[nodemon] app crashed - waiting for file changes before starting...

And the whole site goes down.  Can you provide more color on how to run universal in production?

**Comment by owencooney** [comment]
Hi David, just ran into the same issue myself... This might be helpful: 
https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-serve-with-PM2
