### ISSUE TITLE
Angular Universal with Augury

### ISSUE THREAD

**Issue by LendsMan** [angular/universal-starter#194]
I have an issue with Angular Universal starter pack and Augury. 
When I run `npm start` in universal-starter and try to run Augury I see a message:

> This application is running in production mode and therefore cannot be debugged using Augury. Please rebuild your application in debug mode or remove the call to enableProdMode().

I tried to comment `enableProdMode()` in both server.ts and client.ts and all I got was:
> Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

on the server and the same message

> This application is running in production mode and therefore cannot be debugged using Augury. Please rebuild your application in debug mode or remove the call to enableProdMode().

in the browser.
Setting node environment to _development_ didn't help.

Is it possible to run Angular Universal with Augury?

**Comment by Hongbo-Miao** [comment]
It works for me. Augury version 1.2.1

![image](https://cloud.githubusercontent.com/assets/3375461/19536974/37455480-961c-11e6-86ef-264627dcd9fe.png)

**Comment by gdi2290** [comment]
thanks @Hongbo-Miao, closing this
