### ISSUE TITLE
AoT with universal-starter

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#195]
This isn't really an issue, just a question. I'm trying to implement AoT with the starter but with no luck, so I'm wondering if an implementation is in the works at the moment? Or is AoT maybe incompatible with the current version of angular universal?

Thank you for the great starter project 👍

**Comment by MarkPieszak** [comment]
You can track https://github.com/angular/universal/pull/578 
AoT isn't working just yet with Universal.

**Comment by flauc** [comment]
Thank you for the quick response. Just one more question, do you plan on integrating it in to the starter?

**Comment by gdi2290** [comment]
Thanks for creating an issue, as Mark said please track that issue and yes this starter will have AoT. I'm going to close this so you can track that issue in the universal repo
