### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by wallaceiam** [angular/universal-starter#196]
Has anyone been able to get server side rendering to work with Azure?

**Comment by MarkPieszak** [comment]
Are you talking about asp.NET Core integration with Universal?

**Comment by wallaceiam** [comment]
I'm wondering more if I'm going to be hosting my site on Azure using App Services than if anyone has experience getting server side rendering to work or if it is better to switch to something like JavascriptServices (https://github.com/aspnet/JavaScriptServices).

**Comment by MarkPieszak** [comment]
Yes if you're using Azure I'm assuming you want/need to use .NET. I've helped make sure Steves Angular2 repo is working with the latest Universal changes. https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa

There should information there on deploying to Azure as well!

**Comment by wallaceiam** [comment]
Cheers - going to switch over my project

**Comment by iambipinpaul** [comment]
Has anyone been able to get server side rendering to work with Azure(Nodejs)?
