### ISSUE TITLE
update build to include AoT build

### ISSUE THREAD

**Issue by gdi2290** [angular/universal-starter#197]

**Comment by diestrin** [comment]
Is there anyone working on this? I'll probably going to start adding it to a project based on this repo today. Wondering if there's anything done already, or in the other hand, if I may contribute with my findings.

**Comment by gdi2290** [comment]
this is done

**Comment by ThorstenHans** [comment]
Maybe done, but not working at all,  if you try to execute `npm run build:prod:ngc` after a fresh clone it just tanks.  ^^

**Comment by gdi2290** [comment]
what's the error?
