### ISSUE TITLE
More detailed polyfills import comment

### ISSUE THREAD

**Issue by shedar** [angular/universal-starter#198]
[First line of server.ts](https://github.com/angular/universal-starter/blob/master/src/server.ts#L1) states that polyfills should be the first thing to import.

I would suggest something like 

    the polyfills must be one of first things imported in node.js. 
    The only modules that can be imported higher - node modules with es6-promise dependency 
    (you only need to do it if you have zone.js exception)

Explanation:

In my project, I decided to use [express-http-proxy](https://github.com/villadora/express-http-proxy) to proxy API requests to backend. But it has a newer version of `es6-promise` in dependencies then allowed by `angular2-universal-polyfills`. So npm installs two different versions of s6-promise module.
If I import polyfills as the first import, then I have the following flow:

1. polyfills load es6-promise and then zonejs,
2. zonejs overrides Promise implementation
3. express-http-proxy loads a separate es6-promise module (not loaded by polyfills)
4. es6-promise tries to detect native Promise support. ZoneJs implementation doesn't pass checks
5. es6-promise overrides global Promise with own implementation
6. zoneJS throws an error that its implementation is overridden 
    
    Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.))

It can be fixed by importing `express-http-proxy` before `angular2-universal-polyfills` to get all `es6-promise` modules initialized before `zone.js`.

**Comment by gdi2290** [comment]
can you make a PR with better comments and/or update the readme?

**Comment by shedar** [comment]
Take a look if it's good enough.

**Comment by gdi2290** [comment]
thanks!
