### ISSUE TITLE
@Angular-Class in description should be @AngularClass

### ISSUE THREAD

**Issue by wesleycho** [angular/universal-starter#20]
@Angular-Class links to the wrong organization in the description - it should be @AngularClass

**Comment by bjwyse** [comment]
@gdi2290 This issue is referring to the Github Project description and must be changed by a project admin.

![screen shot 2016-02-04 at 22 13 09](https://cloud.githubusercontent.com/assets/511510/12831490/89088f90-cb8c-11e5-84f3-c83435dfb270.png)

**Comment by jeffbcross** [comment]
Done, thanks @wesleycho and @bjwyse!
