### ISSUE TITLE
Can you add routing example?

### ISSUE THREAD

**Issue by kruny1001** [angular/universal-starter#205]
Universal starter doesn't include routing angular2 app. 
Can you explain how to add route?

**Comment by Hongbo-Miao** [comment]
It is same like a normal Angular 2 app, the only difference is that you need import your routes in `@NgModule` of both **app.broswer.module.ts** and **app.node.module.ts**.

**Comment by gdi2290** [comment]
@Hongbo-Miao is correct. Can someone create a PR that will import one routes file for both modules

**Comment by Hongbo-Miao** [comment]
well, I can help add
