### ISSUE TITLE
Considering becoming an Angular CLI template or using @ngtools/webpack

### ISSUE THREAD

**Issue by mikeumus** [angular/universal-starter#207]
With the Angular CLI becoming so powerful and central to workflow, it's a good time to consider if this starter makes sense to work as an Angular CLI template. See "[App Creation Using Template](https://github.com/angular/angular-cli/wiki/Stories#app-creation-using-template)" in the CLI wiki. Becoming a template would look something like this for a user to get started:

`ng new my-ng2-app --template=universal-starter`

Or adopting [`@ngtools/webpack`](https://www.npmjs.com/~ngtools) to not miss out on any of the innovations happening on the CLI like "code splitting" (see below) and other optimizations. 

See the benefits and ability to use `@ngtools/webpack` standalone from the Angular CLI as presented in [Stephen Fluin's Angular CLI talk](https://youtu.be/uBRK6cTr4Vk?t=6m45s) at Angular Connect 2016:
- Compiles SCSS/LESS
- TypeScript transpilation
- Bundles JavaScript, CSS
- Asset optimization
- Virtual filesystem for assets
  - For serving local assets and compile versions.
- Live-reload via websockets
- Code splitting
  - Recognizing the use of loadChildren in the router, and bundling those modules separately so that any dependencies of those modules are not going to be loaded as part of your main bundle. These separate bundles will be pulled out of the critical path of your application, making your total application bundle much smaller and loading it much more performant.

**Comment by John0x** [comment]
It would be great in general if this starter-project could be made angular cli compatible.  Are there any plans for this?

**Comment by MarkPieszak** [comment]
Yes there is a branch on the CLI that hasn't been merged to the master branch yet. So soon it'll be there!

**Comment by Hongbo-Miao** [comment]
@John0x the branch is here https://github.com/angular/angular-cli/tree/universal#support-for-server-side-rendering
