### ISSUE TITLE
No provider for title.

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#217]
This isn't a big issue since the error is only thrown on the universal side and doesn't crash the app. However I'm interested in how resolving it works because i get the same error with different services as well. 

So i get the following error: 

```
Error: Uncaught (in promise): Error: No provider for Title!
```

I get it when i import: 

```
import {Title} from '@angular/platform-browser';
```

How would i go about resolving this error if i import title in a service and how would i resolve it if i import title in a component? 

Any help is greatly appreciated,

Thanks for the great starter 👍

**Comment by bioub** [comment]
You have to register Title as a provider in your module, for instance :

```typescript
import { Title } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AboutComponent } from './about.component';
import { AboutRoutingModule } from './about-routing.module';

@NgModule({
  imports: [
    AboutRoutingModule
  ],
  declarations: [
    AboutComponent
  ],
  providers: [
    Title
  ],
})
export class AboutModule { }
```

But when I do this I get the following error : 
`EXCEPTION: Uncaught (in promise): TypeError: Cannot create property 'title' on string '<!doctype...'`

Looks like the document string was not parsed with the parseDocument() function.

@gdi2290 does it have something with your Todo : https://github.com/angular/universal/blob/6b71fd94da9aa7650c87f88400fca0606fa56a8f/modules/express-engine/src/index.ts#L103
Or should we call _document from node-platform somehow ? https://github.com/angular/universal/blob/6b71fd94da9aa7650c87f88400fca0606fa56a8f/modules/platform-node/node-platform.ts#L84

**Comment by gdi2290** [comment]
yeah this is a problem with my todo that needs to be done

**Comment by bioub** [comment]
Ok, tell me if I can help on this !

**Comment by inzerceubytovani** [comment]
Also looking forward to support.

**Comment by matiishyn** [comment]
hi guys.
I'm trying to set page title and have the same error @bioub mentioned
![image](https://cloud.githubusercontent.com/assets/3661065/22058631/e7235764-dd69-11e6-8405-9d6a4dac9546.png)

Please help me, how can I do it?

**Comment by failpunk** [comment]
I'm seeing the same error as @matiishyn.  The title tag is semi-important in the world of SEO.

**Comment by inzerceubytovani** [comment]
Look here - https://github.com/angular/universal-starter/issues/287 - might help
