### ISSUE TITLE
How to use pipe?

### ISSUE THREAD

**Issue by bhargav-sae** [angular/universal-starter#220]
I clone this repo and updated the home component like below to use inbuilt [DatePipe](https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html)

**home.component.ts**

```
import { Component } from '@angular/core';

@Component({
  selector: 'home',
  templateUrl: "./home.component.html"
})
export class HomeComponent {
  showDate = new Date();
}
```

**home.component.html**

```
{{ showDate | date }}
```

And this is what I see in console

```
The pipe 'date' could not be found ("[ERROR ->]{{ showDate | date }}"): HomeComponent@0:0 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
The pipe 'date' could not be found ("[ERROR ->]{{ showDate | date }}"): HomeComponent@0:0
    at TemplateParser.parse (http://localhost:3000/index.js:20359:19)
    at RuntimeCompiler._compileTemplate (http://localhost:3000/index.js:41465:51)
    at http://localhost:3000/index.js:41387:83
    at Set.forEach (native)
    at compile (http://localhost:3000/index.js:41387:47)
    at ZoneDelegate.invoke (http://localhost:3000/index.js:85674:26)
    at Zone.run (http://localhost:3000/index.js:85556:43)
    at http://localhost:3000/index.js:85944:57
    at ZoneDelegate.invokeTask (http://localhost:3000/index.js:85707:35)
    at Zone.runTask (http://localhost:3000/index.js:85596:47)
```

_I am still new with universal-angular, Correct me if I am doing it wrong way._

**Comment by flauc** [comment]
I think you need to import the `[CommonModule](https://angular.io/docs/ts/latest/api/common/index/CommonModule-class.html)` in your `app.browser.module.ts` and the `app.node.module.ts`

**Comment by Koslun** [comment]
@flauc It is stated that `UniversalModule` includes `BrowserModule`. `BrowserModule` in turn *should* export `CommonModule`.

Either way, including `CommonModule` in both, only `app.node.module.ts` or neither does not seem to be helping.

**Comment by flauc** [comment]
Is the component that you are trying to use the pipe in, part of another module? That's the only thing i can think of. Because i can use the `DatePipe` and any other pipe with no problems.

**Comment by bhargav-sae** [comment]
> Is the component that you are trying to use the pipe in, part of another module? That's the only thing i can think of. Because i can use the DatePipe and any other pipe with no problems.

It is the part of `HomeModule`, which is included in `app.browser.module.ts`
As I said I just cloned this repo and tried before changing anything, it was working good ( without using Pipe ).
But after changing few lines (as explained above) it is not working.

**Comment by Koslun** [comment]
@bhargav-sae Not tested it but think @flauc is correct. Didn't notice it myself but home and about are in their own modules and not just part of the app and node modules respectively. The needed `CommonModule` is thus not accessible in the Home module since it has not been imported to it. Given that it's a pipe that needs to be imported and not a global service.

So just import `CommonModule` in `HomeModule` to use it in any components that are part of that module, i.e. `HomeComponent`.

**Comment by MarkPieszak** [comment]
Recently a PR added some new Route and modules to the starter, glad someone caught this!

**Comment by Hongbo-Miao** [comment]
So usually you can have a **shared.module.ts**

```
const MODULES = [
  CommonModule,
  RouterModule,
  FormsModule,
  ReactiveFormsModule  // if need
];

const PIPES = [
  YourPipe
];

const COMPONENTS = [
  SomeSharedComponent
];

@NgModule({
  imports: [
    MODULES,
    EffectsModule.run(RouterEffects)
  ],
  declarations: [
    PIPES,
    COMPONENTS
  ],
  providers: [
    AuthHttpService
  ],
  exports: [
    MODULES,
    PIPES,
    COMPONENTS
  ]
})
export class SharedModule { }
```

then import `SharedModule` in the `HomeModule` and `AboutModule`.

I will add a PR.
