### ISSUE TITLE
Pug/Jade view engine

### ISSUE THREAD

**Issue by marvelsrp** [angular/universal-starter#227]
**How use pug/jade template engine?**
I try:
**server.ts**
- rename view engine
`app.set('view engine', 'pug');`
- rename  index file `index.html` to `index.pug`  and rewrite content to pug.
- rename default render `res.render('index',...)` to  `res.render('index.pug', ...)`
- rename engine
```
app.engine('pug', createEngine({
  precompile: true,
  ngModule: MainModule
}));
```
**webpack.config.ts**
- add  pug loader `loaders: [..., { test: /\.pug/, loader: 'pug' }]`

**package.json**
add
```
 "pug": "^2.0.0-beta6",
 "pug-loader": "^2.3.0"
```

All compiled, but server render not work. createEngine worked only with html.

**Comment by BatsShadow** [comment]
My webpack config is based on an older version of this project, and angular 2.0.0, but here is how I have pug working:

```
...
var commonConfig = {
  resolve: {
    extensions: ['', '.ts', '.js', '.json', '.pug', '.style']
  },
  module: {
    loaders: [
      // TypeScript
      { test: /\.ts$/, loaders: ['ts', 'angular2-template-loader'] },
      { test: /\.html$/, loader: 'raw' },
      { test: /\.css$/, loader: 'raw' },
      { test: /\.json$/, loader: 'raw' },
      { test: /\.pug$/, loader: 'pug-html' },
      { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url?limit=10000' },
      { test: /\.styl$/, loader: 'css!stylus?paths=node_modules/bootstrap-styl/&resolve url' }
    ],
  },
  ...
```

And in my components:

```
@Component({
    moduleId: __filename,
    selector: 'payment',
    styles: [ String(require('./payment.styl')) ],
    template: require('./payment.pug')
})
```

**Comment by marvelsrp** [comment]
Cool. pug-html -> html -> app.engine('html')
