### ISSUE TITLE
Server and client both calls OnInit component's Lifecycle Hook

### ISSUE THREAD

**Issue by bhargav-sae** [angular/universal-starter#229]
On static page ( `home page` ) it is working as expected.

When I reload `Item Detail` page, it will fetch Item details upon `onInit` component's `Lifecycle Hook` using `REST API call`, and it reloads with details and refresh the details one more time after `DOMContentLoaded` event.

So to user it reloads the whole page with correct item details ( and in background it is loading whole angular app ) and refreshes item details again ( once it completely loads angular app ).

Does that make sense of my problem? Is that expected behaviour?

*I believe when server side rendering calls onInit() and it calls it again at the client side*

**Comment by gdi2290** [comment]
you have to use the Cache service that will return the response from the request made on the client with the response made on the server

**Comment by bhargav-sae** [comment]
It worked out with Cache service.
