### ISSUE TITLE
Newest version couldn't prerendering html?

### ISSUE THREAD

**Issue by percinor** [angular/universal-starter#232]
I just git clone the new project , it worked,but when  i view source in chrome , server side prerendering html not worked....
2.   could anyone  provide  a example for solve that how to do localstorage   processing. thanks
![e1](https://cloud.githubusercontent.com/assets/16224957/19956792/2455e8f2-a1cb-11e6-962d-c25a4a4197ca.JPG)
![e2](https://cloud.githubusercontent.com/assets/16224957/19956793/2470a0fc-a1cb-11e6-8e68-223f6c092503.JPG)

**Comment by gdi2290** [comment]
@percinor can you download the latest updates and try again?

**Comment by percinor** [comment]
@gdi2290, i download  the latest updates  now ,but  the results are same,   in my project , i put all component in home.module ,i put all  router in  home-routing, exclude service component in browser and node module.

**Comment by percinor** [comment]
forward to #274
