### ISSUE TITLE
What to include for HTMLAudioElement reference?

### ISSUE THREAD

**Issue by bhargav-sae** [angular/universal-starter#234]
I am getting `ReferenceError: Audio is not defined` at server.

I am using this in a directory like below.
`public barking: any = new Audio(require("../../../public/audio/barking-dog.wav"));`

**Comment by bhargav-sae** [comment]
I used renderer instead, and working without any error.
```
barking = this.renderer.createElement(null, "audio");
barking.src = require("../../../public/audio/barking-dog.wav");
```

**Comment by MarkPieszak** [comment]
Glad to hear it. I need to make sure to put that in gotcha's list, knew I had to of forgotten a few!

**Comment by bhargav-sae** [comment]
@MarkPieszak is there any other way to achieve this ? just want to explore other solutions.

**Comment by MarkPieszak** [comment]
Not that I'm aware of, when dealing with the DOM always make sure you use the Renderer, everything else won't exist on the server/Node. 

It's working ok now though?

**Comment by bhargav-sae** [comment]
> It's working ok now though?

Yeah, it is working as expected with renderer.

**Comment by bhargav-sae** [comment]
Btw, I got this solution from [Universal Best-Practices](https://github.com/angular/universal#best-practices)

**Comment by MarkPieszak** [comment]
I forgot to take that from there, and update both lists. But yes, that'll be the way to handle things!
