### ISSUE TITLE
How to deal with "SCRIPT5022: Error: No provider for PlatformRef!" on the IE that version < 11

### ISSUE THREAD

**Issue by lizardd** [angular/universal-starter#236]
when I npm start and run this project on IE9,IE10,the console print the follow error:
SCRIPT5022: Error: No provider for PlatformRef!
How I deal with this error?
Online wait ,In a hurry.

=============
before this error,I fall across a other error,follow
SCRIPT5009: “WeakMap” underfined
but you can npm install core-js@2.4.1,and add script at index.html to deal with it.
 <script src="node_modules/core-js/client/shim.min.js"></script>
=============

**Comment by gdi2290** [comment]
can you try again with latest changes and open another issue? thanks
