### ISSUE TITLE
Angular Universal and Webpack Multi Entry Points

### ISSUE THREAD

**Issue by maufarinelli** [angular/universal-starter#238]
Is there a way to use Webpack Multi Entry Points with Angular Universal?

My concern is that, soon, my website will have many page and I don't want to compile all components of all page in one file only, that will be huge. 

I want, in this case, to have multi entry points. 
For example: one entry point for home (home.js) and another for about (about.js)

Thanks a lot

**Comment by kuldeepkeshwar** [comment]
You can define split points and lazy load the components

**Comment by maufarinelli** [comment]
Thanks @kuldeepkeshwar . Do you have an example?

**Comment by kuldeepkeshwar** [comment]
@maufarinelli check https://github.com/angular/universal-starter/pull/210

**Comment by maufarinelli** [comment]
@kuldeepkeshwar I did not understand your commit. My is my limitted knowledge of Angular2
I see you created `src/app/app.routes.ts` containing the routes. 

But in the models, you didn't import that. 
Instead, you declare `const routes:Routes=[];` and import this empty array 
```
imports: [
    RouterModule.forChild(routes)
 ]
```

I have tried to import the routes Array into the models, but I don't see any lazy load extra call on the Network.

Could you explain me that, please? Thanks a lot

**Comment by kuldeepkeshwar** [comment]
@maufarinelli for lazy loading routes , you can check out https://github.com/angular/universal-starter/pull/235
This divides the application into 3 routes(`Home` ,`About` ,`Lazy`) where `Home` & `About` are normal routes and `Lazy` is lazy loaded
so if you run the server and open `localhost:3000` , you will see `Home` & `About` are already loaded but on navigating to `localhost:3000/lazy` it fetches `Lazy Module` and loads it

**Comment by maufarinelli** [comment]
Hi @kuldeepkeshwar . I see your Pull Request #235 still waiting approval. I think I will wait it to be merged, because I have tried your changes in mine, but my bindings are not working, and I didn't figure out why. 
I put an input with `[(ngModel)]` and a `(click)` binding in and element and they are not working anymore.
Looking forward to see your code merged into master and test it

**Comment by kuldeepkeshwar** [comment]
@gdi2290 please review  #235

**Comment by HonnKing** [comment]
I am confused. If you clone the current state of the repo you get a route called lazy and that claims to be lazy-loaded, but it doesn't appear to actually be lazy. It does load as its own bundle, but it loads on any route, not just /lazy.

So what is the state of lazy loading in this repo? Does it or doesn't it work?
