### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by dgyimesi** [angular/universal-starter#239]
Hi,

after switching to the node module to be bootstrapped in client.ts I get this after recompile/reload: 

`﻿
index.js:18616 Uncaught ReferenceError: Buffer is not defined(…)
`

For reproduction just change `MainModule` import in client.ts to `'./app/app.node.module';`
Has anyone run into the same issue?

**Comment by MarkPieszak** [comment]
You need to import the `app.browser.module` in the `client.ts`, I haven't ran into this, but I'm guessing that's part of the issue. Can you get latest and see if things are working for you?

**Comment by gdi2290** [comment]
should be fix via https://github.com/angular/universal-starter/commit/f2f8d719f7591b55e0d13118b61bfa250abbeb91

**Comment by schoettler** [comment]
I'm still getting this error :/
