### ISSUE TITLE
fix server.ts to Not stop server when 404'ing

### ISSUE THREAD

**Issue by MarkPieszak** [angular/universal-starter#246]
https://github.com/angular/universal/issues/618#issuecomment-259700942

From the above issue:

> Using http service, 404 exception break down server

```
Listening on: localhost:5000
EXCEPTION: Response with status: 404 null for URL: 

.../node_modules/rxjs/Subscriber.js:227
            throw err;
            ^
Response with status: 404 null for URL: 
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by DBuit** [comment]
@MarkPieszak any luck fixes this error? im having the same problem at the moment

**Comment by MarkPieszak** [comment]
Did you try commenting out the lines from the starter in this comment?
https://github.com/angular/universal/issues/618#issuecomment-259711575
