### ISSUE TITLE
Deploy the version d16e5e2  to Heroku doesn’t work

### ISSUE THREAD

**Issue by Damnobre** [angular/universal-starter#248]
Hi Guys, i’m newbie on universal and i’m trying to deploy the universal-starter to Heroku, but it is not works.

After a few hours trying to understend the config and reading the heroku's log, i changed the src/server.ts file and it worked.

I changed the function ngApp(req, res), line 68 (originUrl), like that:

src/server.ts
```
function ngApp(req, res) {
  res.render('index', {
    req,
    res,
    preboot: false,
    baseUrl: '/',
    requestUrl: req.originalUrl,
    originUrl: `http://localhost:${server.address().port}` //(add this)
//   originUrl: 'http://localhost:3000'
  });    
``` 

The question is: is this the corret way to make the deploy works?

**Comment by gdi2290** [comment]
yup, you're correct

**Comment by gdi2290** [comment]
I updated the repo to use the correct port provided by env
