### ISSUE TITLE
Question: Node, browser, shared modules ?

### ISSUE THREAD

**Issue by julienR2** [angular/universal-starter#250]
Hi !

I'm getting a bit confused with the differences between the modules.

I understand the interest of shared module, particularly for lazy loading. However, I'm not quite sure to know when importing a component/service in one or another..

For example in the universal-starter, why importing the "HomeModule" in the node.module and the browser.module instead of the shared.module ?

Thanks for any help in trying to understand these difference !

**Comment by Koslun** [comment]
@julienR2 Can regard the `HomeModule` and `AboutModule` as feature modules.

Recommend reading the style guide, in particular the segment on [app-structure-and-angular-modules]( https://angular.io/docs/ts/latest/guide/style-guide.html#!#app-structure-and-angular-modules).

**Comment by julienR2** [comment]
Thanks ! Interesting reading !

However I still can't figure out why these HomeModule and AboutModule should be imported in a sharedModule (as FormModule for example) ?

Did I miss something else ?

**Comment by gdi2290** [comment]
Currently, the AppModule/MainModule(browser)/MainModule(node) folder structure is a slightly modified version of the style guide to better suit Universal. The style you're referring to is the current style guide that was mentioned above. The angular webpack should example why we use ng-modules (di/runtime) and es6-modules (es6/build-time)
