### ISSUE TITLE
Can't find TS files to debug in chrome devtools

### ISSUE THREAD

**Issue by nabeelaxr** [angular/universal-starter#254]
I want to debug my application and started the application in development mode (commented out enableProdMode()) but can't find TS files in chrome dev tools sources panel, Here is the screenshot of same (only generated JS files) please help me out of this. Thanks

![no-ts](https://cloud.githubusercontent.com/assets/14129350/20351834/d4a2edd0-ac3a-11e6-92c2-e79ee916a742.jpg)

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal-starter/commit/3e5acb809432014693ecf53ca39bddcb84d90fd5
 this is a webpack issue where you need to add `devtool` source-maps config
