### ISSUE TITLE
Access Zone.js

### ISSUE THREAD

**Issue by John0x** [angular/universal-starter#255]
Hey, I saw that zone.js is part of the polyfills so it should be imported correctly, right?

I'm trying to access the req and res objects following the documentation (https://github.com/angular/universal/blob/master/DOCUMENTATION.md#servercontext) using the following: 
````
declare var Zone: any;

let req: any = Zone.current.get('req')
````

But the object is empty. Do I need to do something else or am I not understanding it correctly?

Another Question, how can I use console.log with angular universal? It just doesn't print anything.

**Comment by gdi2290** [comment]
here's an example
https://github.com/angular/universal-starter/commit/e3d92283772307b9f301119ad53380ff4b78f8d4
you need to use it in di
