### ISSUE TITLE
ng2-translate support

### ISSUE THREAD

**Issue by John0x** [angular/universal-starter#263]
Hey, are there any plans to integrate ng2-translate?

Or are there currently limitations with universal and ng2-translate?

**Comment by MarkPieszak** [comment]
I don't think you should have a problem using it.
I just asked @ocombe but it looks like his code itself protects against window if it's not available in a safe `typeof` way.
 
https://github.com/ocombe/ng2-translate/blob/1284b506936f58267815ae19b0e57f08f3a16c04/src/translate.service.ts#L401

Let us know if you run into anything.

**Comment by ocombe** [comment]
It works with universal, I use it in one of my projects, just make sure you use a specific loader for the server side

**Comment by John0x** [comment]
Great, thank you guys :)

**Comment by ghego1** [comment]
I'm having some troubles implementing server-side translations. I'm implementing the custom translator like so:

    import { TranslateModule, TranslateLoader, TranslateService } from 'ng2-translate';
    import {Observable} from "rxjs/Observable";
    var fs = require('fs');

    export class TranslateUniversalLoader implements TranslateLoader {
        constructor(private prefix: string = 'i18n', private suffix: string = '.json') {}

        public getTranslation(lang: string): Observable<any> {
            return Observable.create(observer => {
                observer.next(JSON.parse(fs.readFileSync(`${this.prefix}/${lang}${this.suffix}`, 'utf8')));
                observer.complete();
            });
        }
    }

    @NgModule({
      bootstrap: [ AppComponent ],
      declarations: [ AppComponent ],
      imports: [
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useClass: TranslateUniversalLoader,
        }),
        UniversalModule
      ]
    })
    export class AppModule {

      constructor(private translateService: TranslateService){
        translateService.use('en');
      }

    }

However, I'm getting this error:

    /Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/zone.js/dist/zone-node.js:132
                        throw error;
                        ^

    Error: Can't resolve all parameters for TranslateUniversalLoader: (?, ?).
    at CompileMetadataResolver._getDependenciesMetadata (/Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:14935:21)
    at CompileMetadataResolver._getTypeMetadata (/Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:14829:28)
    at CompileMetadataResolver.getProviderMetadata (/Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:15026:42)
    at /Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:14975:47
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (/Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:14959:21)
    at /Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:14669:65
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51)
    at CompileMetadataResolver.loadNgModuleMetadata (/Users/gherardo/Documents/Apps/JS/landing/enLandUn/node_modules/@angular/compiler/bundles/compiler.umd.js:14625:31)

Any idea of what I'm missing?

**Comment by ghego1** [comment]
Nevermind, found out that with ng2-translatev. 5.0.0 the loader works like this:

    export class TranslateUniversalLoader implements TranslateLoader {
        /**
         * Gets the translations from the server
         * @param lang
         * @returns {any}
         */
        public getTranslation(lang: string): Observable<any> {
            return Observable.create(observer => {
                observer.next(JSON.parse(fs.readFileSync(`i18n/${lang}.json`, 'utf8')));
                observer.complete();
            });
        }
    }

I'm still getting a "Cannot read property 'trim' of undefined" error, but I guess that is due to some other problem.

**Comment by markelarizaga** [comment]
Hi @ocombe,
you mention you made ngx-translate work with Angular Universal. AFAIK the starter is using Angular core 2.1.2 and I read [here](https://github.com/ngx-translate/core) that ngx-translate works only from 2.3.o onwards. I would like to know how did you make both work together. Is there any sample somewhere I could look at?
Thanks a lot in advance.

**Comment by MarkPieszak** [comment]
You could update the starter to use a higher version, the workaround helps allow you to do it. You might just run into some edge case issues, I think that's why we have pinned lower for now. Personally haven't had any issues and I use 2.4.5 so you should be fine ! @markelarizaga

**Comment by ocombe** [comment]
I need to update the readme, ngx translate works from 2.0.0 to 4.x :)
No problem to use it on the server side, except that you should use a loader that works on the server side

**Comment by markelarizaga** [comment]
Hey @MarkPieszak and @ocombe thanks a lot for your answers, and for how fast they came.
I tried that and I think I'm closer but I'm still having problems. Not to pollute this thread, I will open a new issue.

**Comment by markelarizaga** [comment]
Instead of opening a new issue, I added a comment on https://github.com/ngx-translate/core/issues/422 as it may be related.

**Comment by mchambaud** [comment]
Is there a demo of how to implement ngx-translate + angular universal somewhere?

**Comment by mchambaud** [comment]
Found it.. For anybody interested -> https://github.com/ng-seed/universal

**Comment by premiumwd** [comment]
@ghego1 how did you resolve server side code with client side? How did you separate it?

**Comment by ghego1** [comment]
@premiumwd you should have a separate module for the client side and for the server side (e.g. `app.browser.module.ts` and `app.node.module.ts`), then you do the different setups in each one. As per the client side, you can initiate ngx-translate as explained in the docs.

**Comment by premiumwd** [comment]
@ghego1 Right I actually called the server side translations in app.module.server.ts here:

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { Http } from '@angular/http';
import { ServerModule } from '@angular/platform-server';

import { AppModule } from './app.module';
import { AppComponent } from './app.component';

import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';

// SERVER TRANSLATE CODE HERE
import { TranslateUniversalLoader } from './core/services/translate.service';


@NgModule({
imports: [
    ServerModule,
    AppModule,
    TranslateModule.forRoot({
        loader: {
            provide: TranslateLoader,
            useFactory: TranslateUniversalLoader,
            deps: [Http]
        }
    }),
],
bootstrap: [AppComponent]
})
export class AppServerModule { }
`
I wanted to see how you did it. I was unable to do it this way. You want me to put a conditional statement inside app.module.ts and call it if it is dev or prod environment like below:

`
if (process.env.ENV === 'production') {
  // production
} else {
}
`

Can you show me how you did it?

**Comment by premiumwd** [comment]
@ghego1 figured out issue in loader for client it is this:

```
    TranslateModule.forRoot({
        loader: {
            provide: TranslateLoader,
            useFactory: TranslateUniversalLoader,
            deps: [Http]
        }
    }),
```

for server side loader is this:

```
    TranslateModule.forRoot({
        loader: {
            provide: TranslateLoader,
            useClass: TranslateUniversalLoader
        }
    }),
```

**Comment by peterpeterparker** [comment]
@ghego1 could you show some code you used in `app.browser.module.ts` and `app.node.module.ts`... I'm struggling finding the right configuration for the client side
