### ISSUE TITLE
includeClientPackages - supplied parameters do not match any signature of call target

### ISSUE THREAD

**Issue by vadost** [angular/universal-starter#264]
Error appears during the execution of command 'npm start':

universal-starter/node_modules/ts-node/dist/index.js:160
                    throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset));
                    ^
TSError: ⨯ Unable to compile TypeScript
webpack.config.ts (90,14): Supplied parameters do not match any signature of call target. (2346)

**Comment by gdi2290** [comment]
sorry about that. fixed via https://github.com/angular/universal-starter/commit/797907e9a8b9af7e8ebe9fc680075f35fb55b3ae
