### ISSUE TITLE
Cannot redefine property: b 

### ISSUE THREAD

**Issue by antonyRoberts** [angular/universal-starter#266]
After the Commits the last few days any attempt to import MaterialModule.forRoot() results in error, Object.defineProperty(exports, name {
TypeError: Cannot redefine property: b
![universalmaterialissue](https://cloud.githubusercontent.com/assets/19535379/20459225/d9443fa2-ae87-11e6-9fe6-cf1f19967ba5.png)
Repository showing issue, [UniversalMaterialBreak](https://github.com/antonyRoberts/UniversalMaterialBreak/)

**Comment by John0x** [comment]
@antonyRoberts open webpack.config.ts and find the following line:
````
/@angularclass|@angular|angular2-|ng2-|ng-|@ng-|angular-|@ngrx|ngrx-|@angular2|ionic|-angular2|-ng2|-ng/
````

Change it to:
````
[ /@angularclass|@angular|angular2-|ng2-|ng-|@ng-|angular-|@ngrx|ngrx-|@angular2|ionic|-angular2|-ng2|-ng/ ]
````
(sorround it by [ ])

**Comment by antonyRoberts** [comment]
Adding [] to externals: includeClientPackages() presents new error 
![um2err](https://cloud.githubusercontent.com/assets/19535379/20467438/d05eca50-af55-11e6-9a53-65d09ea7556b.png)

**Comment by John0x** [comment]
@antonyRoberts Yeah, you can remove the meta service, which currently causes that problem.
Jsut delete the file and references of the angular2-meta.ts

**Comment by antonyRoberts** [comment]
Thanks @John0x commenting out Meta, from browser.module and node.module resolves the issue.

Friendly reminder to anyone using Material with Universal. Universal Module must be imported after Material Module or you'll receive the error 

 EXCEPTION: Uncaught (in promise): Error: This method is not implemented in Parse5DomAdapter: getCookie Error: This method is not implemented in Parse5DomAdapter: getCookie

We can close this thread.
