### ISSUE TITLE
Can't get current request (or more specifically cookies)

### ISSUE THREAD

**Issue by julienR2** [angular/universal-starter#271]
Hi again !

Going deeper and deeper in the use of Universal !

I'm now trying to get the request object from the server (i.e. the cookies passed along this request). Following this issues' instructions (https://github.com/angular/universal/issues/273) and the example already set in the universal-starter (https://github.com/angular/universal-starter/blob/master/src/browser.module.ts#L21), I though by logging ```Zone.current.get('req')``` I'd get it, but instead I'm getting an empty object..

However, in node.module.ts, returning ```return Zone.current.get('req') || {};``` instead of the current ```{}``` does allow me to get access to the request object using:
```
constructor(@Inject('req') cookies: any) {
  console.log('req',  req);
}
```

What do I do wrong ? Is this example currently set up in the universal-starter is supposed to work already ?

Thanks for your help !

**Comment by gdi2290** [comment]
req/res on the client doesn't do anything. the real object only show up on the server

**Comment by julienR2** [comment]
That what I figure out later, sorry ! I guess I mixed it up a bit.. I've been able to handle correctly the cookies on both side

However in the univsersal-starter I think it would be clear to set up the example
```
export function getRequest() {
  return Zone.current.get('req') || {};
}
```
in the node.module.ts instead of browser.module.ts to avoid confusion. In the way it is now, it seems like it could be interesting to get the ```Zone.current.get('req')``` in the browser.

Thanks for your help !

**Comment by samikarak** [comment]
Hello,

I got the same problem. I need the requests headers on the frontend. I didn't understand exactly how you pass the req object now ?

**Comment by mtuan94** [comment]
same problem.

**Comment by mmathys** [comment]
bumo

**Comment by mmathys** [comment]
@gdi2290 It seems that the option of @julienR2 is not available anymore in Angular 4... How can one pass the req object into the Angular app?

**Comment by julienR2** [comment]
You can check this issues on the same subject https://github.com/angular/universal/issues/709.
The way to get the request changed a bit using now the OpaqueToken.
In your browser.module
```
import { REQUEST } from './shared/constants/request';
...
export function getRequest() {
  // the Request object only lives on the server
  return { cookie: document.cookie };
}
...
{
  // The server provides these in main.server
  provide: REQUEST,
  useFactory: (getRequest)
}
```
./shared/constants/request
```
import { InjectionToken } from '@angular/core';

export const REQUEST = new InjectionToken<string>('REQUEST');
```
Then Inject it the same way as before when you need it
```
import { REQUEST } from './shared/constants/request';
...
constructor(
  ...,
  @Inject(REQUEST) private request
) { }
```
I hope this helps !

However if I manage to get the request on browser side, I can't managed to access it on Serverside anymore.. So if anyone manage it I would be interested !

**Comment by mmathys** [comment]
@julienR2 thanks for your answer, but I'm still a bit confused:

Do I have to make any additional changes in `main.server`, like actually instruct the server to pass the arguments?

**Comment by julienR2** [comment]
@mmathys you probably want to update your main.server following the good example of @frozenpandaz here https://github.com/FrozenPandaz/ng-universal-demo/blob/master/src/main.server.ts

You'll be using `ngExpressEngine` which set up the REQUEST providers for the server (https://github.com/angular/universal/blob/master/modules/ng-express-engine/src/main.ts#L129). Then set up the REQUEST provider for the browser, and you should be all done !

Hope this help ! Let me know if you need more details

**Comment by mmathys** [comment]
@julienR2 Thanks a bunch! That worked! You're the real MVP @julienR2 ❤️ :heart: ❤️

**Comment by julienR2** [comment]
No problems ! Glad it helps ! 👍
Do you manage to get the request on the server side too ?

**Comment by mmathys** [comment]
@julienR2 Yes I did!

**Comment by julienR2** [comment]
Oh Nice ! So maybe you can help me on this, because I'm still stuck with the `No provider for InjectionToken REQUEST` error when trying to access the REQUEST from server.. (like here https://github.com/angular/universal/issues/709#issuecomment-300745110)

Have you added anything to your server.modules ?

**Comment by julienR2** [comment]
Oh Nice @mmathys ! So maybe you can help me on this, because I'm still stuck with the `No provider for InjectionToken REQUEST` error when trying to access the REQUEST from server.. (like here https://github.com/angular/universal/issues/709#issuecomment-300745110)

Have you added anything to your server.modules ?

**Comment by mmathys** [comment]
I did it like this: 

server.ts:
```typescript
...
app.engine('html', (_, options, callback) => {
  const opts = {
    document: template,
    url: options.req.url,
    extraProviders: [{ provide: 'testReq', useFactory: () => options.req }]
  };
  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => callback(null, html));
});
...
```

app.component.ts:
```typescript
import { Inject } from '@angular/core';
...
constructor(..., @Inject('testReq') private req: any) {
  console.log(this.req);
}
...
```

@julienR2 I'm not 100% sure what you mean, one can access the request via `options.req` in `app.engine` callback (node.js server) as well as in the browser side (angular rendered on the server to html). But obviously when the browser side is rendered in the browser, i. e. after the rendered html has been loaded, the req object is gone and the app crashes. I'm working on it right now. I will upload my code as soon as everything works.

**Comment by julienR2** [comment]
Thanks @mmathys I'll try your solution.

My problem is more about `ngExpressEngine` it self I think.
Using `ngExpressEngine` to render the app like this..
```
app.engine('html', ngExpressEngine({
  bootstrap: ServerAppModule
}));
```
..it is supposed to add the REQUEST provider on the server.modules (https://github.com/angular/universal/blob/master/modules/ng-express-engine/src/main.ts#L129)
Then we should only have to provide the "fake" REQUEST in the browser.modules, and then inject REQUEST to use it..

However, when I do so, I get a `No provider for InjectionToken REQUEST`.. It seems the `ngExpressEngine` deosn't set the provider..

But I'll probably set it manually as you did, using the options.req until I find out why `ngExpressEngine` fail to set the REQUEST !

Thanks for your help 👍

**Comment by mmathys** [comment]
I see... This is an ugly workaround, and not sustainable, you're right.

Anyways, here is the full solution, with the browser (rendering in the browser) working:

_BEWARE, IT'S UGLY_

**server.ts**:
```typescript
...
app.engine('html', (_, options, callback) => {
  const opts = {
    document: template,
    url: options.req.url,
    extraProviders: [{ provide: 'request', useFactory: () => options.req }]
  };
  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => callback(null, html));
});
...
```

**app.component.ts**:
```typescript
import { Inject, Injector, PLATFORM_ID } from '@angular/core';
import { isPlatformServer } from '@angular/common';
...
constructor(..., private injector: Injector, @Inject(PLATFORM_ID) private platformId: Object) {
  if (isPlatformServer(this.platformId)) {
    console.log(this.injector.get('request'))
  } else {
    console.log('we\'re rendering from the browser, so there is no request object.');
  }
}
...
```

- Do not use `req` as name. It won't work.

**Comment by julienR2** [comment]
Thanks ! I'll use this for now 👍  and investigate the problem with ngExpressEngine

**Comment by iliasbhal** [comment]
```
app.engine('html',  (_, options, callback) => {
  let engine = ngExpressEngine({
    bootstrap: ServerAppModule,
    providers: [ { provide: 'request', useFactory: () => options.req } ]
  });

  engine(_, options, callback)
})
```

and 

```
import { Inject, Injector, PLATFORM_ID } from '@angular/core';
import { isPlatformServer } from '@angular/common';
...
constructor(..., private injector: Injector, @Inject(PLATFORM_ID) private platformId: Object) {
  if (isPlatformServer(this.platformId)) {
    console.log(this.injector.get('request'))
  } else {
    console.log('we\'re rendering from the browser, so there is no request object.');
  }
}

```

**Comment by iUwej** [comment]
`app.engine('html', (_, options, callback) => {
  console.log("Response items  initialize", options.res);
  const opts = { document: template, url: options.req.url,extraProviders:[
  	{provide: 'request',useFactory: ()=> options.req},
  	{provide: 'response', useFactory: ()=> options.res} 
  	] };

  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => callback(null, html));
});`

How can inject the response object?. It doesn't seem to be defined as in options.res on the options.req is defined

**Comment by michaelpwilson** [comment]
I tried @iliasbhal approach but after running in production I get the following error:

    Error: StaticInjectorError[{provide:"request", useFactory:useFactory}]: 'deps' required

I don't see anything different in the code:

    app.engine('html', (_, options, callback) => {
      let engine = ngExpressEngine({
        bootstrap: AppServerModuleNgFactory,
        providers: [
          { provide: 'request', useFactory: () => options.req },
          provideModuleMap(LAZY_MODULE_MAP)
        ]
      });

      engine(_, options, callback);
    });

**Comment by michaelpwilson** [comment]
Fixed by adding empty array to deps for the provider:

    { provide: 'request', useFactory: () => options.req, deps: [] },

**Comment by chintan13** [comment]
@michaelpwilson thanks man,

full block is here we need to replace in server.ts is

app.engine('html', (_, options, callback) => {
    let engine = ngExpressEngine({
        bootstrap: AppServerModuleNgFactory,
        providers: [
            { provide: 'request', useFactory: () => options.req, deps: [] },
            provideModuleMap(LAZY_MODULE_MAP)
        ]
    });
    engine(_, options, callback);
});

export class AppComponent {
    constructor(
        private injector: Injector,
        @Inject(PLATFORM_ID) private platformId: Object
    ) {
        console.log('hi, we\'re here!');
        if (isPlatformServer(this.platformId)) {
            let req = this.injector.get('request');
            console.log("locales from crawlers: " + req.headers["accept-language"]);
            console.log("host: " + req.get('host'));
            console.log("headers: ", req.headers);
        } else {
            console.log('we\'re rendering from the browser, there is no request object.');
        }
    }
}

**Comment by den-luschitsky** [comment]
@iUwej, for response object you should use following approach in server provider sections:
`{ provide: RESPONSE, useFactory: () => options.req.res, deps: [] }`

and then in your component
`import { RESPONSE } from '@nguniversal/express-engine/tokens';`
`import { Response } from 'express';`

`constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    @Optional() @Inject(RESPONSE) private response: Response
  ) { }`
