### ISSUE TITLE
preboot is not working

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal-starter#273]
I tried to enable preboot but it is not working , not even generation preboot script

I have enabled it with below config.
```
app.engine('.html', createEngine({
  ngModule: MainModule,
  preboot: true,
  providers: [
    // use only if you have shared state between users
    // { provide: 'LRU', useFactory: () => new LRU(10) }

    // stateless providers only since it's shared
  ]
}));
```

repo: https://github.com/kuldeepkeshwar/universal-starter

**Comment by gdi2290** [comment]
you have to set preboot in the request/response config

**Comment by kuldeepkeshwar** [comment]
so instead of passing config to `createEngine`
do I need to pass it respone.render  ?
```
res.render("index", {
    req,
    res,
    ngModule: MainModule,
    preboot: true,
    baseUrl: "/",
    requestUrl: req.originalUrl,
    originUrl: "http://localhost:3000"
  });
```

**Comment by gdi2290** [comment]
you can keep ngModule in createEngine but preboot config can't live there
