### ISSUE TITLE
ModelService need add post method and parameter.

### ISSUE THREAD

**Issue by percinor** [angular/universal-starter#274]
i direct  modify   ApiService add post method in it,  its display ok ,but in viewsource html, the callback data all undefined. i  did not know how modify ModelService  because  it affect by CacheService.

![e1](https://cloud.githubusercontent.com/assets/16224957/20587385/22a53ef8-b248-11e6-87cf-7e795acc413b.JPG)
![e2](https://cloud.githubusercontent.com/assets/16224957/20587387/246c686a-b248-11e6-9bf4-08323316d648.JPG)

**Comment by gdi2290** [comment]
sorry the two services are probably causing more confusion. the use of caching should be moved to ApiService. The only reason why I used it in ModelService was to allow developers to have more control over it. Can you also change your Angular version to 2.1.x
