### ISSUE TITLE
isBrowser and isNode not working on server correctly

### ISSUE THREAD

**Issue by amorri40** [angular/universal-starter#276]
I have a clean checkout of universal-starter expect that I added the following two lines into about.module.ts:
```javascript
import {isBrowser, isNode } from 'angular2-universal/browser';
console.error('Is browser:',isBrowser,"Is node:",isNode);
```
The result is not what I expect at all, on the server (npm start) it says:
```bash
[nodemon] starting `node dist/server/index.js`
is browser: true is node: false
Listening on: http://localhost:3000
```

Surely it should be the other way around? On the browser the console.error gives the correct result.

Many thanks

**Comment by asgerjensen** [comment]
Import them from 'angular2-universal/node' in your server bootstrap main module. From there inject them to your root scope via 
    { provide : 'isBrowser', useValue : isBrower }

**Comment by amorri40** [comment]
That is already there in the `node.module.ts` file that has not been modified.

More information of what I'm trying to do if it helps:
I want to load an angular2 component that uses `Element` called `angular2-tree-component`
and based on the answer here: http://stackoverflow.com/questions/40751383/angular-universal-dynamic-imports-for-browser-only was trying to get the same conditional input working like so:
```javascript
import { isBrowser } from 'angular2-universal';
import { TreeModule } from 'angular2-tree-component';

let imports = [
    ... //your modules here
];
let declarations = [
    ... //your declarations here
];

if (isBrowser) {
    imports.push(TreeModule);
}

@NgModule({
    bootstrap: [AppComponent],
    declarations: declarations,
    providers: [
        ... //your providers here
    ],
    imports: imports
})
```

But the problem is when running on the server it is saying isBrowser is true when it should be false.

**Comment by MarkPieszak** [comment]
In your about.module can you do the import from regular "angular2-universal", without the /browser and give it a shot? Sorry on an iPad at the moment.

**Comment by amorri40** [comment]
Thank you @MarkPieszak that is exactly what was wrong.
