### ISSUE TITLE
bundle(js) is being served at very slow rate 

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal-starter#280]
The recent changes (brotli/compression) ,has increased the response time of  `main.bundle.js` it's ~ 1.47s

<img width="722" alt="screen shot 2016-11-28 at 10 56 39 am" src="https://cloud.githubusercontent.com/assets/10448534/20657197/002f9cbe-b55a-11e6-9fad-4d682f9fbea3.png">

commenting out below code , bring it back to 500ms
```
app.use(interceptor((req, res)=>({
  isInterceptable: () => true,
  intercept: ( body, send ) => {
    const encodings  = new Set(accepts(req).encodings());
    const bodyBuffer = new Buffer(body, 'utf-8');
    let output = bodyBuffer;
    // check for encoding support
    if (encodings.has('br')) {
      // brotli
      res.setHeader('Content-Encoding', 'br');
      output = compressSync(bodyBuffer);
    } else if (encodings.has('gzip')) {
      // gzip
      res.setHeader('Content-Encoding', 'gzip');
      output = gzipSync(bodyBuffer);
    }
    send(output);
  }
})));
```

<img width="724" alt="screen shot 2016-11-28 at 10 56 58 am" src="https://cloud.githubusercontent.com/assets/10448534/20657198/0058e9ca-b55a-11e6-8300-f66c4169c269.png">

**Comment by gouravcoder** [comment]
@kuldeepkeshwar pls review:
https://github.com/angular/universal-starter/pull/283
