### ISSUE TITLE
@angularclass/bootloader not in npm registry

### ISSUE THREAD

**Issue by teacii** [angular/universal-starter#284]
Hi,

I see that the repo was recently updated to include @angularclass/bootloader
However now I cannot do a npm install as the @angularclass/bootloader is not in the npm registry.
Work in progress ?

Cheers
TeaCii

**Comment by flauc** [comment]
You can install directly from github if you need it right away: 

```
"@angularclass/bootloader": "git+https://git@github.com/AngularClass/angular2-bootloader.git",
```

**Comment by gdi2290** [comment]
sorry about that npm defaults to private. 1.0.1 is public

**Comment by teacii** [comment]
@flauc Thanks for the update. However at the time I raised issue, that repo was not available.
@gdi2290 Thanks man. It worked.
