### ISSUE TITLE
Wired multer error 

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#286]
This might be a completely out of place question, but I've been getting this error when using multer with the starter. 

```
TypeError: Cannot read property 'on' of undefined
    at new Multipart...
```

I've completely drained out all my ideas. The thing is multer used to work with the starter before the changes for AoT. I'm hoping it might be something in the `_workaround.node.ts` file or maybe something in webpack that conflicts with the library. 

This is the block of code that breaks: 

```ts
this.parser = new Dicer(parserCfg);
  this.parser.on('drain', function() {
    self._needDrain = false;
    if (self._cb && !self._pause) {
      var cb = self._cb;
      self._cb = undefined;
      cb();
    }
```

Any help is greatly appreciated.

**Comment by antonyRoberts** [comment]
What version of zone.js are you using?(Problem with Multer: zone 0.6.26 starts at 0.6.22 )[https://github.com/angular/zone.js/issues/498]

**Comment by flauc** [comment]
I'm not home right now so I can't check right away, but I think you might have saved my life just now 👍

**Comment by antonyRoberts** [comment]
Best of luck, following zone has been a game of whack-a-mole

**Comment by flauc** [comment]
Reverting back to 0.6.21 actually solved it. Thanks a lot.
