### ISSUE TITLE
not implemented in Parse5DomAdapter: getElementsByTagName

### ISSUE THREAD

**Issue by teacii** [angular/universal-starter#287]
Hi,

I may be running away with things that are under development. So please accept my apologies upfront.

When using the included "Meta" service, I got following error:
EXCEPTION: This method is not implemented in Parse5DomAdapter: getElementsByTagName

Here my code:
```
export class AboutComponent implements OnInit{
  private name: MetaDefinition = {name: 'description', content: 'Yoo Hoo'};
  constructor(
      @Inject('req') req: any,
      private _meta:Meta
  ) {
    // console.log('req',  req)

  }

  ngOnInit(){
    this._meta.updateTag('meta',this.name);
  }
}
```
Thank you for any assistance in advance.

**Comment by inzerceubytovani** [comment]
Same problem here.

**Comment by MarkPieszak** [comment]
We never finished implementing that method yet actually (https://github.com/angular/angular/blob/2a3ca7bfcfc4c861687eec252cc01ffc55796134/modules/%40angular/platform-server/src/parse5_adapter.ts#L358).
Let me take a look!

**Comment by Reuvenc** [comment]
Got same error with Parse5DomAdapter:getAttributeNS.

**Comment by MarkPieszak** [comment]
@Reuvenc can you use `.getAttribute('test:foo')` and try to grab the attribute with its namespace like that instead, and see if it works?

**Comment by john-landgrave** [comment]
This is also pretty frustrating for our team as well. We have a fairly time-sensitive project, so I would be happy to implement a workaround in the meta service if that's the way that I had to go. I have already tried to get at the head various ways, but I can't seem to get a handle on a DOMNode (el) to pass in to get a hold of the head. I tried doing `this._dom.defaultDoc().head`, but apparently that's just a string per a log'd `Object.prototype.toString.call(this._dom.defaultDoc());` (even though the interface says it should return a `Document`) and `.parse()` is also not implemented yet?

Is there some way that you all know of that I can get a hold of the `html` Node to pass into a `this._dom.querySelector` or something so that I can add a meta tag? `GetTag` is also completely broken as it relies on `.query()` which is also not implemented. The alternate plan was to drop a dummy meta tag in there (ugly, I know) and then `getTag` it and `updateTag` it on the server side. Ironically, all of this works perfectly fine client side, where it's already too late for things like Facebook sharing.

I'm happy to help with this however I can and have forked and will see if I can implement a solution. Is there a particular reason that parse hasn't been implemented with the native `parse5.parse()` function? That seems like the easiest solution to begin with, as it would be trivial to then get the `<head>` tag.

**Comment by inzerceubytovani** [comment]
@john-landgrave  I figured it out how to get HEAD element with this workaround:

In __getOrCreateElement_ when you change 

`const head = this._dom.getElementsByTagName(this._dom.defaultDoc(), 'head')[0];` 

into 

`const head = this._document.head;`

Document was injected in constructor:

`@Inject(DOCUMENT) private _document: any`

However this solution only append new element in __getOrCreateElement_ only append new child. Now I am trying to find out workaround how to update existing meta. 

Also when you need change title, use this 

`this._document.title = 'my title`;

**Comment by john-landgrave** [comment]
Okay, just in case anyone else lands here and needs this, to clarify @inzerceubytovani's help above:

1. Add the following method to the `angular2-meta.ts`: `constructor(@Inject(DOCUMENT) private _document: any) {}`
2. Add the following import to the top of the file: `import { DOCUMENT } from '@angular/platform-browser';`
3. Add the `Inject` symbol to the import from "@angular/core". That import should look like at least: `import { Injectable, Inject } from '@angular/core';`
4. Change `_appendMetaElement` to look like this:
`private _appendMetaElement(meta: HTMLMetaElement): void {
    const head = this._document.head;
    this._dom.appendChild(head, meta);
  }`

After you do that, feel free to use the addTags method freely and you should get your additional meta tags showing up!

**Comment by Reuvenc** [comment]
@MarkPieszak It happens when I'm using an SVG, seems like it fails when providing xlink:href attribute. 

``` html
<svg>
    <use xmlns:xlink="http://www.w3.org/1999/xlink"
	     xlink:href="#right-arrow">
    </use>
</svg>
```

I'm not sure how should I your suggestion in such case.

**Comment by xzengCB** [comment]
@john-landgrave Really appreciate your sharing of the work around for meta service!

**Comment by dottodot** [comment]
I also get this error when trying to use `angular2-meta.ts` in my own project using universal-cli

```
/bailey-uni/node_modules/@angular/platform-browser/src/dom/dom_adapter.js:9
export function getDOM() {
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/bailey-uni/dist/server.bundle.js:2042:18)
    at __webpack_require__ (/bailey-uni/dist/server.bundle.js:27:30)
```
not sure what I'm missing as don't get the when I clone universal-starter and I have the same versions of angular and universal installed.

**Comment by orgbx** [comment]
@dottodot If you are still having this issue, take a look at this gist https://gist.github.com/orgbx/af6a2920b5d66a5e04972719f46cb71f

I couldn't find out why I was getting the error on a project I have but not on the current universal-starter but finally, using `__platform_browser_private__.getDOM()` instead of importing directly `getDOM` from inside the @angular/platform-browser/src/dom/ works! 🎉

**Comment by flauc** [comment]
Hi @orgbx 

Thanks for the gist, however I've added this method to the `Meta` class:

```typescript

private _dom: DomAdapter =  __platform_browser_private__.getDOM();

setTitle(title: string) {
  this._dom.setTitle(title)
}
```

I get the following error when using it: 

```
Unhandled Promise rejection: Cannot create property 'title' on string '<!doctype html>
```

Any idea why? Thanks 👍

**Comment by orgbx** [comment]
@flauc Actually, in the project I'm developing I added the same method to this SeoService 😄 (I've also removed all the update & remove methods, and restricted the addTags method to work only on server side). 

I've updated the gist but basically, just use the publicly available `DOCUMENT` token injected in the constructor
 ```
 /**
   * Sets the title of the page
   */
  setTitle(title: string) {
    this._document.title = title
  }
```

**Comment by matiishyn** [comment]
Thanks @orgbx 
It works

**Comment by failpunk** [comment]
I'm getting the following error even after the previous workarounds:
**TypeError: Cannot assign to read only property 'title' of <!doctype html>**
title

**Comment by DynamicRemo** [comment]
@orgbx i followed your gist and Thanks, it works. 
The title on the page is updated but when i check on server (or by viewing page source) its still have the title from index.html page. Am i missing anything? Thanking you!

**Comment by orgbx** [comment]
Strange, It does replace the default title from index.html in our case. 
Is your app fully rendered while disabling JS? We had a case where we messed up with the HTTP providers, and all the XHR events weren't being caught inside the Zone, so the HTML was returned from server before all the service callbacks were done and the app was stable.
Do test a non async case, just a direct setTitle from the constructor of your root component and see if it works. Good luck.

**Comment by DynamicRemo** [comment]
Sorry @orgbx for the late response and Thanks, its working fine.  Now i am trying to add meta tags (og:url, og:image, article:tag) dynamically from my components but the code which is in the provided gist is a bit confusing to me. Would you mind explaining that a bit with an example? That would be really nice of you. Thanking you!

**Comment by Sathishchary** [comment]
Same problem here.How can I add the og:url and og:image meta tags for social share(twitter ,fb ,etc) dynamically ,Can you please provide a sample example?

**Comment by orgbx** [comment]
@DynamicRemo & @Sathishchary 
```typescript
        let desc: MetaDefinition = { name: 'description', content: description };
        let ogDesc: MetaDefinition = { name: 'og:description', content: description };
        let ogTitle: MetaDefinition = { name: 'og:title', content: title };

        this._seo.addTags([desc, ogDesc, ogTitle]);
```
The MetaDefinition interface in the gist, has some in the jsdoc comments.

**Comment by Skillnter** [comment]
@orgbx  only CSR but no SSR..... it just stopped the error which was showing nothing else changed...

**Comment by furcino** [comment]
Hello, I was looking for the solution too. Just build an angular5 project and wanted seo to work with angular-universal. I didn't find it here so I am adding it:

`import { Component } from '@angular/core';
import { Title, Meta, MetaDefinition } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  public constructor(public meta: Meta, public pageTitle: Title) {
    pageTitle.setTitle("Furcino.COM");
    const keywords: MetaDefinition = {
      name: "keywords",
      content: "angular2, java, javaEE, angular-universal"
    }
    const description: MetaDefinition = {
      name: "description",
      content: "This is a description"
    }
    this.meta.addTags([keywords, description]);
    //this.meta.updateMeta("keywords", "one two three");
  }

  title = 'app';
}`

So people can find this: 

I wanted to **change meta tags and page title in angular5 during the prerender phase**. That led me to here. I finally just started searching the documentation and the solution was there clear as day. The solution lets you even **change meta tags and page title dinamically in angular5**. This is just for demonstration purposes. The code for meta tag update and page title update needs to be probably moved in the real application.
