### ISSUE TITLE
Can someone explain the "+app" naming convention?

### ISSUE THREAD

**Issue by anorborg** [angular/universal-starter#289]
This probably isn't the appropriate place to ask, but I attempted to google and haven't seen the "+" prefix used anywhere else and am very curious. Apologies if this isn't the right place.

**Comment by MarkPieszak** [comment]
It means it's a Module/NgModule. Just a naming convention that seemed to appear a while back, but it's helpful to recognize what it is real quick! Also, I personally only make something a Module if I'm going to lazy-load it, but that's personal preference.

**Comment by anorborg** [comment]
@MarkPieszak thanks! Do you have a source for that? Trying to be able to point to something.

**Comment by MarkPieszak** [comment]
> The + in front of the about folder is a naming convention for modules that are being lazy loaded.

From: https://medium.com/@daviddentoom/angular-2-lazy-loading-with-webpack-d25fe71c29c1#.94iv3jf73

**Comment by anorborg** [comment]
Awesome! Thanks @MarkPieszak
