### ISSUE TITLE
Production build overrides PORT environment variable

### ISSUE THREAD

**Issue by Hagendorn** [angular/universal-starter#291]
When I run a production build with:
`npm run build:prod:ngc`

Than try to set the `PORT` environment variable by:
`PORT=8080 npm run server`

The server starts on port `3000`, but it should use `8080` instead.

I think I have found the reason for that. The `webpack.DefinePlugin` overrides the hole `process.env` object defined in the `webpack.prod.config.ts` [file line 14](https://github.com/angular/universal-starter/blob/master/webpack.prod.config.ts#L14):
```javascript
new webpack.DefinePlugin({
  'process.env': {
    'NODE_ENV': JSON.stringify('production'),
    'AOT': true
  }
}),
```

To fix that issue the provided configuration for the `webpack.DefinePlugin` should be changed to:
```javascript
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production'),
  'process.env.AOT': true
}),
```
This would only define `NODE_ENV` and `AOT` and all other environment variables are unmodified.

I could provide a pull request for a fix, please let know.

**Comment by gouravcoder** [comment]
@Hagendorn nice find!

**Comment by gdi2290** [comment]
@Hagendorn thanks! can you make a PR

**Comment by Hagendorn** [comment]
Oh the issued didn't close automatically with my PR. So I close it manually.
