### ISSUE TITLE
How does the todo's API works?

### ISSUE THREAD

**Issue by khex** [angular/universal-starter#292]
I have found some basic implementation of API in `src/backend/api.ts`, but how does it works?
GET to `http://localhost:3000/todos` returns an **404** error.

**Comment by MarkPieszak** [comment]
The GET route is `/api/todos`

You can see them all here [(in that backend/api.ts file)](https://github.com/angular/universal-starter/blob/master/src/backend/api.ts#L40-L106)

You can see it creating the route here:
```
import { serverApi, createTodoApi } from './backend/api';

// createToDoApi() just exports all the individual routes instead of putting all that 
// code in the server.ts file.

app.use('/api', createTodoApi()); 
```

**Comment by khex** [comment]
@MarkPieszak Thanks a lot and close this issue.
