### ISSUE TITLE
Input text bug in the demo app

### ISSUE THREAD

**Issue by jon301** [angular/universal-starter#294]
Hi,

I've just downloaded the starter kit and tried out the demo app.
There is a weird behavior concerning the input text :
- Focus the input and type something
- Now move the cursor at the beginning of the input and add some more text
- You'll notive that the cursor will automatically move to the end of the input  

![screen capture on 2016-12-03 at 09-56-11](https://cloud.githubusercontent.com/assets/122108/20858179/2c15c7c0-b93f-11e6-89b7-31efbcd7d925.gif)

Angular2 : v2.1.2
Angular2 Universal : v2.1.0-rc.1 

Thanks for your help

**Comment by MarkPieszak** [comment]
Hey @jon301, very strange! What Browser and version are you using by any chance?

**Comment by jon301** [comment]
Hi @MarkPieszak 

I see this bug on :
Google Chrome 55.0.2883.75 (64-bit)
Safari 10.0.1 (12602.2.14.0.7)

Works well on Firefox 50.0.2

OS : macOS Sierra 10.12.1 (16B2555)

**Comment by MarkPieszak** [comment]
Sounds good thank you, I'll look into it.
