### ISSUE TITLE
Can't to connect external angular2 component to starter application 

### ISSUE THREAD

**Issue by oleksmir** [angular/universal-starter#297]
When I try to connect external angular2 component from npm I have problems with export/import keywords.
Example with @nodeart/products-list-component from npm:

I got an error during starting server (compilation is okay):
`.../universal-starter/node_modules/@nodeart/products-list-component/index.ts:1 `
`(function (exports, require, module, __filename, __dirname) { export { ProductsListModule } from './src/products-list.module'; `
`SyntaxError: Unexpected token export`
I think  the reason is next: 'export' is not allowed word, because it us reserved by node.
Maybe it should be some conditions with isNode or isBrowser with angular2 universal to prevent node process this actions which generates those errors.

**Comment by MarkPieszak** [comment]
It looks like they might be transpiling only down to ES6?

**Comment by OlexMir** [comment]
I already have "target": "es5" in tsconfig.json

**Comment by nosovk** [comment]
It works in Angular-Starter project. I think trouble in that "module.exports" should be used in Node env. In my opinion the clue is in isomorphic usage of that component in Angular Universal.
Also there is a possibility that Angular Universal doesn't support not UMD components...
