### ISSUE TITLE
Support Angular 2.3

### ISSUE THREAD

**Issue by John0x** [angular/universal-starter#303]
Hello, are there any plans to soon support newer angular2 versions?
What problems are there currently which prevent switchting to 2.3 ?

**Comment by Koslun** [comment]
Believe universal uses a few private imports from angular modules which break in later versions as private variables in angular can change at any point in time. This at least led to this issue: https://github.com/angular/universal/issues/606.

Read in the [angular weekly meeting notes](https://docs.google.com/document/d/1rC5dz7AkCZP813daT_bccbS-20OLmXgBVi50CSKx148/pub) and heard at [angular air](https://angularair.com/) that the angular core team has recently taken over the project and have been moving parts to the angular repo, thus integrating it more with the angular release schedule.

Here's one issue to follow the progress of this move: https://github.com/angular/angular/issues/12495.

Really no clue of when they'll be done though, but given angular's support of semver I suppose it can't come any sooner than the next minor or major release. So at least won't be properly integrated in a stable release until after holidays then, but maybe in a beta or release candidate.

**Comment by gdi2290** [comment]
closing for https://github.com/angular/angular/issues/12495
