### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by John0x** [angular/universal-starter#304]
Hey, is there a specific reason that the component folders have a plus as the first character?
I thought that the + sign was intended only for lazy modules.

**Comment by MarkPieszak** [comment]
Typically (that's the way I use it), sometimes people use it to indicate just an NgModule as well. We might as well make that one lazy to stick with that concept though you're right.

**Comment by anorborg** [comment]
FYI, I asked about this for the naming convention in the docs and apparently its not recommended. Perhaps the convention should be removed:

https://github.com/angular/angular.io/issues/2944#issuecomment-266675249

**Comment by gdi2290** [comment]
it was a convention that Igor was pushing for in the past
