### ISSUE TITLE
Production build without AoT fails on browser

### ISSUE THREAD

**Issue by diestrin** [angular/universal-starter#309]
Steps to reproduce:
- Clone the repo
- Edit webpack.prod.config.ts
- Change line 18 `'process.env.AOT': true` to `'process.env.AOT': false`
- Change line 135 `entry: './src/client.aot',` to `entry: './src/client',`
- Change line 164 `entry: './src/server.aot',` to `entry: './src/server',`
- Run `npm run build:prod`
- Run `npm run server`
- Open http://localhost:3000/
![Console Error](https://api.monosnap.com/rpc/file/download?id=pirbPSeCtz6c773XnADNc4T0k2xSdY)

**Comment by MarkPieszak** [comment]
Did you run `npm run build:prod:ngc` ?

**Comment by diestrin** [comment]
No, I don't want to use AoT

**Comment by diestrin** [comment]
I'll close this, I found how to do it.
For those who want to know, just comment out all the `NormalModuleReplacementPlugin` in the `clientConfig`

**Comment by MarkPieszak** [comment]
Ahh glad to hear it! Yeah that removes duplicate things from the modules, wonder why it was affecting prod for you.

**Comment by diestrin** [comment]
I think that it makes sense to remove that when you're building for AoT, but for JiT those things are needed

**Comment by MarkPieszak** [comment]
Might be worth making that more conditional for the AoT scenario, you're right.
