### ISSUE TITLE
universal cache: all the same req url will not be sent

### ISSUE THREAD

**Issue by zwwtj2014** [angular/universal-starter#311]
hi,
    I try to use a UniversalCache  to save certain requests so they aren't re-ran again on the Client. And has a service like this:
```js
get(url) {
    let key = url;
    if (this._cache.has(key)) {
      return Observable.of(this._cache.get(key));
    }
    // you probably shouldn't .share() and you should write the correct logic
    return this._api.get(url)
      .do(json => {
        this._cache.set(key, json);
      });
  }
```
but **all http req will be cache in _cache map like {'url':'json'}, and same req url will not be sent.**
So I try to solve the problem, and Universal Cache use getWithCache, else will use method get:
```js
  get(url) {
    return this._api.get(url);
  }
  getWithCache(url) {
    let key = url;

    if (this._cache.has(key)) {
      return Observable.of(this._cache.get(key));
    }
    return this._api.get(url)
      .do(json => {
        this._cache.set(key, json);
      });
  }
```

---

But I feel it is Weird. Universal provides a better solution or any ideas?

**Comment by MarkPieszak** [comment]
You only want it to be Cached 1 time right? 
(Cache the server response, use it on that client that first time, then never again)

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/shared/cache/api.ts#L32-L35

I forgot I wanted to add these updates here for this reason. `autoClear` is set to true by default, but if there are some requests you just want cached permanently, just set it to false (3rd parameter) when calling this.

```
export class HttpCacheService {

    constructor(public _http: Http, public _cache: CacheService) { }

    get(url, options?: RequestOptionsArgs, autoClear: boolean = true) {

        // You want to return the cache if there is a response in it. 
        // This would cache the first response so if your API isn't idempotent you probably want to 
        // remove the item from the cache after you use it. LRU of 1 
        let key = url;

        if (this._cache.has(key)) {

            const cachedResponse = this._cache.get(key);

            // if autoClear is set to false, item will stay in cache until you manually clear it
            // ie: trigger CacheService.remove(url /* with the url/key used here */)

            if (autoClear) {
                // remove previous value automatically for now
                this._cache.remove(key);
            }

            return Observable.of(cachedResponse);
        }

        // note: you probably shouldn't .share() and you should write the correct logic

        return this._http.get(url, options)
            .map(res => res.json())
            .do(json => { this._cache.set(key, json); })
            .share();
    }
}
```

**Comment by zwwtj2014** [comment]
Thanks for your answer, and It is a good solution for Cached 1 time!
But I'm concerned about requests that do not need to use UniversalCache, like click a button and send get req.
```ts
// click re-render button
reRender(): void {
        // event.stopPropagation();
        const modelUrl = 'app/mocks-json/mock-model.json';
        this.reRenderService.get(modelUrl).subscribe(
            model => {
                 this.model = model;
            }
        );
    }
```
the http req should not be cached. So I think there should be two types of HTTP services: HttpCacheService for universalCache and HttpService for normal http requests above, or all reqs will be cached and remove according to the url if autoclear === true. Right?

---

PS: I read the code in your project aspnetcore-angular2-universal, HttpCacheService and ApiGatewayService were provided
