### ISSUE TITLE
Re-rendering when bootstraping at client for lazy routes

### ISSUE THREAD

**Issue by Junik** [angular/universal-starter#313]
Is there any way I can skip the second rendering? 
In this starter kit for "/lazy"  route it is also occur http://screencast.com/t/rZ1kgfGTI

**Comment by MarkPieszak** [comment]
Which second rendering, the client re-doing xhr?

**Comment by kuldeepkeshwar** [comment]
@Junik you can use cache service and preboot

**Comment by Junik** [comment]
http://screencast.com/t/c11oGwZm

**Comment by inzerceubytovani** [comment]
Still no progress here? I found also some tries to fix that in this issue - https://github.com/angular/universal-starter/issues/175 but I'm not sure it helps.

Until this will be not fixed, lazy loading is not very usable with universal.

**Comment by sadeghipour** [comment]
It could be useful
open browser.module.ts and find

RouterModule.forRoot([], { useHash: false, preloadingStrategy: IdlePreload }),

and just replace with

RouterModule.forRoot([], { useHash: false}),

https://alisch.me/post/Universal-Starter-%7C-Tips-and-Tricks
