### ISSUE TITLE
Should be able to run build:prod without :ngc

### ISSUE THREAD

**Issue by jongood01** [angular/universal-starter#316]
Running `npm run build:prod` gives the error because I'm not running ngc first:

```
ERROR in ./src/server.aot.ts
    Module not found: Error: Can't resolve './node.module.ngfactory' in '/path-to-my-app/my-app/src'
     @ ./src/server.aot.ts 21:30-64

    ERROR in [default]  /path-to-my-app/my-app/src/server.aot.ts:23:36
    Cannot find module './node.module.ngfactory'.
```

I tried setting: `'process.env.AOT': false` in webpack.prod.config.ts but that doesn't help and commenting out the code in the 2 files allows the build to run but when I run `node /dist/server/index.js` it exits with no errors.

Would be good to be able to build without AOT.

**Comment by gdi2290** [comment]
AoT is required for production since Angular becomes slower bootstrapping with more components otherwise
