### ISSUE TITLE
Static pre-render documentation?

### ISSUE THREAD

**Issue by sebastianmacias** [angular/universal-starter#318]
I need to pre-render certain routes for SEO purposes and host my universal app in a static host (no node.js server will be running). I have been looking all over and can't find any info that can point me in the right direction.

How can this be achieved?

Thanks

**Comment by gdi2290** [comment]
yes, https://www.npmjs.com/package/angular2-universal-render but also should be supported in ng4
https://github.com/angular/angular/issues/13822

**Comment by jonasdk** [comment]
@sebastianmacias 
Did the above solve you issues? I am in a similar situation where we are not sure what to do. Since we want to have the app prerendered, but it seems stuck somewhere between a old version and waiting for Angular 4 to have it included. 
Best,

**Comment by webmutation** [comment]
Not sure how this fixes the issue... since this requires to manually render every route.
