### ISSUE TITLE
Lazy laoding ReferenceError: System is not defined

### ISSUE THREAD

**Issue by goriunov** [angular/universal-starter#323]
I got this error with Universal cli how can i fix that , i tried fix from https://github.com/devCrossNet/universal-cli/issues/20 but it did not work for me it displays the same stuff

**Comment by djabif** [comment]
I'm facing the same issue. Did you solve it?

**Comment by nicky-lenaers** [comment]
I had a similar issue before. Make sure you have ``src/typings.d.ts``. This is where definitions for ``System`` are defined.

**Comment by paulogr** [comment]
Same issue here, anyone solve it?

**Comment by gdi2290** [comment]
make sure you include typings.d.ts
