### ISSUE TITLE
Deploy to Heroku: rimraf not found

### ISSUE THREAD

**Issue by UrbanCondor** [angular/universal-starter#324]
If I click the "Deploy to Heroku" button and successfully deploy universal-starter to my Heroku instance, the app won't start. If I look in the logs, I see there is an error "sh: 1: rimraf: not found". Is there a fix for this?

![image](https://cloud.githubusercontent.com/assets/18430094/21736723/bec99c7a-d4ad-11e6-9d5c-106125de29cb.png)

**Comment by MarkPieszak** [comment]
Can you try npm installing rimraf there and giving it a shot?

**Comment by UrbanCondor** [comment]
I retraced my steps and I'm not getting the same error anymore. Strange. 

Thanks for the advice regardless!
