### ISSUE TITLE
rendering content based on current domain

### ISSUE THREAD

**Issue by tyanthoney14** [angular/universal-starter#327]
Is there currently any way to make a domain specific request for content for Angular Universal. 

The situation is we have a single application where the content changes depending on the domain. We currently are hosting the site through Heroku and have all of our DBA's pointing to the same application.  I need to change the site copy for each domain we own and the back end request uses the site domain multiple times in the request url. I am currently struggling with finding out how to grab the domain to be able to make a logical decision about where to grab the copy. I apologize if this is not the venue for this question I have not had any luck solving this problem up to this point.

**Comment by MarkPieszak** [comment]
Were you able to handle it in Node, and render the correct application from there then?

**Comment by tyanthoney14** [comment]
No sir I just thought that an issue was not the appropriate place for my
question.
