### ISSUE TITLE
Get rid of __workaround(s)

### ISSUE THREAD

**Issue by matiishyn** [angular/universal-starter#328]
Hey guys.
First of all, I'd like to thank you for the great project! Personally I think that **`${JSframeworkName}Universal`** should be the future of SPAs

We are planning to use this starter for rewriting our existing Angular1.x project. But I can see some `__workaround...` files that contain temporary fixes:

> THIS IS TEMPORARY TO PATCH 2.1.1+ Core bugs

As I can see there are already newer versions of `@angular/...` and other modules.
So, my question is, can we update dependencies and get rid of those __workaround(s)?

Thank you for help!
Ivan

**Comment by MarkPieszak** [comment]
Hey there @matiishyn 
The workarounds are needed to use 2.1.1+ and there are some issues with using Universal with higher than 2.2+. Currently universal is moving to Angular Core which will fix and prevent issues like this from appearing in future releases of angular as they will always be in sync. For now, leave the, in there temporarily and when 4.x comes out we should be able to remove them and update the repo to reflect any API changes.

**Comment by matiishyn** [comment]
thank you @MarkPieszak 
it's nice to hear that.
thank you for your support
