### ISSUE TITLE
Updating to  Angular 4.0.0-beta3/2.4.3

### ISSUE THREAD

**Issue by Shiroh1ge** [angular/universal-starter#329]
So I'm trying to update my Angular version + rxjs and zone, but I'm getting dep errors.

```
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN angular2-universal-polyfills@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
```
If I install v0.6.21 of zone.js then I get:
`npm WARN @angular/core@2.4.3 requires a peer of zone.js@^0.7.2 but none was installed.`
Is there a workaround about this? I'm using the Universal Starter without any changes to it.

**Comment by MarkPieszak** [comment]
At the moment you want to stick with `2.1.2` until Universal's serialization engine is moved into Angular Core then everything will re-align.

**Comment by Shiroh1ge** [comment]
Will do! Thanks for the quick response!

**Comment by MarkPieszak** [comment]
Not a problem, things will get better in the months to come :+1:

**Comment by tskweres** [comment]
So what should my package.json look like to get this working out of the box? I cloned the repo and just tried npm installing from the instructions and I'm getting the dependency errors :(

**Comment by MarkPieszak** [comment]
Errors or warnings? @tskweres Warnings are ok

**Comment by tskweres** [comment]
@MarkPieszak agreed, I eventually get this error on ng serve

https://github.com/devCrossNet/universal-cli/issues/60#issuecomment-277191558

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
