### ISSUE TITLE
A way to determine the end of "state 0"

### ISSUE THREAD

**Issue by samvloeberghs** [angular/universal-starter#33]
Hello,

Is there a way or a flag to set to determine when the initial state ( the one that should be prerendered ) is complete? Let's assume the following usecase:

1. I have an app that consistst of 1 main component and 1 route with a component
2. The route component does an async http call to a backend API
3. The component for that route has several child components / directives
4. The result from the asycn API call needs to be passed into the several child components and rendered

After all this, the "state zero" should be rendered.

How to achieve this? Is there something on the roadmap to accomplish this?

Grtz!

**Comment by manekinekko** [comment]
@samvloeberghs could you give a real world example for this use case?

**Comment by mikkeldamm** [comment]
@samvloeberghs if I understand you correctly, you then want to make a http call from a parent component to get data and make child components use that data for rendering - and you want that to happen in the server side rendering.

I have done the above by making the http call in the [OnActivate](https://angular.io/docs/ts/latest/api/router/OnActivate-interface.html) interface implementation on the parent component, in that way the rendering of the children will wait until that promise is fulfilled.

Here is an example:
```
routerOnActivate(next: ComponentInstruction, prev: ComponentInstruction) {
    return new Promise((resolve, reject) => {
        this.http.get("some-url").subscribe(
            response => {
                this.dataForChildren = response.data;
                resolve();
            }, 
            error => {
                reject();
            }
        }
    }
}
```

**Comment by gdi2290** [comment]
http calls are tracked, can you try to do this in the repo again

**Comment by gdi2290** [comment]
I'm going to close this for now to keep the issues down but feel free to reopen it
