### ISSUE TITLE
Communicating between client and server

### ISSUE THREAD

**Issue by afganhalbana** [angular/universal-starter#332]
Hi guys, as i havent seen any proper examples and documentations about how to communicate the client and the server. My problem is i get a route which need user to authenticate first and  i use canactive for that. The problem occurs if user type the route url on the browser, the routes show the protected route which supposed not to and the view seems serve the correct page (in this case i redirect the user to the login page). Obviously this happens because the server give access to the route while the client not. So as a workaround i list the protected route and use the middleware to protect the route. How could i achieve this, so basically my client call the api from the same server like the todos api then calling another api to authenticate the user then i store the data in order to authenticate the routing on the server. So the question, is this a good example to do that so or are there any options like the DI things or the cookie parser that i hard to find the documentation about to communicate between client and server.

**Comment by nacimux** [comment]
I olso would like to see a real work exemple with connection to database, communication between client and server.
