### ISSUE TITLE
How to use Router Events in Universal Starter?

### ISSUE THREAD

**Issue by zmnv** [angular/universal-starter#335]
In original Angular 2, there are methods to scroll page up after click routerLink (router event?). 

**app.component.ts**

```
export class AppComponent implements OnInit {

  title="app component";

  constructor(
    private router: Router,
  ) {}

  ngOnInit() {
    this.router.events.filter(event => event instanceof NavigationEnd).subscribe(event => {
      window.scroll(0, 0);
    });
  }
}
```

But in Universal Starter It makes error

`Error: Can't set headers after they are sent.  at SendStream.headersAlreadySent ...`

As I understand, router events places anywhere else? Which file I can change? 
How to add scroll page after routing?

**Comment by MarkPieszak** [comment]
Are you responding twice from Express, with either a return or two next() happening?
Also make sure that yin conditionally wrap window, with isBrowser. https://github.com/angular/universal#universal-gotchas
   
      if (isBrowser)

**Comment by zmnv** [comment]
@MarkPieszak I want to just make scroll up after router link click. And that "scroll up" must scrolling ONLY when user clicked link.

### HALF-SOLVED
This solution with your advice works correctly, but it scroll up not only by clicked link, also by page opened by direct url (e.g. http://localhost:3000/home)

app.component.ts

```
export class AppComponent implements OnInit {

  title="app component";

  constructor(
    private router: Router,
  ) {}

  ngOnInit() {
    if (isBrowser) {
      this.router.events.subscribe(path => {
        var scrollToTop = window.setInterval(function () {
          var pos = window.pageYOffset;
          if (pos > 0) {
            window.scrollTo(0, pos - 20); // how far to scroll on each step
          } else {
            window.clearInterval(scrollToTop);
          }
        }, 16); // how fast to scroll (this equals roughly 60 fps)
      });
    }
  }

}
```

According that I have a question. How to modify that code to scroll up ONLY when user clicked by <a routerLink....>? How it works in actual version (master) of universal starter? 

Hmmm, sorry if this is beyond the scope of universe starter.

**Comment by zmnv** [comment]
Just use 

```
    if (isBrowser) {
      this.router.events.subscribe(path => {
        var scrollToTop = window.setInterval(function () {
          var pos = window.pageYOffset;
          if (pos > 0) {
            window.scrollTo(0, pos - 20); // how far to scroll on each step
          } else {
            window.clearInterval(scrollToTop);
          }
        }, 16); // how fast to scroll (this equals roughly 60 fps)
      });
    }
```

in each component where you want to scroll up by routing, and don't use where you don't want.

Of use code inside `this.router.events.subscribe` as (click)="yourFunction" with setTimeout 1...20ms.
