### ISSUE TITLE
[resolved] Using custom Material Design. Augmented DOM effects are not applied after change page by routing

### ISSUE THREAD

**Issue by zmnv** [angular/universal-starter#336]
Hello. 

Try to picrure. I have a .js (material-design-light) script, which adds some derectives and DOM elements into elements with class="someclass". 

When I go to some page by direct url (localhost:3000/home) or reload that page by F5 it works.

For example, I write code
```
<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" >
   SOME TEXT
</button>
```

Browser changes it into a code
```
<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" mdl-lalal="lalala">
   <span class="lalalala lala">SOME TEXT</span>
   ....
</button>
```
All right, that's what I want.

But when a click to `<a routeLink="someroute">link</a>`, I see only first code, which I just wrote. Browser doesnt change it to code which I want.

I tryed to google, found that by [that issue](https://github.com/cmelion/generator-ng2-webpack/wiki/Working-with-Material-Design-Lite):
```
    ngAfterViewInit() {
        // Ensure material-design-lite effects are applied
        componentHandler.upgradeDom();
    }
```

but in my code it doesnt work, because `componentHandler` is unknown (tryed to import .js library with that function in client.ts — `import 'material-design-lite/src/mdlComponentHandler.js';`

I think, the problem is:
1. Routing uses cache without .js effects ?
2. I doing something wrong.

Can you describe how to resolve that problem, please? In short, I want to apply (by .js) effects after click by routeLink.

**Comment by zmnv** [comment]
Live example: 

Chaning DOM is worked if I paste that <button> outside the router-outlet.
```
<button class="mdl-button mdl-js-button mdl-js-ripple-effect" data-upgraded=",MaterialButton,MaterialRipple">
    SOME TEXT
   <span class="mdl-button__ripple-container">
      <span class="mdl-ripple is-animating" style="width: 246.737px; height: 246.737px; transform: translate(-50%, -50%) translate(58px, 15px);"></span>
   </span>
</button>
```

But in router-outlet, happens nothing.

```
<button mdly-button="" class="mdl-button mdl-js-button mdl-js-ripple-effect">
   SOME TEXT
</button>
```

But if I press F5, its worked. But when I click routerLink, it doesnt work until I press F5 again.

**Comment by zmnv** [comment]
### SOLVED

1. install **material-design-lite** by npm and `import material-design-lite/material.js` in client.ts

OR just include in <head></head> (in index.html) 
`<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>`

OR any import which you like.


2. Create file **MaterialDesignLiteUpgradeElement.ts** in folder **/+app/shared/**
```
import { Directive, AfterViewInit } from '@angular/core';
import { isBrowser } from 'angular2-universal';
declare var componentHandler: any;

@Directive({
  selector: '[mdl]'
})
export class MDL implements AfterViewInit {
  ngAfterViewInit() {
    if(isBrowser) {
      componentHandler.upgradeAllRegistered();
    }
  }
}
```


3. Include derective MDL in /+app/shared/shared.module.ts
```
import { MDL } from '../MaterialDesignLiteUpgradeElement';
....
const COMPONENTS = [
  // put shared components here
  MDL,
  // your other components
];
```


4. In your any component html file (e.g. home.component.html) use **mdl** directive in main element
```
<div mdl>
   <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">TEXT</button>
</div>
```

I recommend you use the directives instead long class
`class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"`. 

For example

**your-custom-directive.ts**
```
import {
  Component, Directive, ElementRef, Renderer,
} from '@angular/core';

@Directive({
  selector: '[mdly-button]'
})
export class MdlButtonDirective {
  constructor(element: ElementRef, renderer: Renderer) {
    renderer.setElementClass(element.nativeElement, 'mdl-button', true);
    renderer.setElementClass(element.nativeElement, 'mdl-js-button', true);
    renderer.setElementClass(element.nativeElement, 'mdl-js-ripple-effect', true);
  }
}
```

**Comment by MarkPieszak** [comment]
Thanks for posting how you solve any issues you face, helps others who might run into the same thing!
