### ISSUE TITLE
Production-ready code: minify without AoT

### ISSUE THREAD

**Issue by matiishyn** [angular/universal-starter#337]
Hi guys,

We have written a small website using the `universal-starter` template. And now we are trying to produce production-ready code.

I've tried the `build:prod:ngc` command which runs AOT, but it doesn't work because of some problems with SASS, ng2-translate, others...

So, I was thinking, maybe we can just minify code without AOT, and it'd be enough for us. 

And here are my questions:

1. what is the preferable way to produce production-ready code? AOT only? or can we use just minification?
2. if it's possible to go without AOT and just minification, can you please give me a hint how to do that

Thank you in advance for help!

**Comment by zmnv** [comment]
@matiishyn did you resolve that issue?

Or anybody else?

**Comment by matiishyn** [comment]
hi @zmnv 
No, I didn't manage to fix AoT issues
