### ISSUE TITLE
Is using Universal a good idea if you are planning to make big application?

### ISSUE THREAD

**Issue by FahadMullaji** [angular/universal-starter#339]
Hey guys,

Whenever I add new pages in my application then it gets compiled into index.js.
Of course, it uses webpack to minify the code but till what extent would it do?

What if I want to have around 1000 pages in my application then size of index.js will get into MBs and as this gets loaded at the time of initialization of application then it will take so much time for loading the application.

How would you deal with this problem? Split index.js? but on what basis? and which part to load when? and how?

Thanks
Fahad Mullaji

**Comment by flauc** [comment]
Hi @FahadMullaji,

There is an example on this repo of how to use LazyLoaded modules. This does exactly what you need, it splits the main.js file in to chunks and takes care of loading them when they are required (when the route connectect to the module is visited).

**Comment by StefanRein** [comment]
But why you need to use then two Module Loaders.. SystemJS and Webpack..?!
Wasn't this fixed in later angular versions? But the repo uses older ones.
