### ISSUE TITLE
[How-to] Jquery plugin - Add Swiped Carousel and other plugins

### ISSUE THREAD

**Issue by zmnv** [angular/universal-starter#341]
Trying to use animation from inside of other functions in component by `this.togglestates("goHide");`. 
Tryed to use ViewEncapsulation.None also, or without it. No animation. 

```
imports ...

@Component({
  changeDetection: ChangeDetectionStrategy.Default,
  encapsulation: ViewEncapsulation.Emulated,
  selector: 'layer-discount',
  templateUrl: './discount.component.html',
  animations: [
    trigger('visibilityChanged', [
      state('shown' , style({ opacity: 1 })),
      state('hidden', style({ opacity: 0 })),
      transition('* => *', animate('.4s'))
    ])
  ]
})

export class DiscountComponent implements OnInit { 

state: string ='show';

 togglestates(STATE) {
    if(STATE == 'goShow') {
      setTimeout(function(){
        this.state = 'show';
      }, 800);
    }
    if(STATE == 'goHide') {
      setTimeout(function(){
        this.state = 'hidden';
      }, 800);
    }
  }

}
```

html:

```
    <div [@visibilityChanged]="state">
      <h3>{{nigma.text}}</h3>
    </div>
```

**Comment by zmnv** [comment]
two weeks of my life was for nothing. 

jquery sliders doesn't works because 

```
    if(isBrowser) {
      $(document).ready(function(){

        $('.owl-carousel').owlCarousel();
      });
    }
```
compiler not understand owlCarousel and get error, stackoverflow solutions and other google is for usual Angular 2 ........ okay. 

angular 2 page slider doesnt work also because there is no support to 'divectives' in components...

i'm dead.

**Comment by MarkPieszak** [comment]
Animations should work (on the browser side at least), you're not talking about hitting F5 and it running the animations from the server-rendered view right? Because those won't get triggered.

Here's an example of basic animations [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/containers/rest-test/rest-test.component.ts#L12-L25)

As for jQuery, do you have it set up properly? I need to make sure I add the Gotcha to the seconds here & in the Universal repo. They're more up-to-date [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal#how-can-i-use-jquery-andor-some-jquery-plugins-with-angular-universal)

But to use jQuery, and jQuery plugins, it has to be setup differently:

The gist is, you need to import the plugin in your main-client.ts only, jQuery must be added as a Plugin for webpack so it's global, and you need to `import * as $ from 'jquery';` at the top of your component to use jQuery in general within it. Then just wrap it in `if (isBrowser) { $('.owl-carousel').owlCarousel(); }` and that should do the trick!

---

> How can I use jQuery and/or some jQuery plugins with Angular Universal?

Note: If at all possible, try to avoid using jQuery or libraries dependent on it, as there are better, more abstract ways of dealing with the DOM in Angular (2+) such as using the Renderer, etc.
Yes, of course but there are a few things you need to setup before doing this. First, make sure jQuery is included in webpack vendor file, and that you have a webpack Plugin setup for it. new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' })

Now, make sure any "plugins" etc that you have, are only included in your **main-client.ts** file. (**ie: import 'slick-carousel';**) In a Component you want to use jQuery, make sure to import it near the top like so:

`import * as $ from 'jquery';`
Always make sure to wrap anything jQuery oriented in Universal's isBrowser conditional!

**Comment by zmnv** [comment]
@MarkPieszak 

**webpack.config.ts**
```
export var commonPlugins = [
  ....
  new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' })
];
```

**client.ts**
```
// the polyfills must be the first thing imported
import 'angular2-universal-polyfills';
import 'ts-helpers';
import './__workaround.browser'; // temporary until 2.1.1 things are patched in Core

import * as $ from 'jquery'
import 'owl.carousel';
...
```

carousel.component.ts
```
import { Component, OnInit } from '@angular/core';
import { isBrowser } from 'angular2-universal';

import * as $ from 'jquery';

@Component({
  changeDetection: ChangeDetectionStrategy.Default,
  encapsulation: ViewEncapsulation.Emulated,
  selector: 'slider',
  templateUrl: './carousel.component.html',
})
export class CarouselComponent implements OnInit {
  ngOnInit() {
    if (isBrowser) { $('.owl-carousel').owlCarousel(); }
  }
}
```

Compiler returns
`**Property 'owlCarousel' does not exist on type 'JQuery'.**`

Okay. Then I fount folder **typings** and file **index.d.ts** inside. Add:
```
/// <reference path="globals/jquery/index.d.ts" />
interface JQuery {
  owlCarousel():void;
}
```
And there is no error in compiler. But in browser in console I see
`**EXCEPTION: $(...).owlCarousel is not a function**`


I use pack of **universal-starter master**

**Comment by MarkPieszak** [comment]
Let me try and take a look tomorrow and see why it's not working, looks fine to me at least, hmm.

**Comment by zmnv** [comment]
@MarkPieszak no problem :) just try to include [OwlCarousel2](https://github.com/OwlCarousel2/OwlCarousel2) in **master** pack of universal-starter. I still think I'm include owl wrong. Because there are so many contradictory information about how to fix that problems in internet. It would be nice if the developer of angular-universal tried to do it, and gave an example or repository. Because this is not only for owl, It's for all jQuery plugins as well.

Now I try to "carousel" with typescript functions and angular 2 animations. I had to use jquery because ng2-...-slider or other angular 2 components doesnt works ( or probably I'm stupid :) ) because of 'directives: [ ... ]'.

------------------

PS: however, jQuery works fine. $('.blabla').click() works. Also all scripts and .js plugins works if I include they in index.html as <script src="...">. First seconds of loading page in http://localhost plugins are work! but after some second it disapear (because of components loading).

**Comment by MarkPieszak** [comment]
Maybe try adding a delay in there after the isBrowser?

You're right there's a lot of mixed info out there.

    if (isBrowser) {
        setTimeout(() => {
             $('.owl-carousel').owlCarousel();
        }, 1000);
     }

Also if you use a library like **[ng2-bootstrap](https://valor-software.com/ng2-bootstrap/)**, it not only has a Carousel (https://valor-software.com/ng2-bootstrap/#/carousel), but it works with Universal!
Just avoid using jQuery all together :) Look at their docs on how to get it set up with your NgModule, it's very easy!

Just install version `"ng2-bootstrap": "1.1.16",` as the *newest* version requires Angular 2.4.x (which Universal isn't compatible with yet).

**Comment by zmnv** [comment]
@MarkPieszak 

1. `npm install --save ng2-bootstrap `
2. in some .json file or anywhere change vesrion to 1.1.16 ? 

or there are other method to install older version thike ng2-bootstrap@1.1.16 ? sorry for dumb question, I just want to describe full solution for other people.

**Comment by zmnv** [comment]
@MarkPieszak thanks, ng2-bootstrap woks. But there is no animation by changing slides in that version. Animation — is a most important part. It makes no sense to use that carousel without transition animation. 

:(

**Comment by MarkPieszak** [comment]
Yeah I think they just leave that up to you! Glad you got it working 👍🎁

**Comment by zmnv** [comment]
@MarkPieszak sorry, problem not solved. It's not a solution to use old version ng2-bootstrap without animations. need to use owl (and other plugins) from jQuery.

**Comment by zmnv** [comment]
@MarkPieszak it's question also about SHARE buttons like fb, vk end etc.

Share services also uses .js files and functions to replace DOM elements to paste icons and links. That important question.

**Comment by MarkPieszak** [comment]
Can you mark an issue on their page to see if they have any option for swipe capability, or could point you in the right direction? I know there is hammerjs, but maybe they know of other good & easy options.

**Comment by zmnv** [comment]
@MarkPieszak It's also hasnt dragable slide horizontal by mouse.

Ha ha, how can I use hammer js, if hammer js is an external library and had same error which other problems from this issue? 

Anyway, did you try include jquery modules (or just js functuon from external js) in master package of that repository?

**Comment by zmnv** [comment]
**[SOLVED]**

One more example. Using carousel swiper — [Swiper (getting starter)](http://idangero.us/swiper/get-started/#.WI0l81OLSwU). 

0. You can use jQuery or not. Just read getting starter and choose method. If you want to use It with jQuery, read [that issue](https://github.com/angular/universal-starter/issues/334) #334 

1. ` npm install swiper`

2. /src/**client.ts**

```
// the polyfills must be the first thing imported
import 'angular2-universal-polyfills';
import 'ts-helpers';
import './__workaround.browser'; // temporary until 2.1.1 things are patched in Core

import 'swiper'; // !!!!!!!!!!!

// Angular 2
import { enableProdMode } from '@angular/core';
import { platformUniversalDynamic } from 'angular2-universal/browser';
import { bootloader } from '@angularclass/bootloader';
.....
```

3. any.component.ts

```
import { Component, ChangeDetectionStrategy, ViewEncapsulation } from '@angular/core';

import { isBrowser } from 'angular2-universal';

import * as $ from 'jquery'; // ADD THIS to include jQuery
declare var Swiper:any; // ADD THIS

@Component({
  changeDetection: ChangeDetectionStrategy.Default,
  encapsulation: ViewEncapsulation.Emulated,
  selector: 'any',
  templateUrl: './any.component.html',
})
export class AnyComponent {

  constructor() {

    // we need the data synchronously for the client to set the server response
    // we create another method so we have more control for testing
    this.universalInit();
  }


  universalInit() {

    if(isBrowser) {
      $(document).ready(function () {
        //initialize swiper when document ready
        var mySwiper = new Swiper ('.swiper-container', {
          // Optional parameters
          direction: 'vertical',
          loop: true
        })
      });
    }

  }

}
```

**Comment by zmnv** [comment]
@MarkPieszak How about import .js files (plugins) ? It's still the problem, which I described on previous post.
