### ISSUE TITLE
Server.ts is not loading custom node_modules

### ISSUE THREAD

**Issue by jindalrohit** [angular/universal-starter#343]
server.ts is not loading my custom node modules while I used **require('mymodule')**. It loads my node module with relative path **require('./node_modules/mymodule')**.
Below is my directory structure 
- src
  +node_modules - my custom node_modules.
  - server.ts
How can i fix this issue?

**Comment by MarkPieszak** [comment]
If you don't put a path `./` `../` etc, it assumed it's within `node_modules` folder.
Is it in your normal directory? Just use those to get to the correct location if so.

**Comment by jindalrohit** [comment]
This folder structure works if I use **server.js** file instead of server.ts file but here i am using angular universal. Is there any way that i can convert this file into ES5 without using webpack or babel means manually?
**And Node.js work like this :** 

If the module identifier passed to require() is not a core module, and does not begin with '/', '../', or './', then Node.js starts at the parent directory of the current module, and adds /node_modules, and attempts to load the module from that location. Node will not append node_modules to a path already ending in node_modules.

If it is not found there, then it moves to the parent directory, and so on, until the root of the file system is reached.

**Comment by MarkPieszak** [comment]
You could run tsc to just compile it real quick for you? Just point to it directly.
