### ISSUE TITLE
Webpack DLL

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#344]
Thanks for the great repo @gdi2290 👍 

This isn't really an issue just a question. Is there a reason why Webpack DLL isn't implement in this library, is there a conflict with universal or something along thous lines? 

I'd like to go ahead and implement it on my fork but I'm not sure if it might be incomparable.

**Comment by MarkPieszak** [comment]
Webpack DLL won't be a problem, go for it! This repo was originally just more of a minimal starter (mainly to just show the gist of how Universal works with Express) but I'm sure an addition like that would be very helpful!

**Comment by flauc** [comment]
Got it, thank you 👍
