### ISSUE TITLE
Using universal with nginx

### ISSUE THREAD

**Issue by Dralac** [angular/universal-starter#346]
Hi,

Not sure if a bug, but I guess this is general question about running universal in production with nginx.

Is there any guideline how to make this repo works with nginx server?

When I'm using it in localhost, after opening source code, I can see everything is rendered on server side and work as supposed to. Of course no middleware server, everything is out of box.

But after I put that on server and set proxy on nginx, the only thing that renders is Browser view. When I open the source code for page, I can only see my index.html without anything else rendered there.

I'd like to mention I'm running ng2-rc4, but not sure if that's related with the issue.

Any help would be appreciated.

**Comment by Koslun** [comment]
ng2-rc4 means you're using version rc4 of Angular 2? I would not expect that to work at all with the latest universal version. Especially considering the big breaking change in rc5 with the introduction of ngModules which also triggered a big rewrite of universal.

You in fact can more or less only run the versions used in this starter. I.e. version ~2.1.2 of regular core angular libraries together with version ~2.1.0-rc.1 of angular universal. Though, as mentioned in other posts, this is planned to change for version 4.0 of angular, see https://github.com/angular/angular/issues/13822

We got an nginx reverse proxy working with a project highly influenced by this starter. So can at least say that it is something that is possible with current version of angular universal.

**Comment by Dralac** [comment]
Hi @Koslun @MarkPieszak 

Yes, it's angular 2 RC4, but the project is using this (universal-starter) repo at the point it was shipped with ng2-rc4. Our code has never been updated to (universal-starter) RC5 (or higher) that introduces modules. We started with RC4 release and the code is based on it since now.

I stumbled on this issue, since I inherited a plenty of code already written for project and just had to deploy it on server. 

So, as I mentioned, everything works in localhost as expected, but when I put it on server with pm2 and nginx, I'm facing the issue that server side is not rendering app at all. That's something that confuses me, why it's not acting the same on both sides (as in localhost).

Thank you for your attention.

**Comment by Koslun** [comment]
@Dralac Although I was following the project at the time, I was not actively using it and I don't know much more than that it was seemingly working but underwent a big overhaul post RC5. I would imagine there being a lot less users for that version and for a lot shorter period of time. So I can imagine any number of bugs existing. My recommendation would definitely be to consider updating once they merge the universal stuff into angular 4.

Maybe first try the same production setup but using the latest version of this starter? Could then maybe confirm that it's not something with your production configuration.

**Comment by MarkPieszak** [comment]
I agree with @Koslun is there anyway you can try just doing a fresh repo and just trying to see if that works with any success when you push it up?

I'm not sure how nginx could be affecting that older version, what version of Universal is that one on?

**Comment by Dralac** [comment]
Hi guys, 

thanks for help, I tested it with the latest universal-starter repo and it works as supposed.
After digging a bit deeper why's that, I found out the issue.

So, when I was developing in localhost I was using local API and it was pretty fast so everything gets rendered in no time. But when code is on the server and using external API to grab some data, application initialises before I get data from API.
After data is ready, server view doesn't update.

I'm just curios if this is how universal works, so it's not updating server view from Promise after component is initialized, just client?

**Comment by gomesNazareth** [comment]
@Dralac  Did you manage to run angular universal on an nginx server ? . I am currently facing the same problem . Tying to run angular universal in production on an nginx server .

**Comment by Dralac** [comment]
@gomesNazareth Yes, I fixed the issue I had, but it was related with API and old version of angular-universal I had. 
Let us know what's the issue you are facing to, so we might can help.

**Comment by gomesNazareth** [comment]
@dralac  Actually  i have built  an angular2 app  and running it using  an nginx server.  Now  for the purpose  on seo i have to implement angular universal. But i got to know  that  angular universal needs to be  serviced  only using  a node server.  But i need it to run on an nginx server  . This  actually  is my problem

**Comment by Dralac** [comment]
@gomesNazareth I think it's not possible yet to run it directly on nginx. I had to install nodejs as well, and then just use nginx as proxy.

**Comment by zuhrulumam** [comment]
@Dralac sorry to bother you, i got connection refused error when using angular universal with nginx as proxy, did you know how to solve it?

**Comment by Dralac** [comment]
@zuhrulumam Not really sure what could be the issue, but I can share with you my nginx setup for specific domain, it might be helpful to you.

```
server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  mywebsitedomain.com;
    
    location / {
        root         /usr/share/nginx/html;    
        proxy_pass http://127.0.0.1:3000;       // ${IP nodjs running on} : ${port}
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**Comment by sivabudh** [comment]
Interesting. Would be very interested to see how this plays out. I too also use NGINX to serve my Angular app. And interested in trying out Angular Universal for SEO. Bummer that Angular Universal only works with Node.
