### ISSUE TITLE
Rendered HTML minification

### ISSUE THREAD

**Issue by kevinvella** [angular/universal-starter#347]
Hi,

I have a site that is going to be in production soon. Universal is working well, but the generated HTML is not minified.

I noticed in the server.ts file that there is a plugin "compression". Is this supposed to minify the HTML that is generated.

PS: In the generated HTML there are many styles.

Could you please suggest if i am missing something.

Thanks
Regards
Kevin

**Comment by kevinvella** [comment]
Hi,

I've used express-minify-html to minfiy the output

**Comment by crebuh** [comment]
@kevinvella 

do you have a code snippet how you integrated the express-minify-html plugin?

**Comment by kevinvella** [comment]
@crebuh Yes sure :)

var minifyHTML = require('express-minify-html');

app.use(minifyHTML({
    override:      true,
    exception_url: false,
    htmlMinifier: {
        removeComments:            true,
        collapseWhitespace:        true,
        collapseBooleanAttributes: true,
        removeAttributeQuotes:     true,
        removeEmptyAttributes:     true,
        minifyJS:                  true,
        minifyCSS:                 true
    }
}));

**Comment by crebuh** [comment]
@kevinvella 

big thx for the fast reply, it is working but now the app is rendered even slower on the server side :laughing:

**Comment by kevinvella** [comment]
@crebuh Ahh ic :/

**Comment by quangpdt** [comment]
The solution from @kevinvella did the job but it increased the server response time a lot. So I decided to go with CloudFlare and use their minify tools for all JS, CSS and HTML

**Comment by RigaNik** [comment]
I've installed express-minify-html and included it in server.ts as @kevinvella said. When I go with `npm run build:server:prod && npm run build:browser:prod` it builds fine, but as soon as I try to run the server it throws me an error.
`Error: Cannot find module '../lib/utils.js' ` in dist/server.js

It looks like the problem exists only if I try to use express-minify-html. Error is thrown in this part

```
var UglifyJS = exports;
var FILES = UglifyJS.FILES = [
    "../lib/utils.js",
    "../lib/ast.js",
    "../lib/parse.js",
    "../lib/transform.js",
    "../lib/scope.js",
    "../lib/output.js",
    "../lib/compress.js",
    "../lib/sourcemap.js",
    "../lib/mozilla-ast.js",
    "../lib/propmangle.js",
    "../lib/minify.js",
    "./exports.js",
].map(function(file){
    return /*require.resolve*/(__webpack_require__(462).resolve(file));
});
```

anyone had similar problem?

**Comment by RigaNik** [comment]
For anyone else having the same problem as I did, I managed to solve it by forking express-minify-html and html-minifier and changing parser for html-minifier to Terser instead of uglifyJS. That worked for me.

**Comment by bmarti44** [comment]
To get minification to work, I did something similar, but I used https://www.npmjs.com/package/patch-package to patch the `html-minifier` package to use `terser` instead of `uglify-js`.

That being said, it painfully slows down the server response time (about 5 seconds in my case, I'm sure whatever options you pick will have different results). Ultimately it will probably be faster to implement a regex to do this (not ideal at all).

**Comment by kuncevic** [comment]
Here is my code:

import { enableProdMode } from '@angular/core';
import { ngExpressEngine } from '@nguniversal/express-engine';
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
import * as bodyParser from 'body-parser';
import * as compression from 'compression';
import * as cors from 'cors';
import * as express from 'express';
import 'reflect-metadata';
import 'zone.js/dist/zone-node';

const minifyHTML = require('express-minify-html');

enableProdMode();

export const app = express();

app.use(compression());
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.use(
  minifyHTML({
    override: true,
    exception_url: false,
    htmlMinifier: {
      removeComments: true,
      collapseWhitespace: true,
      collapseBooleanAttributes: true,
      removeAttributeQuotes: true,
      removeEmptyAttributes: true,
      minifyJS: true,
      minifyCSS: true
    }
  })
);

// const DIST_FOLDER = join(process.cwd(), 'dist');

const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/server/main');

app.engine(
  'html',
  ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [provideModuleMap(LAZY_MODULE_MAP)]
  })
);

app.set('view engine', 'html');
app.set('views', './dist/browser');

app.get('/redirect/**', (req, res) => {
  const location = req.url.substring(10);
  res.redirect(301, location);
});

app.get(
  '*.*',
  express.static('./dist/browser', {
    maxAge: '1y'
  })
);

app.get('/*', (req, res) => {
  res.render('index', { req, res }, (err, html) => {
    if (html) {
      res.send(html);
    } else {
      console.error(err);
      res.send(err);
    }
  });
});

minifyHTML does not take any effect, any thoughts?
