### ISSUE TITLE
Example is not work

### ISSUE THREAD

**Issue by wasteCleaner** [angular/universal-starter#349]
Hello!
2 days I try start the Angular Universal, but it is not easy issue. It isn't work. I just download example and use 'npm start'. And this example isn't work: http://jmp.sh/SP7pLSO
What could be the problem?

**Comment by MarkPieszak** [comment]
What version of Node do you have?
Check `node --version`

Did you run `npm install` before running npm start?

**Comment by wasteCleaner** [comment]
I have Node v6.9.1
Yes, I use npm i before

**Comment by MarkPieszak** [comment]
Strange I've never seen those errors before, this is from a Fresh copy of this repo here as well? Hm

**Comment by wasteCleaner** [comment]
MarkPieszak, yes, it is a fresh copy.
I try start it in empty directory (without my Angular2 project, only this files). It isn't work too.
http://jmp.sh/TAqOIEj
Why then it try open files (not in project directory): Error: EACCES: permission denied, open '/Users/aleksandrgorin/.config/configstore/update-notifier-nodemon.json'

**Comment by wasteCleaner** [comment]
Very strangr, but 'sudo npm start' is work.
For run Angular Universal on production server I want to start it under root?

**Comment by MarkPieszak** [comment]
Ah you're on OSX? You need to fix priveledges for those folders you have your projects in, otherwise you'll have to do sudo all the time.

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
