### ISSUE TITLE
Using modules who use 'window' property

### ISSUE THREAD

**Issue by wasteCleaner** [angular/universal-starter#351]
Hello!
I use angular2-masonry module. This module be connected as:
1. app.module
import { MasonryModule } from 'angular2-masonry';
@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [],
  imports: [MasonryModule]
})

2. some.component
import { AngularMasonry, MasonryModule } from 'angular2-masonry'; 
...
@ViewChild(AngularMasonry) masonry: AngularMasonry;
@ViewChild(MasonryModule) layout: MasonryModule;

  ngAfterViewInit() {
    this.masonry.layoutComplete.subscribe(() => {...});
  }

3. Template of some.component
<masonry [options]="{options:values}">
          <masonry-brick class="some-class" *ngFor="let item of itemsArray">
                     ... content ...
          </masonry-brick>
</masonry>

I can't add this code in if (isBrowser){} because I can't use the if construction with @ViewChild().
And If I hide js code in the template will still selector <masonry [options]="{options:values}">.

Please help. My error: http://jmp.sh/HAkV7fF

**Comment by flauc** [comment]
Hi @wasteCleaner 

I had to use masonry recently as well. My solution was to not use `angular2-masonry` but rather the pure js version, you can initialize it in the `AfterViewInit` hook and wrap it in `IsBrowser`, worked just fine for me.

**Comment by wasteCleaner** [comment]
@flauc Thank you! You are very help me!

**Comment by lukaszkukawski** [comment]
**@flauc** 
can you show how you do this?
