### ISSUE TITLE
Not rendered page (the console is not any error)

### ISSUE THREAD

**Issue by wasteCleaner** [angular/universal-starter#352]
Hello!
I have very strange error. I can run the server and it is started without any errors, but if I requested http://localhost:3000 - I get empty page (server response page without any data).
I don't see in console any errors.
I use in my application HttpModule. If HttpModule before UniversalModule I don't see any errors and don't see the page. If UniversalModule before HttpModule - I see error "EXCEPTION: This method is not implemented in Parse5DomAdapter: getCookie" (http://jmp.sh/raBR7gr) and also I don't see page.
How can I catch the error? Why there are no errors in the console?

**Comment by djabif** [comment]
Check this issue https://github.com/angular/universal-starter/issues/167, you just need to place Universal module last
