### ISSUE TITLE
Http2 ?

### ISSUE THREAD

**Issue by zmnv** [angular/universal-starter#354]
In backend side use apache and etc.. 
enabled
`sudo a2enmod http2`

I use **get** function in my component (**get** function from model.service.ts -- master from this github)

```
this.model.get('url to request').subscribe(data => {
      this.relatedLinks = data;
 });
```

inside of universalInit() { }.

But when I look at my apache logs, I see request not http2, but http/1.1

```
server_ip - - [10/Feb/2017:11:43:35 +0300] "GET /wp-json/wp/v2/menulinker....[some code] HTTP/1.1" 200 1125 "-" "Angular 2 Universal"

my_ip - - [10/Feb/2017:11:43:37 +0300] "GET /assets/favicon_vlako2.ico HTTP/1.1" 200 1450 "http://..../" "Mozilla/5.0 (Windows NT6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/5    37.36"
```

How to use http2 in universal request?

**Comment by samvloeberghs** [comment]
http2 is totally unrelated to universal
