### ISSUE TITLE
Pre-render with async call won't work when using a custom http provider

### ISSUE THREAD

**Issue by julienR2** [angular/universal-starter#355]
Hi all !
To handle HTTP errors the same way in all the app, we created a custom HTTP provider:
```
{
    provide: Http,
    useFactory: loadCustomHttp,
    deps: [ XHRBackend, RequestOptions, DataHelperService, AuthStorageService, Injector ]
}
```

With the HTTP service looking like this (I skipped the imports to make it shorter but still quite long sorry.. However I feel it could be interesting to put this code in case the error comes from the custom HTTP implementation):
```
@Injectable()
export class CustomHttp extends Http {

  constructor(
    backend: ConnectionBackend,
    defaultOptions: AppRequestOptions,
    private dataHelper: DataHelperService,
    private authStorage: AuthStorageService,
    private injector: Injector
  ) {
    super(backend, defaultOptions);
  }

  request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {
    if (typeof(url) == 'Request') {
      console.log('calling ', url.url);
    }

    let requestResponse = super.request(url, options)
                               .retryWhen(error => {
                                  return error.delay(200)
                                              .take(2);
                               });

    if (typeof(url) === 'object') {
      return this.intercept(requestResponse, url.url);
    }
    return this.intercept(requestResponse, url.toString());
  }

  get(url: string, options?: RequestOptionsArgs): Observable<Response> {
    return this.intercept(super.get(url, options), url);
  }

  post(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
    return this.intercept(super.post(url, body, options), url);
  }

  getRouter(): Router { // this creates router property on your service.
    return this.injector.get(Router);
  }

  intercept(observable: Observable<Response>, url: string): Observable<Response> {
    return observable.catch((err, source) => {
      if (err.status === 401) { // user not connected trying to access a secure page
        this.authStorage.clearAll();

        let router = this.getRouter();
        if (router) {
          if (!url.endsWith(process.env.SETTINGS_API_URL)
          && !url.endsWith(process.env.CONFIG_API_URL)) {
            this.dataHelper.setData(JSON.stringify({ error: 'refresh token' }));
            router.navigate(['auth/login', { next: router.url}]);
          }
        }
      }

      if (err.status === 500) {
        let router = this.getRouter();
        if (router) {
          router.navigate(['server-error', {status: err.status}]);
        }
      }
      return Observable.throw(err);
    });
  }
}
```

However I realized recently that the pre-rendering of the page with async request wasn't working anymore ! It seems Zone can't figure out anymore when the request is done or not.

I don't know if it's a bug or not, but I thought it could be interesting discussing it and maybe have another Universal friendly solution to globally handle HTTP request errors ?

Thanks for any advice or piece of information !

**Comment by MarkPieszak** [comment]
So the reason is that we're already extending `Http` within Universal, with a class called `PreloadHttp`.
So just extend that instead and you should be all set!

```
@Injectable()
export class CustomHttp extends PreloadHttp {
  /* your overrides */
}
```

That should take care of the problem!

**Comment by julienR2** [comment]
Awesome !
I'll try this tonight and let you know if everything goes as expected :)
Thanks for these details !

On Feb 11, 2017 04:14, "Mark Pieszak" <notifications@github.com> wrote:

So the reason is that we're already extending Http within Universal, with a
class called PreloadHttp.
So just extend that instead and you should be all set!

@Injectable()
export class CustomHttp extends PreloadHttp {
  /* your overrides */
}

That should take care of the problem!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/universal-starter/issues/355#issuecomment-279117018>,
or mute the thread

**Comment by julienR2** [comment]
Hi ! I've finally got some time to try this.

However, even with a simple override like this:
```
@Injectable()
export class CustomHttp extends PreloadHttp {

  constructor(
    backend: ConnectionBackend,
    defaultOptions: AppRequestOptions
  ) {
    super(backend, defaultOptions);
  }
}
```
with this declaration in may shared.module:
```
{
    provide: PreloadHttp,
    useFactory: loadCustomHttp,
    deps: [ XHRBackend, RequestOptions, DataHelperService, AuthStorageService, Injector ]
  }
```

I've got a `TypeError: b is undefined` error.. (In Chrome it's a bit more explicit `Uncaught TypeError: Cannot read property 'prototype' of undefined` but still quite hard to identify)

**Comment by MarkPieszak** [comment]
I don't think you need to do all that provide stuff, just add `CustomHttp` normally (no useFactory etc), and inject it through out your app in constructors `private http: CustomHttp`.

**Comment by gdi2290** [comment]
you need to wrap it with zone.js

**Comment by nicolaslawdune** [comment]
Did you solve it ?

I can't do any HTTP requests during pre-rendering server and throws this error : `Microsoft.AspNetCore.NodeServices Error: 0 : unable to verify the first certificate`

**Comment by gdi2290** [comment]
so long as zone.js is able to track your async calls then the server will wait for them to be done otherwise it just won't know
