### ISSUE TITLE
session ?

### ISSUE THREAD

**Issue by ahmadhaerii** [angular/universal-starter#359]
why i cant use session in the api.ts ?
i use 'mongoose'  'express-session'  'connect-mongo'  for save sessions and user login , but every request save 2 row in the db and i can't save user login in the server side !

**Comment by gdi2290** [comment]
the api was only meant to be an example and not at all how you're suppose to implement it. the api and the app should be separate

**Comment by ahmadhaerii** [comment]
can you make a sample for session ?
i use zone.current.get('req').session in the api , but not work ... ! i don't know how to use them ... !
