### ISSUE TITLE
css not appling quicly.

### ISSUE THREAD

**Issue by NiLeShpatil777** [angular/universal-starter#362]
hi,
 Images are loading first without css and once all html template data loades,images are getting loaded without any css then after some time css gets applied to the images.Why the images are getting loaded without any css at the time of loading?.Becouse of this my pages are feeling like broken .
my package.json is as follows,
{
  "name": "universal-starter",
  "version": "2.0.0",
  "description": "Angular 2 Universal starter kit by @AngularClass",
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/universal-starter.git"
  },
  "scripts": {
    "watch": "webpack --watch",
    "prebuild": "rimraf dist",
    "build": "webpack",
    "build:prod": "webpack --progress -p",
    "prestart": "npm run build",
    "server": "nodemon dist/server/index.js",
    "debug:server": "node-nightly --inspect --debug-brk dist/server/index.js",
    "start": "npm run server",
    "debug:start": "npm run build && npm run debug:server",
    "predebug": "npm run build",
    "debug:build": "node-nightly --inspect --debug-brk node_modules/webpack/bin/webpack.js",
    "debug": "node --debug-brk dist/server/index.js"
  },
  "license": "MIT",
  "contributors": [
    "AngularClass <hello@angularclass.com>",
    "PatrickJS <patrick@angularclass.com>",
    "Jeff Whelpley <jeff@gethuman.com>",
    "Jeff Cross <crossj@google.com>",
    "Mark Pieszak <mpieszak84@gmail.com>"
  ],
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "angular2-express-engine": "~2.0.11",
    "angular2-platform-node": "~2.0.11",
    "angular2-universal": "~2.0.11",
    "angular2-universal-polyfills": "~2.0.11",
    "body-parser": "^1.15.2",
    "express": "^4.14.0",
    "jquery": "^3.1.1",
    "methods": "~1.1.2",
    "ng2-page-scroll": "^3.1.1",
    "ng2meta": "^1.0.0",
    "node-sass": "3.7.0",
    "nodemailer": "0.7.1",
    "nodemailer-smtp-transport": "^2.6.0",
    "rxjs": "5.0.0-beta.12",
    "sass-loader": "3.2.0",
    "stylelint-webpack-plugin": "^0.3.0",
    "tslint": "^3.14.0",
    "tslint-loader": "^2.1.5",
    "webpack-closure-compiler": "^2.0.2",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@angularclass/resolve-angular-routes": "^1.0.9",
    "@types/body-parser": "0.0.29",
    "@types/compression": "0.0.29",
    "@types/cookie-parser": "^1.3.29",
    "@types/express": "^4.0.32",
    "@types/express-serve-static-core": "^4.0.33",
    "@types/hammerjs": "^2.0.32",
    "@types/mime": "0.0.28",
    "@types/node": "^6.0.38",
    "@types/serve-static": "^1.7.27",
    "angular2-template-loader": "^0.4.0",
    "cookie-parser": "^1.4.3",
    "imports-loader": "^0.6.5",
    "json-loader": "^0.5.4",
    "nodemon": "^1.10.0",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "string-replace-loader": "github:gdi2290/string-replace-loader",
    "ts-loader": "^0.8.2",
    "ts-node": "^1.3.0",
    "typescript": "2.0.0",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^2.1.0-beta.0",
    "webpack-merge": "^0.13.0"
  }
}

**Comment by MarkPieszak** [comment]
The styles aren't being added to your server rendered view that's why, but it must be something newer you've added, with a fresh install of the repo it works fine.

How are you trying to apply styles to your Templates?

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
