### ISSUE TITLE
How to update meta "og"

### ISSUE THREAD

**Issue by martinop** [angular/universal-starter#366]
How i can update meta property "og:title" using angular2-meta that provide universal starter?
I do:
```
this._meta.updateTag("property=og:title", { name: 'og:title', content:  "test test"})
```
and I got:
```
EXCEPTION: Uncaught (in promise): SyntaxError: Failed to execute 'querySelector' on 'Document': 'meta[property=og:title]' is not a valid selector.
Error: Failed to execute 'querySelector' on 'Document': 'meta[property=og:title]' is not a valid selector.
```

**Comment by hightech2** [comment]
Try to wrap og:title with "". If that isn't at any help I provide a simple method that updates meta.

 updateMeta(tagName: string, content: string) {
    const tag = { name: tagName, content: content };
    const attributeSelector = `name="${tagName}"`;
    this._meta.removeTag(attributeSelector);
    this._meta.addTag((tag) as any, false);
  };

**Comment by MarkPieszak** [comment]
You can update Meta tags directly with the `Meta` service provided with Angular now.
