### ISSUE TITLE
Angular2 Server Side Rendering - Angular 2 Universal Issue

### ISSUE THREAD

**Issue by Abinayats** [angular/universal-starter#367]
I tried changing my angular2 app to angular2 universal. On that I segregated server and client side module. On doing npm start I am getting the following error.

`EXCEPTION: The selector "app-root" did not match any elements
ORIGINAL STACKTRACE:
Error: The selector "app-root" did not match any elements
    at DomRenderer.selectRootElement (C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:26663:23)
    at selectOrCreateRenderHostElement (C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:15131:32)
    at AppView._View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:12:16)
    at AppView.create (C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:51125:21)
    at ComponentFactory.create (C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:36104:36)
    at ApplicationRef_.bootstrap (C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:22794:40)
    at C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:22703:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:22703:42)
    at C:\Users\SYS168\scotchiversal - Copy\dist\server\index.js:22671:27`

Can you please someone guide me.. This is my folder structure https://s11.postimg.org/g5xht8k6b/git.png
![git](https://cloud.githubusercontent.com/assets/25842428/23063036/87b1f93e-f52e-11e6-8f9c-d67b3ece16e5.PNG)

Thanks in Advance.

**Comment by MarkPieszak** [comment]
In your index.html is there in fact an app-root HTML tag there?

**Comment by Abinayats** [comment]
Yes It is there. My problem when i hit browser the webpage loading correctly. But not the server side. If I view page source app-root tag is there still.

I am getting this error in console. If this error is solved, the in the place of app-root html will come.
I am struggling to pass through the server side.

**Comment by MarkPieszak** [comment]
It might be something strange in your server.ts maybe. Do you have a repo anywhere to look at?

**Comment by Abinayats** [comment]
No I need to upload. I will upload and text you.

**Comment by Abinayats** [comment]
This is my server.ts code

// the polyfills must be one of the first things imported in node.js.
// The only modules to be imported higher - node modules with es6-promise 3.x or other Promise polyfill dependency
// (rule of thumb: do it if you have zone.js exception that it has been overwritten)
// if you are including modules that modify Promise, such as NewRelic,, you must include them before polyfills
import 'angular2-universal-polyfills';
import 'ts-helpers';
import './__workaround.node'; // temporary until 2.1.1 things are patched in Core

import * as path from 'path';
import * as express from 'express';
import * as bodyParser from 'body-parser';
import * as cookieParser from 'cookie-parser';
import * as morgan from 'morgan';
import * as compression from 'compression';

// Angular 2
import { enableProdMode } from '@angular/core';
// Angular 2 Universal
import { createEngine } from 'angular2-express-engine';

// App
import { MainModule } from './node.module';

// Routes
import { routes } from './server.routes';



// enable prod for faster renders
enableProdMode();

const app = express();
const ROOT = path.join(path.resolve(__dirname, '..'));

// Express View
app.engine('.html', createEngine({
  ngModule: MainModule,
  providers: [
    // use only if you have shared state between users
    // { provide: 'LRU', useFactory: () => new LRU(10) }

    // stateless providers only since it's shared
  ]
}));
app.set('port', process.env.PORT || 3000);
app.set('views', __dirname);
app.set('view engine', 'html');
app.set('json spaces', 2);

app.use(cookieParser('Angular 2 Universal'));
app.use(bodyParser.json());
app.use(compression());

app.use(morgan('dev'));

function cacheControl(req, res, next) {
  // instruct browser to revalidate in 60 seconds
  res.header('Cache-Control', 'max-age=60');
  next();
}
// Serve static files
app.use('/assets', cacheControl, express.static(path.join(__dirname, 'assets'), {maxAge: 30}));
app.use(cacheControl, express.static(path.join(ROOT, 'dist/client'), {index: false}));

//
/////////////////////////
// ** Example API
// Notice API should be in aseparate process
import { serverApi, createTodoApi } from './backend/api';
// Our API for demos only
app.get('/data.json', serverApi);
app.use('/api', createTodoApi());

process.on('uncaughtException', function (err) { 
  console.error('Catching uncaught errors to avoid process crash', err);
});

function ngApp(req, res) {

  function onHandleError(parentZoneDelegate, currentZone, targetZone, error)  {
    console.warn('Error in SSR, serving for direct CSR');
    console.warn('Abinaya'+error);
    res.sendFile('index.html', {root: './src'});
    return false;
  }

  Zone.current.fork({ name: 'CSR fallback', onHandleError }).run(() => {
    res.render('index', {
      req,
      res,
      // time: true, // use this to determine what part of your app is slow only in development
      preboot: true,
      baseUrl: '/',
      requestUrl: req.originalUrl,
      originUrl: `http://localhost:${ app.get('port') }`
    });
    // res.render('index', {
    //   req,
    //   res,
    //   // time: true, // use this to determine what part of your app is slow only in development
    //   preboot: false,
    //   baseUrl: '/',
    //   requestUrl: req.originalUrl,
    //   originUrl: `http://localhost:${ app.get('port') }`
    // });
  });

}




/**
 * use universal for specific routes
 */
app.get('/', ngApp);
// app.get('job-listings/:listing', ngApp);

routes.forEach(route => {
  app.get(`/${route}`, ngApp);
  app.get(`/${route}/*`, ngApp);
});









app.get('*', function(req, res) {
  res.setHeader('Content-Type', 'application/json');
  var pojo = { status: 404, message: 'No Content' };
  var json = JSON.stringify(pojo, null, 2);
  res.status(404).send(json);
});

// Server
let server = app.listen(app.get('port'), () => {
  console.log(`Listening on: http://localhost:${server.address().port}`);
});





// app.get('*', ngApp);
// app.get('/', ngApp);

**Comment by valevalorin** [comment]
I'm experiencing this same issue. I've had the same selector error message showing up in my console since I pulled down the project.

My app works in the browser but prebooting fails.

**Comment by singhmohancs** [comment]
@valevalorin 
Maybe, you have not added `selector` to your `app` component.
<img width="300" alt="screen shot 2017-07-14 at 12 12 05 am" src="https://user-images.githubusercontent.com/283132/28182270-338d6ff0-6829-11e7-96c5-e1cb7a34fc3a.png">

**Comment by valevalorin** [comment]
@singhmohancs 
It's there.

**Comment by singhmohancs** [comment]
@valevalorin 
This works perfectly with your configuration. Here is my repo with your configurations 
https://github.com/singhmohancs/universal-starter/tree/universal-template

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
