### ISSUE TITLE
Style tags loaded twice for ViewEncapsulation.None

### ISSUE THREAD

**Issue by tuxado** [angular/universal-starter#370]
hi,

i use sass-loader for loading scss files but when i use ViewEncapsulation.None on the component the server work fine but i note that styles tags are "loaded twice" and the url change from the requested url  http://localhost:3000/page1 (the server response) to http://localhost:3000/ and redirecto to http://localhost:3000/page1 (client response)  and when i use ViewEncapsulation.Emulated the building crash with 'push' does not exist related to a styles array

```
@Component({
  changeDetection: ChangeDetectionStrategy.Default,
  encapsulation: ViewEncapsulation.None,
  styleUrls: ['./initial.scss', './page1.component.scss'],  <-- loaded twice
  selector: 'page1',
  templateUrl: './page1.component.html'
})
```

```
 {
       test: /\.scss$/,
        use: ['raw-loader', 'sass-loader']
 }, 
```

Should we use only css files for styles?

**Comment by halben** [comment]
I ran into this issue as well. It's rendering twice; One on the server and one on the client side.

**Comment by nicky-lenaers** [comment]
Having this issue aswel. Makes debugging and inspecting CSS in Chrome Dev Tools a real pain, since I had to disable/enable every CSS line twice or even more.

**Comment by tuxado** [comment]
@nicky-lenaers you can set encapsulation: ViewEncapsulation.Emulated on the component the style tags will be loaded once but for the scss styles users this not working with "Emulated" and the build of the app crash with 'push' does not exist and when i set encapsulation to ViewEncapsulation.None the build pass but style tags are loaded twice, i read in some post that we should convert scss to css with scripts before the build of the app but i have no idea how to do that.

@Component({
  changeDetection: ChangeDetectionStrategy.Default,
  encapsulation: ViewEncapsulation.Emulated, // <-- [Emulated]
  styleUrls: ['./initial.css', './page1.component.css'],  // <-- [loaded once]
  selector: 'page1',
  templateUrl: './page1.component.html'
})

**Comment by nicky-lenaers** [comment]
@tuxado Yes, changing the `ViewEncapsulation.None` to `ViewEncapsulation.Emulation` fixes the double imports.

However, I have "global" styles I need to apply to the whole app (like `<html>` and `<body>` elements), not per component. These will not be applied to any elements outside the component root if `ViewEncapsulation` is set to `Emulated`. So e.g. including styles for `body` or `html` in my root component `<app>` with `ViewEncapsulation` set to `Emulated` will not work.

> i read in some post that we should convert scss to css with scripts before the build of the app but i have no idea how to do that.

I guess you could configure Webpack to build a seperate file from your Sass files and simply include the generated CSS file once in your `index.html`.
