### ISSUE TITLE
What is CSR fallback & SSR + how to know universal  worked ?

### ISSUE THREAD

**Issue by sinsunsan** [angular/universal-starter#372]
I have problems in my installation so my server.js 
use this function 
```js
function onHandleError(parentZoneDelegate, currentZone, targetZone, error)  {
    console.warn('Error in SSR, serving for direct CSR');
    res.sendFile('index.html', {root: './src'});
    return false;
  }
```
and get me a display 
but when  inspecting code in the browser and clicking view source 
It seemed empty, so suppose angular universal have not worked

3 questions : 
* what is SSR
* what is CSR 
* how to tell for sur universal worked or not ? (even if the display is correct)

**Comment by sinsunsan** [comment]
To precise the source is not empty but the <bw-app> have not been processed. 
So I suppose universal have not succeed.

```html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Angular 2 Universal Starter</title>
  <meta name="description" content="Angular 2 Universal">
  <meta name="keywords" content="Angular 2,Universal">
  <meta name="author" content="PatrickJS">
  <meta name="viewport" content="width=device-width,minimum-scale=1">

  <link rel="icon" href="data:;base64,iVBORw0KGgo=">

  <link rel="prerender" href="http://localhost:3000/lazy">
  <link rel="preload" href="/assets/logo.png">
  <base href="/">

</head>
<body>

  <bw-app>
    Loading Universal customized...
  </bw-app>


  <script async src="/main.bundle.js"></script>
</body>
</html>
```

**Comment by MarkPieszak** [comment]
SSR is Server-side rendering
I'm not sure what CSR is supposed to stand for there, but basically on error it just dishes out the original `index.html` file so that at least client-side bootstrapping can take over (even when SSR failed).

One super easy way to test SSR is to go to your Chrome devtools, settings, and click the Disable JavaScript checkbox. Then try refreshing / clicking around your app. No client-side at all, everything came from the server! :)

Hope that helps.

**Comment by sinsunsan** [comment]
Thanks !
SSR : Server-side rendering 
CSR : Client side rendering

Interesting way to test, so that we can only see server content. 

By the way I fixed  I think the problem why this error happened. 
I add imported  UniversalModule in my own module, and after checking universal starter, they  did not do that. 
This was the problem to use many tutorial to start with some that were probably outdated.

**Comment by MarkPieszak** [comment]
Clientside rendering there it is :)

Things will be updated soon when we switch to Angular 4.x!

**Comment by flauc** [comment]
@MarkPieszak

Totally unrelated, but do you maybe have an estimate when that might be?

Thanks 👍

**Comment by sinsunsan** [comment]
Yes when angular 4 will be ready ? And what does it change for our angular universal problem? I mean how it will be easier to setup ? Will it be  integrated in angular 4 without angular-universal ?

**Comment by MarkPieszak** [comment]
It will be within `@angular/platform-server`, but it can be used just the same there will be an expressEngine that abstracts out the changed API calls underneath. We've had success testing it out, maybe soon we can clean up the starter and add it in here as well.

As for the documentation, I'm sure it'll be a lot cleaner and I'd imagine on the Angular.io website as well.

Maybe in a week or so we can get it in here so people can play with it in the wild? @flauc

**Comment by sinsunsan** [comment]
Ok good to make it more integrated. 

I am preparing a tuto on how to use pratically use angular universal starter, and which file do what 
http://dev.sebastienlucas.com/how-to-use-the-angular-universal-starter/

The most difficult part for us to learn is to distinguish : 

* files that need to be used unchanged
* That need to be customised 
* that is specific to the example app

My blog post is a work in progress. 
If you have advices to give me with pleasure...
