### ISSUE TITLE
use library that use dom element inside it 

### ISSUE THREAD

**Issue by mostafamashayekhi** [angular/universal-starter#377]
I want use flowplayer in my project angular universal but flowplayer use dom element and I get error document is not defined how to solve it?

I'm newbie in angular universal;
thank's for answer;

**Comment by ivancamilov** [comment]
You could use the `isBrowser` and `isNode` functions like this:

```
import { isNode, isBrowser } from 'angular2-universal';
...

if(isBrowser) {
  // handle browser-only logic here
}
```
