### ISSUE TITLE
manipulate meta tags in Universal

### ISSUE THREAD

**Issue by sadeghipour** [angular/universal-starter#378]
Could it be possible to edit/add meta tags (such as description, title, og:image and etc) in Universal?

**Comment by Dralac** [comment]
@sadeghipour You have more info about it here #340

**Comment by orgbx** [comment]
Yes, search is your friend @sadeghipour. We had to do it for you..
This question has already been discussed in many issues (you have a complete discussion and working example here for example https://github.com/angular/universal-starter/issues/287#issuecomment-271274120)
You should close this issue.

**Comment by meeraPurohit** [comment]
Hey, @orgbx, I tried implementing you approach, but I got the following error while importing 
**import {__platform_browser_private__} from '@angular/platform-browser';**
**[ts] Module '"DIRCTORY/node_modules/@angular/platform-browser/platform-browser"' has no exported member '__platform_browser_private__'.**

Do you have any other solution for this? Or I'am not correctly importing it?
Please help me out for this.
Thanks!

**Comment by orgbx** [comment]
@meeraPurohit My solution was for angular 2 where universal was flaky and patchy. Things have quite changed since then and while I'm not updated on the framework anymore, I do recall that Angular 4 included a big overhaul of the universal approach where meta tags were now natively supported. Good luck.

**Comment by meeraPurohit** [comment]
Hey @orgbx,
Thanks for the reply. I tried it in angular 5 and succeeded. Those were really hectic days for me.

**Comment by kamalakkanni** [comment]
Hi @meeraPurohit ,

I am also using universal in angular5 project.My updated meta tags are rendered in view page source in localhost:4000.After deploying this to iis.It is not rendering updated meta.pls help me to fix it.I used Meta service which is from @angular/platform-browser

Thanks

**Comment by meeraPurohit** [comment]
@kamalakkanni  

First of all you need to create a shared service like this

```
import { Injectable } from '@angular/core';
import { Title, Meta } from "@angular/platform-browser";
import { Router, NavigationEnd } from "@angular/router";
import 'rxjs/add/operator/filter';

@Injectable()
export class SeoService {
    public constructor(
        private titleService: Title,
        private metaService: Meta,
        private router: Router,
    ) { }

    public addSeoData(): void {
        this.router.events.filter((event: any) => event instanceof NavigationEnd).subscribe(() => {
            let root = this.router.routerState.snapshot.root;
            while (root) {
                if (root.children && root.children.length) {
                    root = root.children[0];
                } else if (root.data && root.data['title']) {
                    this.titleService.setTitle(root.data['title']);
                    let tags = root.data["metatags"];
                    for (let tag in tags) {
                        this.metaService.updateTag({ property: tag, content: tags[tag] });
                        this.metaService.updateTag({ name: tag, content: tags[tag] });
                    }
                    return;
                } else {
                    return;
                }
            }
        });
    }
}
```

Then after in you routing file, you need to put 
```

data: {
            title: "Your title here",
            metatags: {
                'description': 'Your description',
                'keywords': 'Your keywords',
            }
        }
```
 
and inside you every component you need to import your shared file and call the addSeoData into constructor like this 

```
constructor(private seoService: SeoService) {
    this.seoService.addSeoData();
} 
```

Hope this will help you. and do reverrt me if you succeed.

**Comment by dpinheiro** [comment]
I had a problem with the Meta service and universal as well, and it turns out if access document object before setting the meta tags, the meta tags will not show up (they show when app bootstraps in the browser but not on server render as pretended)

```
constructor(
    private metaService: Meta,
    @Inject(DOCUMENT) document: any
  ) { }

  ngOnInit() {
    this.metaService.updateTag({'property': 'foo', 'content': 'bar'});

    // this has to come after setting meta, otherwise it will not work!
    this.shareUrl = document.location.href;
  }
```

If `this.shareUrl = document.location.href` is becomes first than the tags will not work
