### ISSUE TITLE
Http.get error

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#38]
I am trying to get angular universal into a existing angular2 app. I am getting the following error when accessing the site : 

`EXCEPTION: Error during instantiation of BlogList!.
STACKTRACE:

ORIGINAL EXCEPTION: Error
ERROR CONTEXT:
_Context {
  element: 
   { type: 'tag',
     name: 'blog-list',
     namespace: 'http://www.w3.org/1999/xhtml',
     attribs: { '_ngcontent-fid-4': '' },
     'x-attribsNamespace': {},
     'x-attribsPrefix': {},
     children: [],
     parent: null,
     prev: null,
     next: null },
  componentElement: 
   { type: 'tag',
     name: 'router-outlet',
     namespace: 'http://www.w3.org/1999/xhtml',
     attribs: {},
     'x-attribsNamespace': {},
     'x-attribsPrefix': {},
     children: [],
     parent: 
      { type: 'tag',
        name: 'div',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: [Object],
        'x-attribsNamespace': {},
        'x-attribsPrefix': {},
        children: [Object],
        parent: [Object],
        prev: [Object],
        next: null,
        className: 'blog-app' },
     prev: 
      { type: 'text',
        data: '\n        ',
        parent: [Object],
        prev: null,
        next: [Circular] },
     next: 
      { type: 'text',
        data: '\n    ',
        parent: [Object],
        prev: [Circular],
        next: null } },
  injector: 
   Injector {
     _isHostBoundary: false,
     _depProvider: 
      AppElement {
        proto: [Object],
        parentView: [Object],
        parent: null,
        nativeElement: [Object],
        embeddedViewFactory: null,
        nestedViews: null,
        componentView: null,
        ref: [Object],
        _queryStrategy: _EmptyQueryStrategy {},
        _injector: [Circular],
        _strategy: [Object] },
     _debugContext: [Function],
     _constructionCounter: 2,
     _proto: ProtoInjector { numberOfProviders: 2, _strategy: [Object] },
     _parent: 
      Injector {
        _isHostBoundary: true,
        _depProvider: null,
        _debugContext: null,
        _constructionCounter: 0,
        _proto: [Object],
        _parent: [Object],
        _strategy: [Object] },
     _strategy: 
      InjectorInlineStrategy {
        injector: [Circular],
        protoStrategy: [Object],
        obj0: {},
        obj1: [Object],
        obj2: {},
        obj3: {},
        obj4: {},
        obj5: {},
        obj6: {},
        obj7: {},
        obj8: {},
        obj9: {} } } }
DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask
Angular 2 is running in the production mode. Call enableDevMode() to enable the development mode.`

In the browser I see the following : 

`Uncaught TypeError: Cannot read property 'cloneNode' of null`

The task npm start runs without probems, the issue only occurs when I actually navigate to the URL.

The app does use HTTP, but I followed the instructions given here : https://github.com/angular/universal-starter/issues/7#issuecomment-153156415

Any help would be much appreciated ;)

**Comment by joaogarin** [comment]
By the way components are working, router also is working if I access localhost:3000/about (a specific routing that is not using HTTP) it seems to work.

The error comes only really on components that are using http.

**Comment by manekinekko** [comment]
@joaogarin could you try again with the latest version of the starter and give us your feedback?

**Comment by joaogarin** [comment]
Hello,

I still see this error log when using HTTP withing the "Home" component for example. I dont see the browser error though that says : Uncaught TypeError: Cannot read property 'cloneNode' of null

I will update the title of the issue.

This is the stack trace of a just cloned version of the repo : 

STACKTRACE:

ORIGINAL EXCEPTION: Error
ERROR CONTEXT:
_Context {
  element: 
   { type: 'tag',
     name: 'home',
     namespace: 'http://www.w3.org/1999/xhtml',
     attribs: { '_ngcontent-vbh-2': '' },
     'x-attribsNamespace': {},
     'x-attribsPrefix': {},
     children: [],
     parent: null,
     prev: null,
     next: null },
  componentElement: 
   { type: 'tag',
     name: 'router-outlet',
     namespace: 'http://www.w3.org/1999/xhtml',
     attribs: { '_ngcontent-vbh-1': '' },
     'x-attribsNamespace': {},
     'x-attribsPrefix': {},
     children: [],
     parent: 
      { type: 'tag',
        name: 'main',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: [Object],
        'x-attribsNamespace': {},
        'x-attribsPrefix': {},
        children: [Object],
        parent: [Object],
        prev: [Object],
        next: [Object] },
     prev: 
      { type: 'text',
        data: '\n      ',
        parent: [Object],
        prev: null,
        next: [Circular] },
     next: 
      { type: 'text',
        data: '\n    ',
        parent: [Object],
        prev: [Circular],
        next: null } },
  injector: 
   Injector {
     _isHostBoundary: false,
     _depProvider: 
      AppElement {
        proto: [Object],
        parentView: [Object],
        parent: null,
        nativeElement: [Object],
        embeddedViewFactory: null,
        nestedViews: null,
        componentView: null,
        ref: [Object],
        _queryStrategy: _EmptyQueryStrategy {},
        _injector: [Circular],
        _strategy: [Object] },
     _debugContext: [Function],
     _constructionCounter: 1,
     _proto: ProtoInjector { numberOfProviders: 1, _strategy: [Object] },
     _parent: 
      Injector {
        _isHostBoundary: true,
        _depProvider: null,
        _debugContext: null,
        _constructionCounter: 0,
        _proto: [Object],
        _parent: [Object],
        _strategy: [Object] },
     _strategy: 
      InjectorInlineStrategy {
        injector: [Circular],
        protoStrategy: [Object],
        obj0: {},
        obj1: {},
        obj2: {},
        obj3: {},
        obj4: {},
        obj5: {},
        obj6: {},
        obj7: {},
        obj8: {},
        obj9: {} } } }
DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask

What I did was what is described in a git diff attached as screenshots. Simply adding a http.get in the Home component.

Best regards
Joao Garin
![screenshot 2016-02-28 16 49 42](https://cloud.githubusercontent.com/assets/2866604/13380135/64a0da92-de3b-11e5-95f4-7dfff7d2710e.png)
![screenshot 2016-02-28 16 49 49](https://cloud.githubusercontent.com/assets/2866604/13380136/64a2b2b8-de3b-11e5-8170-8bfbb354a11e.png)

**Comment by manekinekko** [comment]
OK. I reproduced your issue. This is an issue related to universal. I'll open a issue on your behalf on the Universal repo.

**Comment by joaogarin** [comment]
;) great. I am not sure I am actually using the http the proper way. but I followed the suggestions from @gdi2290 in https://github.com/angular/universal-starter/issues/7#issuecomment-153156415

**Comment by manekinekko** [comment]
Yeah, universal is providing its own HTTP_PROVIDERS which you have to use.
We'll investigate this. Thanks :+1:

**Comment by manekinekko** [comment]
@gdi2290 we may close this issue. It is not related to the starter.
