### ISSUE TITLE
Angular 4 Update

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#385]
Hi, I'm just curious to know if there are plans for updating this repo to angular 4?

Thanks for the hard work 👍

**Comment by maloca1992** [comment]
+

**Comment by maloca1992** [comment]
+1

**Comment by MarkPieszak** [comment]
You can see https://github.com/FrozenPandaz/ng-universal-demo for now, I'm sure the starter will be something along those lines. Definitely enough to get you started at least 👍

**Comment by flauc** [comment]
Yes I found that one as well, so I was curious if I should move to that one or stick with this.

**Comment by MarkPieszak** [comment]
Yeah definitely go with that one for now, but I'd imagine we're going to upgrade this one as well eventually though! Would make sense since angular2-universal moved :)

**Comment by flauc** [comment]
Great, thanks for the help 👍

**Comment by samarthnm** [comment]
@vikerman  : Can you please help me ? unable to upgrade.

**Comment by dneeleman** [comment]
@samarthnm what isn't actually working for you? Did you follow the migration guide for Angular Universal?

**Comment by samarthnm** [comment]
@dneeleman  :  I follow this http://angularjs.blogspot.in/2017/03/angular-400-now-available.html for upgration, Can you please send me migration step or link something ?

**Comment by dneeleman** [comment]
@samarthnm Ah yes, that article is not that great for upgrading. You can use Universals own upgrade guide: https://github.com/angular/universal/blob/master/UPGRADE-GUIDE.md.

This is the one I'm actually currently using to upgrade our projects!

**Comment by MarkPieszak** [comment]
Hey guys, there should be a repo wipe and replacement coming to implement the v4 version of the starter: You can follow the PR here: https://github.com/angular/universal-starter/pull/358

**Comment by joseluisq** [comment]
:+1: 
Does it some progress this?

**Comment by MarkPieszak** [comment]
This should be in master now @joseluisq 

We can close this one out now @gdi2290 (I don't have access in this repo)

**Comment by joseluisq** [comment]
@MarkPieszak :+1:
