### ISSUE TITLE
Metatags Server Side Render

### ISSUE THREAD

**Issue by martinop** [angular/universal-starter#389]
How I can set the meta tags for specific view to be able to share that link on twitter and others social media?
```
import { Injectable, Inject } from '@angular/core';
import { DomAdapter } from '@angular/platform-browser/src/dom/dom_adapter';
import { __platform_browser_private__, DOCUMENT } from '@angular/platform-browser';

@Injectable()
export class SeoService {
  private _dom: DomAdapter = __platform_browser_private__.getDOM();
  constructor( @Inject(DOCUMENT) private _document: any) { }

  setTitle(title: string) {
    this._document.title = title
  }

  setMetaElem(name: string, value: string) {
    let headTags = this._document.head.children as HTMLCollection;
    for (let i = 0; i < headTags.length; i++) {
      let elem = headTags[i] as HTMLElement;
      if (elem.tagName === 'META') {
        let attr = elem.attributes
        if (attr[0]) {
          if (attr[0].value === name) {
            this._dom.remove(elem);
          }
        }
      }

    }

    let el = this._dom.createElement('meta') as HTMLMetaElement;
    this._dom.setAttribute(el, 'name', name);
    this._dom.setAttribute(el, 'content', value);
    this._dom.appendChild(this._document.head, el);
  }

  setOgElem(name: string, value: string) {
    let headTags = this._document.head.children as HTMLCollection;
    for (let i = 0; i < headTags.length; i++) {
      let elem = headTags[i] as HTMLElement;
      if (elem.tagName === 'META') {
        let attr = elem.attributes
        if (attr[0]) {
          if (attr[0].value === name) {
            this._dom.remove(elem);
          }
        }
      }

    }

    let el = this._dom.createElement('meta') as HTMLMetaElement;
    this._dom.setAttribute(el, 'property', name);
    this._dom.setAttribute(el, 'content', value);
    this._dom.appendChild(this._document.head, el);
  }
}
```

Im using that service

**Comment by elhamchoopany** [comment]
you should be use OpenGraph and Twitter Card

**Comment by MarkPieszak** [comment]
You can use the `Meta` service provided by Angular now to change `<meta>` tags easily.

**Comment by ericel** [comment]
@MarkPieszak  The meta tag service provided by Angular doesn't seem to work with universal in rendering. Everything works well, but when I view my page source,  the meta tags don't show up.

**Comment by avsek477** [comment]
@ericel  did you find any solution for your problem?

**Comment by mlb6** [comment]
@ericel I'm having the same issue. Using the Meta Service does not add any meta tag on the server side. Have you found a solution?

**Comment by AhmedHassan07** [comment]
I am having same problem with angular universal. any solution?

**Comment by avsek477** [comment]
Add this to your tsconfig.json file. By default, the angular neglects the
meta data. Also, my server response always throws the index.html. But in my
front end, the api responses are all good. I cant figure out why my
server.ts isn't throwing any reponse other than index.html

angularCompilerOptions": {
    "skipMetadataEmit" : false,
    "strictMetadataEmit": true
  }

**Comment by meeraPurohit** [comment]
@avsek477 I'am using angular 5 and I implemented this on tsconfig.json file but no success. 
Can you help me out of this?
