### ISSUE TITLE
Preboot Bug... Not updating input value until new value is entered after full boot.

### ISSUE THREAD

**Issue by qdouble** [angular/universal-starter#39]
As can be seen if you load up the seed and type in the input field, the input value is not updated until a new value is entered. This problem exists even when using ngModel and/or form controls. The big issue is, if you are filling out a form or input field before the app fully loads, the forms fields or variable bindings won't be up to date until you type a new value, which could result in a very bad and confusing user experience if your form is invalid because some of the controls/variables that you updated before the page fully loaded are registering as null.

**Comment by zanettin** [comment]
same happens on button clicks with latest webpack version. I can click on any button, but after loading the app, nothing is propagated.

**Comment by jeffwhelpley** [comment]
There are two separate issues here.

@gdi2290 I may be wrong, but it looks like we are not using preboot with the universal-starter. Shouldn't we be passing in `preboot: true` here:

https://github.com/angular/universal-starter/blob/master/src/server.ts#L16

The second issue, however, is that even after getting this working, there is a potential issue with components trying to use an input value during the client side initial render. Let's do this. first, Patrick, let's get the renderToStringWithPreboot working (i.e. passing in the option to ng2engine) and then we can discuss the secondary problem.

**Comment by zanettin** [comment]
@jeffwhelpley thanks for your reply. the preboot flag is set to true on the server.ts file (L:31) https://github.com/angular/universal-starter/blob/master/src/server.ts. I'm using the angular Class example provided here => https://github.com/angular/universal-starter (webpack version). thanks a lot for your work on this!

**Comment by gdi2290** [comment]
can you try latest?

**Comment by zanettin** [comment]
Hi @gdi2290 

thanks for your action on this issue! I can't get a working example on angular-universal-preview 0.70.7.
what I've tried:

- started web app
- toggled network to DLS (2Mb/s)
- changed "Angular" in the input to "random"
- waited till load completed

expectation: text over the input should be "random"
result: my input was overwritten to "Angular2" and the title above did not changed.

setup: node 5.6.0, npm 3.6.0, branch on master

thanks again for you help.

**Comment by gdi2290** [comment]
preboot was set to false can you change it back https://github.com/angular/universal-starter/commit/c6995a7a0321e74a283048fe8ab5d954d68b74f4

**Comment by zanettin** [comment]
Thanks for your quick reply.
With preboot set to true to only thing that changes is, that at the end of the loading cycle my input value is still the entered one. but the title does not update.

**Comment by gdi2290** [comment]
I added a feature to provide server only components so I made a Title directive that replaces the initial title value
https://github.com/angular/universal-starter/blob/master/src/server-only-app/server-only-app.ts#L3...L9
you may want to delete it

**Comment by zanettin** [comment]
Hi Patrick

I think you've misunderstood me. With "title" I meant the binded value right above the input test "Hello, Angular2!". This should update to the input value, right? It does, but not if you change something during the load cycle. What I expect here is this:

- I type something in the input
- load cycle completes
- preboot updates "Hello, XXXX" to what I've typed in the input

Thanks again.

**Comment by zanettin** [comment]
With angular2 beta 11 and universal preview 0.82.1 can I confirm, that preboot works as expected. thank you very much for that!

**Comment by gdi2290** [comment]
@zanettin thanks for checking. I'll close this unless someone feels there is still an issue please reopen it
