### ISSUE TITLE
Error adding ngx-bootstrap

### ISSUE THREAD

**Issue by viktorstaikov** [angular/universal-starter#391]
Hi,
I'm migrating my business logic from existing project to this starter.
I'm using ngx-bootstrap for bootstrap components (Dropdown, Carousel, Modal).
They are all imported at app.module.ts.
The project is built, but when starting I get the following errors:

- for Carousel from ngx-bootstrap added as `CarouselModule.forRoot(),`
`Error: Unexpected value '[object Object]' imported by the module 'AppModule'`

**Comment by halben** [comment]
Seeing same issue when importing "ModalModule" in app.module.ts

**Comment by viktorstaikov** [comment]
The problem was due to ngx-bootstrap directly depending on Angular 4 and I was using Angular 2 (as per this starter). When upgraded to Angular 4, it has compiled properly.
