### ISSUE TITLE
The views are not swapped after initial render

### ISSUE THREAD

**Issue by viktorstaikov** [angular/universal-starter#393]
Hi,
For some reason the static view returned from the server is not swapped with the client view.
I suspect that, because two reasons:
1. I have _console.log('hi')_ inside _ngAfterViewInit_ which is logging only in the server log, but not in the browser.
2. There is a simple button which has _onclick_ event to update some text. The handler is not working (this is either with _preboot: true_ and _preboot: false_).

**Comment by MarkPieszak** [comment]
Do you have JavaScript disabled?

**Comment by viktorstaikov** [comment]
@MarkPieszak JS was definitely enabled.
Actually, I managed to fix it by changing the server routing from:
`
app.get('/', ngApp);
routes.forEach(route => {
  app.get(`/${route}`, ngApp);
  app.get(`/${route}/*`, ngApp);
});
app.get('*', function (req, res) {
  res.setHeader('Content-Type', 'application/json');
  var pojo = { status: 404, message: 'No Content' };
  var json = JSON.stringify(pojo, null, 2);
  res.status(404).send(json);
});
`
to
`
app.get('*', ngApp);
`
