### ISSUE TITLE
How add a translate module to universal starter?

### ISSUE THREAD

**Issue by moslemezati** [angular/universal-starter#395]
I use this repository to our project but I can't add module as easy as AngularJs for example I need to add `ngx-translate` but after I added as its document installation for aot it showed me 
`
Unexpected value 'TranslateModule' imported by the module 'AppModule'
`
How could I add module to this project?

**Comment by peterpeterparker** [comment]
So, I lost half a day figuring out how to use ngx-translate with universal-starter, therefore, find out here how I achieve it, maybe it will help you solve your problem.

1. install ngx-translate

     npm install @ngx-translate/core --save
     npm install @ngx-translate/http-loader --save

2. install copy-webpack-plugin

     npm install copy-webpack-plugin --save-dev

3. create folder and translation file `src/assets/i18n/en.json` containing for example

    {
       "TEST": "Super super"
    }

4. in webback.common.js add a copy plugin to copy the translations file to the dist/output directoty

     const copyWebpackPlugin = require('copy-webpack-plugin');
     
     plugins: [
        new copyWebpackPlugin([
             {
               from: './src/assets/i18n/en.json',
               to: './assets/i18n/en.json'
             }
           ])
         ]

5. if you run your server, you gonna face maybe like me an error on the client side telling you that `fs` isn't found, therefore in webpack.client.js add the following:

     node: {
        fs: 'empty'
     }

6. app.module.ts:

     export function exportTranslateStaticLoader(http: HttpClient) {
        return new TranslateHttpLoader(http, './assets/i18n/', '.json');
     }

    imports: [
         HttpClientModule,
         TranslateModule.forRoot({
        loader: {
          provide: TranslateLoader,
          useFactory: exportTranslateStaticLoader,
          deps: [HttpClient]
        }
      }
       )
      ]

7. browser-app.module.ts:
 
     imports: [TranslateModule.forChild()]

8. server-app.module.ts:

     export function translateFactory() {
        return new TranslateUniversalLoader('./dist/assets/i18n', '.json');
      }

      imports: [
          TranslateModule.forRoot({
             loader: {
              provide: TranslateLoader,
               useFactory: translateFactory
          }
        })
     ]

9. create a new service translateUniversalLoader

    ng g service translateUniversalLoader

10. overwrite the content of this service with the following code:

     import {Observable} from "rxjs/Observable";
     import {TranslateLoader} from '@ngx-translate/core';
     const fs = require('fs');
     
     export class TranslateUniversalLoader implements TranslateLoader {
       constructor(private prefix: string = 'i18n', private suffix: string = '.json') {}
         
       public getTranslation(lang: string): Observable<any> {
         return Observable.create(observer => {
     observer.next(JSON.parse(fs.readFileSync(`${this.prefix}/${lang}${this.suffix}`, 'utf8')));
           observer.complete();
         });
       }
     }

11. finally in app.component.ts:

    ngOnInit() {
         this.translateService.setDefaultLang('en');
         this.translateService.use('en');
     }

Hope it gonna help you or someone.

**Comment by fircus** [comment]
thank you peterpeterparker, you saved me

**Comment by fircus** [comment]
but, peterpeterparker, there is one moment..........once the project has built firstly, everything works fine, but when the project livereloads after some changes, I'm getting error "Cannot find module "fs""

**Comment by peterpeterparker** [comment]
@fircus so far I didn't used live reload that's why maybe I didn't face the problem. But that isn't too bad no?

**Comment by Scipionh** [comment]
Would that be feasible to have a similar solution for the server side ?

**Comment by peterpeterparker** [comment]
@nogo0d 

for the module and ts part you could have a look to the following couple of posts, I noticed that my solution was a bit glitchy and had to make some improvements, maybe that could helps you?

https://github.com/ngx-translate/core/issues/754

also since then I have migrated to the angular cli, so not sure anymore that I still use the webpack part of what I described above

**Comment by nogo0d** [comment]
@peterpeterparker 

Will take a look TY

**Comment by nogo0d** [comment]
@peterpeterparker 

Hmm. I can't put this thing working. (Really don't know how to start this...)
This internationalization feature, shouldn't be a really simple task to add to a project?  Is there any way to talk to you privately?! (Really sorry to bother you) :|

**Comment by peterpeterparker** [comment]
ngx-translate is generally easy to include, it's just that using universal make things at first a bit more tricky

your project is open source? could you link it here?

or would you like to open a stackoverflow issue, document it, and link it here?

**Comment by nogo0d** [comment]
@peterpeterparker 

The project itself is not open-source, but because it is a really early version I can put it there but basically I didn't put anything new. Just followed this: https://github.com/angular/universal-starter

The repository I'm working on:
https://github.com/nogo0d/angular-universal-example

If you could give me some lights I would appreciate.

**Comment by nogo0d** [comment]
Yes, right.

I'm just trying to find a resource to implement ngx-translate with angular-universal, but I'm not being able to find that..

**Comment by peterpeterparker** [comment]
Well when it comes to me, this issue and the one I told you above are what I did document.

Have a try and then post your issues, in case you face some, on Stackoverflow. Feel free to link them here and ping me if it happens.

**Comment by nogo0d** [comment]
Hmm.. OK. Will dig a little more. TY for everything,

**Comment by takahser** [comment]
thanks @peterpeterparker, this was very helpful!
for **angular 6**, the complementary instructions are located here: https://github.com/ngx-translate/core/issues/754#issuecomment-387022945

**Comment by peterpeterparker** [comment]
@takahser cool and thx for having linked the complementary "instructions" 👍

**Comment by RadouaneRoufid** [comment]
Hi,

Thank you @peterpeterparker  for you solution. However, I have a problem. My html code is rendered without translation from server side. Below my configuration : 

translate-server-loader.ts
```
import {TranslateLoader} from '@ngx-translate/core';
import * as translationAr from 'assets/i18n/ar.json';
import * as translationFr from 'assets/i18n/fr.json';
import {Observable, of} from 'rxjs';

const TRANSLATIONS = {
    ar: translationAr,
    fr: translationFr,
};

export class TranslateServerLoader implements TranslateLoader {
    constructor() {
    }

    public getTranslation(lang: string): Observable<any> {
        return of(TRANSLATIONS[lang]);
    }
}

export function translateFactory() {
    return new TranslateServerLoader();
}
```
app.server.module.ts
```
import {translateFactory} from './app/modules/core/services/translate-server-loader.service';

@NgModule({
    imports: [
        AppModule,
        ServerModule,
        ModuleMapLoaderModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: translateFactory
            }
        })
    ],
    bootstrap: [AppComponent],
})
export class AppServerModule {
}
```
translate-browser-loader.service.ts
```
export class TranslateBrowserLoaderService implements TranslateLoader {
    constructor(private prefix = 'i18n',
                private suffix = '.json',
                private http: HttpClient) {

    }

    public getTranslation(lang: string): Observable<any> {
        return new TranslateHttpLoader(this.http, this.prefix, this.suffix).getTranslation(lang);
    }
}
```

app.module.ts
```

export function exportTranslateStaticLoader(http: HttpClient) {
    return new TranslateBrowserLoaderService('/assets/i18n/', '.json', http);
}
TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: exportTranslateStaticLoader,
                deps: [HttpClient]
            }
        })

```

In my app.component.ts, I'm initializing translate service. This seems not be taken

```
public ngOnInit(): void {
        this.translateService.setDefaultLang(Locale.FRENCH.shortcut);
        this.translateService.use(Locale.FRENCH.shortcut);
}
```
My html code is being rendered as 
`<h1>ng-reflect-translate="">home.title</h1>`

and then a http request call is made to fetch the language and the text is being translated. 

Any idea why this does not work as expected ?

Thank you.

**Comment by RadouaneRoufid** [comment]
The code behind h1 is `<h1 translate>home.title</h1>` (I also tried <h1>{{'home.title' | translate}}</h1>) and the value of `Locale.FRENCH.shortcut` is `fr`.

It seems like the initialization of translateService in app.component.ts is not being applied. I verified in server side, that the translation are correctly found. But the html code is not translated.

**Comment by peterpeterparker** [comment]
Maybe, I based my implementation on https://github.com/angular/universal-starter

**Comment by RadouaneRoufid** [comment]
After struggling for 3 days, I found that the problem was due to the version of `@angular-devkit/build-angular`, and `@angular/cli` and `webpack-cli`.

My previous package.json has this as devDepencies ( translation in universal not working)
```
"@angular-devkit/build-angular": "0.7.0",
    "@angular/cli": "^6.2.3",
    "@angular/platform-server": "^6.0.0",
    "@angular/compiler-cli": "^6.1.7",
    "@types/googlemaps": "^3.30.0",
    "@types/jasmine": "~2.8.0",
    "@types/jquery": "^2.0.43",
    "@types/lodash": "^4.14.88",
    "@types/node": "^6.0.92",
    "copy-webpack-plugin": "^4.5.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.7.2",
    "protractor": "~5.3.0",
    "ts-loader": "^5.1.0",
    "ts-node": "^5.0.1",
    "tslint": "^5.9.1",
    "typescript": "2.7.2",
    "webpack": "4.19.1",
    "webpack-cli": "^3.1.1"
}
```

It works now after changing it to 
```

"devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "^6.0.0",
    "@angular/compiler-cli": "^6.1.7",
    "@angular/platform-server": "^6.0.0",
    "@types/googlemaps": "^3.30.0",
    "@types/jasmine": "~2.8.0",
    "@types/jquery": "^2.0.43",
    "@types/lodash": "^4.14.88",
    "@types/node": "^6.0.92",
    "copy-webpack-plugin": "^4.5.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.7.2",
    "protractor": "~5.3.0",
    "ts-loader": "^5.1.0",
    "ts-node": "^5.0.1",
    "tslint": "^5.9.1",
    "typescript": "2.7.2",
    "webpack-cli": "^2.0.14"
  }

```

Any explanation of why this does not work with latest version ?
