### ISSUE TITLE
view source code hit not coming on server

### ISSUE THREAD

**Issue by Skillnter** [angular/universal-starter#396]
when i downloaded the starter kit and started it, whenever i used to hit "CTRL + U"(view source code of page) the server used to get hit, but its not getting any hits now whenever i view the source code. 

> I haven't updated any of the files in the SRC folder except for the ones in the +app folder

What could be the possible issue? I tried troubleshooting myself but i guess i am helpless at the moment. Can anyone help me with the problem? I need to understand the workflow and the functions through which the flow is passing through. Because of this, whenever i see the source code by hitting 'ctrl + u', i see only the index.html page and not the prerender ones.

Is this issue related to universal_cache problem? but i used to get that universal_cache missing problem before too but i was able to see the prerender pages. Anyways i need lil help with the universal_cache missing problem too.

please help me out..... I cant updagrade to 4.0 right now and need to solve this issue in rush.

**Comment by gdi2290** [comment]
please follow https://github.com/angular/universal-starter/pull/358 for angular 4
