### ISSUE TITLE
Add MongoDB access to universal-starter project

### ISSUE THREAD

**Issue by prt101g** [angular/universal-starter#398]
I have been trying to figure out how to change it so that it communicates with a real database rather than a mocked cache and backend.

What is the best way to edit the code so that it connects to a real MongoDB database in the backend for queries and updates?  Where would I start?

See https://stackoverflow.com/questions/44633772/add-mongodb-access-to-universal-starter-project

**Comment by Toxicable** [comment]
I don't think this is the appropriate place for a MongoDB example
