### ISSUE TITLE
How to put the build on my server?

### ISSUE THREAD

**Issue by torugor** [angular/universal-starter#399]
I am really confused with the process of building this project.
I used to have an angular2 project I wanted to put SEO TAGs dinamically.

I sucessfully converted it to universal and it is running correctly.
npm run build works smoothly but it created on dist folder 2 folders: client and server. Neither has an index.html file to be placed on my webserver. I am used to run npm build.prod and have on /dist/prod
all files i need to upload to my server. Now I cant see such files anywhere.

How does this /dist/client and /dist/server convert into something I can upload to my webserver in order to be used by my users?

**Comment by torugor** [comment]
Ok After reading a lot about webpack i figured out that the client folder built needs to be dumped into www folder and the index.html should be placed on my subfolder on linux server. I have no idea where to dump the server files. And thing is...it is bad because i want this angular site to be in a subfolder not in www.
So how can i change it to the www and where should i put the server folder?

**Comment by torugor** [comment]
My structure is 
www (i have another simple html site in here...its a landing page that goes to angular website)
www/guia-medico (here is where i want to put my files. Here is my angular site.)

**Comment by nietopablo19** [comment]
the same case here.. can you resolve this problem?

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
