### ISSUE TITLE
Problems with build server

### ISSUE THREAD

**Issue by torugor** [angular/universal-starter#400]
My project builds ok on webstorm using `npm run build` and i can see it is all ok on `npm run start`.

When i go to the dist/server and use `node index.js` it starts the server ok
but when i go to localhost:3000 i receive this:

Error: Failed to lookup view "index" in views directory "src"
    at EventEmitter.render (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\express\lib\response.js:971:7)
    at C:\Projetos_WEB\docpadweb-guiamedico\dist\server\index.js:68886:13
    at ZoneDelegate.invoke (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\zone.js\dist\zone-node.js:232:26)
    at Zone.run (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\zone.js\dist\zone-node.js:114:43)
    at ngApp (C:\Projetos_WEB\docpadweb-guiamedico\dist\server\index.js:68885:79)
    at Layer.handle [as handle_request] (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Projetos_WEB\docpadweb-guiamedico\node_modules\express\lib\router\layer.js:95:5)

Here is my server.ts:

app.set('port', process.env.PORT || 3000);
app.set('views', __dirname);
app.set('view engine', 'html');
app.set('json spaces', 2);

app.use(cookieParser('Angular 2 Universal'));
app.use(bodyParser.json());
app.use(compression());

app.use(morgan('dev'));

function cacheControl(req, res, next) {
  // instruct browser to revalidate in 60 seconds
  res.header('Cache-Control', 'max-age=60');
  next();
}
// Serve static files
app.use('/assets', cacheControl, express.static(path.join(__dirname, 'assets'), {maxAge: 30}));
app.use(cacheControl, express.static(path.join(ROOT, 'dist/client'), {index: false}));

//
/////////////////////////
// ** Example API
// Notice API should be in aseparate process
import { serverApi, createTodoApi } from './backend/api';
// Our API for demos only
app.get('/data.json', serverApi);
app.use('/api', createTodoApi());

process.on('uncaughtException', function (err) {
  console.error('Catching uncaught errors to avoid process crash', err);
});

function ngApp(req, res) {

  function onHandleError(parentZoneDelegate, currentZone, targetZone, error)  {
    console.warn('Error in SSR, serving for direct CSR');
    res.sendFile('index.html', {root: './src'});
    return false;
  }

  Zone.current.fork({ name: 'CSR fallback', onHandleError }).run(() => {
    res.render('index', {
      req,
      res,
      // time: true, // use this to determine what part of your app is slow only in development
      preboot: false,
      baseUrl: '/',
      requestUrl: req.originalUrl,
      originUrl: `http://localhost:${ app.get('port') }`
    });
  });

}

/**
 * use universal for specific routes
 */
app.get('/', ngApp);
routes.forEach(route => {
  app.get(`/${route}`, ngApp);
  app.get(`/${route}/*`, ngApp);
});

app.get('*', function(req, res) {
  res.setHeader('Content-Type', 'application/json');
  var pojo = { status: 404, message: 'No Content' };
  var json = JSON.stringify(pojo, null, 2);
  res.status(404).send(json);
});

// Server
let server = app.listen(app.get('port'), () => {
  console.log(`Listening on: http://localhost:${server.address().port}`);
});

**Comment by torugor** [comment]
Is it me or this project has no one answering questions anymore? did this stop?

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
