### ISSUE TITLE
Re-rendering occurs with non-lazy loaded routes

### ISSUE THREAD

**Issue by valevalorin** [angular/universal-starter#402]
Cloned the project recently. All I've done is remove some of the initial routes/modules/components (about, todo, lazy) and added one of my own. I'm just trying to load the home module and I'm getting a re-render:

https://i.gyazo.com/f20b3eb148229890690d35a1deecfbf6.mp4

Looking through the issues it seems like normally only occurs during lazy loaded routes. I'm not sure what I could've done to make this happen. Any ideas?

**Comment by gdi2290** [comment]
you need to preload the lazy routes before loading the main app

**Comment by valevalorin** [comment]
Sorry, maybe I wasn't explicit enough. I have NO lazy routes on my
application.

**Comment by gdi2290** [comment]
which version of Angular are you running?

**Comment by valevalorin** [comment]
2.1.2

I've also pulled down the project fresh and after running npm install, npm start I get the same issue.

**Comment by gdi2290** [comment]
ok, yeah we need to update this repo to use Angular 4 with the latest changes

**Comment by valevalorin** [comment]
Alright, I'll upgrade my version and report back.

**Comment by gdi2290** [comment]
you can see the repo was upgraded in this PR if that helps
https://github.com/angular/universal-starter/pull/358
