### ISSUE TITLE
Lazy Load not creating chunk bundle in Universal

### ISSUE THREAD

**Issue by maphi88** [angular/universal-starter#403]
Hi , My routing file is somewhat
```
  { path: '', component:HomeComponent, data: { name:'Home', type:'Page' }},
  { path:'parenting/admin',
     loadChildren: './typescripts/blogger/blogger.module#BloggerModule',
     data: { name:'User', type:'Detail' }
  },
export const Mc4kRoutingModule :ModuleWithProviders = RouterModule.forRoot(routes);
```
My BloggerRoutingModule is somewhat like

```
@NgModule({
  imports: [
    RouterModule.forChild([
        {path:'',component: BloggerPrivateComponent},
    ])
  ]
})
export class BloggerRoutingModule { }
```
on running `ng build --prod` Only one client bundle is generated instead of chunk for lazy load modules

**Comment by Toxicable** [comment]
Are you still getting this error?
We have also just added a CLI example which has AOT chunk generation working fine, would you mind trying that?

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.

**Comment by maphi88** [comment]
@Toxicable  I have created 2 routing instead, one for server (app.node.server) and one for browser(app.browser.server). This allows server side rendering as well as client lazy load. The main issue which caused single page generation was cause there was a component which was used in other page as well, have separated it to module and included it.
