### ISSUE TITLE
universal-starter  is not working on build:prod.

### ISSUE THREAD

**Issue by webdeveloperneeraj** [angular/universal-starter#407]
I have cloned universal-starter and npm install then i am using
npm run build:prod
i am getting this warning and got stuck.
WARNING in ./node_modules/express/lib/view.js
    80:29-41 Critical dependency: the request of a dependency is an expression

  
Child html-webpack-plugin for "index.html":
           [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 213 bytes {0} [built]

**Comment by RaphaelYan** [comment]
Hello @webdeveloperneeraj, have you found how to fix this ?
