### ISSUE TITLE
Live reload not working

### ISSUE THREAD

**Issue by fis-dan-wnuk** [angular/universal-starter#408]
Hello,

I am not sure if this is expected or not - but I am running this application (npm start and npm run watch in two separate windows), and when I make a change to the template in the app component or the home view component, the change is not reflected in the browser until I refresh the page. I do see the --watch is detecting the changes and the server appears to be reloading them, but the browser does not get updated.

Is this expected, or should live reload be working out of the box? I saw a couple of closed issues related to live reload, but I'm not sure if they reflect the current status as some are a year old at this point.

Thanks,

Dan

**Comment by peterpeterparker** [comment]
Just cloned the repo, I noticed the same behavior, a refresh in the browser seems to be needed.

But furthermore it looks like that changes in `html` pages are noticed but that any changes to `typescript` files aren't. Did you noticed the same behavior @fis-dan-wnuk ?

**Comment by fis-dan-wnuk** [comment]
I did not notice that behavior - if I refresh the browser I am able to see both TS and HTML file changes. Neither TS nor HTML files are live reloading for me.

**Comment by peterpeterparker** [comment]
thx for the feedback...are we both doing something wrong?

**Comment by fis-dan-wnuk** [comment]
Not sure. There isn't any use of the LiveReloadPlugin in the repo so you could try adding that into the project - saw that recommended in an older issue. I didn't get very far, though I didn't spend much time on this. I was hoping to get a response here before looking more at live reload. I've got another problem trying to integrate an internal project and getting ReferenceError: window is not defined from the AoT compiler, so trying to track that down has been taking up most of my time.

Here's stuff I added in webpack.common.js if it helps, though this did not get it working for me.

`const LiveReloadPlugin = require('webpack-livereload-plugin');`

`new LiveReloadPlugin({
	  appendScriptTag : true
	})`

**Comment by peterpeterparker** [comment]
thx for the feedback. me too right now I'm "fighting" with something else respectively how to load dynamically the language I want at boot time with ngx-translate

about your `window`error, have you try to encapsulate your code within `isPlatformBrowser`? see `universal gotchas` https://github.com/angular/universal for example

**Comment by Scipionh** [comment]
Is that something you plan to fix ?

**Comment by MarkPieszak** [comment]
If you guys can, use the `cli` starter example here (as all of this is working there), as the other one is just an example on how to get started with custom webpack configuration, and likely won't get worked on anymore.
