### ISSUE TITLE
AOT not work!

### ISSUE THREAD

**Issue by wizardnet972** [angular/universal-starter#409]
I'm running `npm build:aot`
Then: `cd dist`
run: `node server.js`
goto: `http://localhost:8000`

I get error message:
Error: Failed to lookup view "../dist/index" in views directory "src"

**Comment by wizardnet972** [comment]
Its because on the `main.server.ts`
is should set to `dist` instead `src` when compile to AOT/PROD mode.

app.set('views', 'dist');

and it's works!

**Comment by Toxicable** [comment]
if you've fixed your problem can you close this issue.
Otherwise might I suggest trying our new CLI example, it has AOT working fine there
