### ISSUE TITLE
Add styles.css

### ISSUE THREAD

**Issue by MGazi42** [angular/universal-starter#412]
I don't know why this repo has not use syles.css but when I need to use UI Component libraries like primeng, Teradata or any other UI library, the UI library wants to add some style.css

Please add style.css

**Comment by argirok** [comment]
+1
Did you manage to add styles? I used to have an 'assets' folder but I cannot make it work with the latest version.

**Comment by Toxicable** [comment]
This repo now has a CLI example which has a `styles.css`
