### ISSUE TITLE
feat: upgrade to CLI

### ISSUE THREAD

**Issue by Toxicable** [angular/universal-starter#413]
Now that the CLI has experimental support for Universal it might be a good point to start thinking about upgrading this repo to use is.
Once https://github.com/angular/universal/tree/master/modules/ng-module-map-ngfactory-loader is published the CLI should be able to achieve the same functionality as the current starter does

**Comment by glebmachine** [comment]
Yeah, could you please help CLI team to achieve same functionality
I'm frustrating about universal support in cli

**Comment by Toxicable** [comment]
@glebmachine With the exception of lazy loading as mentioned above the CLI can do Universal
See here for more info https://github.com/angular/angular-cli/wiki/stories-universal-rendering

**Comment by glebmachine** [comment]
Yep, lazy loading is decision making feature(
-- 
Gleb Mikheev
CTO

*Beta Digital Production*

3 floor, 8th entrance,  pr-kt Mira 119 building 452, Moscow, Russia

Mobile:  +7 (916) 118-28-21
Skype:   glebmikheev

www.betaagency.ru
www.facebook.com/betadigitalproduction

**Comment by Toxicable** [comment]
You can build https://github.com/angular/universal/tree/master/modules/ng-module-map-ngfactory-loader from the source and use it yourself, it's not ideal but it's what i've been doing

**Comment by glebmachine** [comment]
Working on it today for all day.
I have integrated webpack from universal starter to blank cli project with
lazyloading.

Tomorrow will work on my working project.
I will share my results soon

Thank you!)
-- 
Gleb Mikheev
CTO

*Beta Digital Production*

3 floor, 8th entrance,  pr-kt Mira 119 building 452, Moscow, Russia

Mobile:  +7 (916) 118-28-21
Skype:   glebmikheev

www.betaagency.ru
www.facebook.com/betadigitalproduction
