### ISSUE TITLE
only able to set TRANSFER_STATE in AppComponent

### ISSUE THREAD

**Issue by NqCompiler** [angular/universal-starter#416]
Hey,

setting values via TransferState service (cache) is only possible in the AppComponent, but retrieving them also in other components and services. 
I am loading an Array of some data, but it's not always the same data (depends on the route etc.). I can't always tell from the AppComponent which data it should load from the backend and set for the cache (besides the fact that it would be also a big mess in the AppComponent itself if I try).

Is it possible to to set these caching values from other components/services than the AppComponent ?

Thanks and keep up the great work!

**Comment by denisyilmaz** [comment]
I use the TransferState Service in other Components and Resolvers successfully to set and get data. 

As an example here is my PageResolver I use for retrieving API Data and add it to TransferState. The Resolver looks if the Data is already loaded (via Server and added to TransferState), otherwise it loads the data via HTTP Request and sets it for later use to TransferState (if the page is loaded on Clientside).

```typescript
import { Injectable, PLATFORM_ID, Inject } from '@angular/core';
import { isPlatformServer } from '@angular/common';
import { Resolve, RouterStateSnapshot, ActivatedRouteSnapshot } from '@angular/router';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Observable }     from 'rxjs/Observable';
import 'rxjs/Rx';

import { TransferState } from './../shared/modules/transfer-state/transfer-state';

@Injectable()
export class PageResolver implements Resolve<any> {
    constructor(
        private cache: TransferState,
        private http: HttpClient,
        @Inject(PLATFORM_ID) 
        private platformId: Object
    ) {}
    resolve(
        route: ActivatedRouteSnapshot,
        state: RouterStateSnapshot
    ): Observable<any>|Promise<any>|any {
        return new Promise((resolve, reject) => {
            let slug = route.params['slug'];
            let projectCacheSlug = 'page-' + slug;
            if(this.cache.get(projectCacheSlug)) {
                resolve()
            } else {
                let port = process.env.PORT || 8000
                let url = (isPlatformServer(this.platformId)) ? 'http://localhost:' + port : ''
                this.http
                    .get( url + '/api/pages/' + slug)
                    .retry(5)
                    .subscribe(
                        res   =>    {
                            this.cache.set(projectCacheSlug, res);
                            resolve();
                        },
                        (err: HttpErrorResponse) => {
                        if (err.error instanceof Error) {
                            // A client-side or network error occurred. Handle it accordingly.
                            console.log('An error occurred:', err.error.message);
                        } else {
                            // The backend returned an unsuccessful response code.
                            // The response body may contain clues as to what went wrong,
                            console.log(`Backend returned code ${err.status}, body was: ${err.error}`);
                        }
                        }
                    )
            }
        })
    }
}
```

Hope that helps.

**Comment by NqCompiler** [comment]
Thanks for your answer. I realized it is also working in other Components, even services.
I am working with the watcher (npm run watch) and you should always restart your local server as well (usually it's doing this on his own, somehow in my case not).
But I am still facing some issues with setting the cache in async operations. Can't figure out yet what the problem is, but I'll keep looking and may update this issue

**Comment by NqCompiler** [comment]
Ok so I was using my own Http Service, which was extending the Http Class from @angular/router. In order to make it work correctly I had to insert it via a useFactory function. Somehow this was causing my TranferState not to work. Makes sense because I was injecting a TransferState in die dependencies (deps), which is probably a new instance and therefore different.
