### ISSUE TITLE
npm watch not runing

### ISSUE THREAD

**Issue by ctwhome** [angular/universal-starter#42]
after clone the repository and do "npm install",  "npm watch" does not work.

**Comment by bjwyse** [comment]
try 'npm run watch'

**Comment by manekinekko** [comment]
@ctwhome actually, you need to run both commands:
```bash
$ # in shell #1
$ npm start
$ # in shell #2
$ npm run watch
```
FYI, you need to refresh the browser manually.

**Comment by manekinekko** [comment]
@ctwhome any news about issue?

**Comment by gdi2290** [comment]
this is a problem with npm. to run npm scripts you must use the command `npm run` so in this case it's `npm run watch`. Please reopen if this is still an issue
