### ISSUE TITLE
AOT. Module build failed: Invalid CSS after...

### ISSUE THREAD

**Issue by fircus** [angular/universal-starter#420]
Hello, When I try to execute "build:aot" command, I get error "Module build failed: Invalid CSS after "...lint:disable */": expected 1 selector or at-rule, was "export const styles"" for all my ".scss" files. Has anybody faced this trouble?
My loaders:
{test: /\.css$/, use: [{loader: 'raw-loader'}]},
{test: /\.scss/, use: [{loader: 'raw-loader'}, {loader: 'sass-loader'}]},

**Comment by MarkPieszak** [comment]
It looks like you might of just setup the webpack loaders wrong for that, can you take a look at this comment here to set it up? https://github.com/angular/universal-starter/issues/320#issuecomment-269865804
