### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by Scipionh** [angular/universal-starter#421]
npm ERR! notarget No compatible version found: evp_bytestokey@^1.0.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.2, 1.0.1, 1.0.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'browserify-aes'
npm ERR! notarget

**Comment by denisyilmaz** [comment]
as I understand it you have to switch to either `/cli` or `/custom-webpack` folder as there is no main package.json in the main folder. see the PR #422 for the new readme.

**Comment by Scipionh** [comment]
The error actually happens from both /cli and /custom-webpack

**Comment by denisyilmaz** [comment]
strange. I just cloned the repo 2 minutes ago and successfully installed node_modules in the `/custom-webpack`folder.
