### ISSUE TITLE
No provider for InjectionToken REQUEST!

### ISSUE THREAD

**Issue by blochaou** [angular/universal-starter#423]
Hello
I try to use angular universal cli in a muti tenant application. 
I created a service and inject the REQUEST token.

When i provide this service with  in the AppModule i get the error :
 **No provider for InjectionToken REQUEST!**
in chrome console

app.module.ts

`
@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
  ],
  imports: [
    
    BrowserModule.withServerTransition({appId: 'my-app'}),
    RouterModule.forRoot([
      { path: '', component: HomeComponent, pathMatch: 'full'},
      { path: 'lazy', loadChildren: './lazy/lazy.module#LazyModule'}
    ]),
   HttpModule
  ],
  providers:[
    AppService,
    {
      provide: APP_INITIALIZER,
      useFactory: initConfiguration,
      deps: [AppService],
      multi: true
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { 

}
`

AppService.ts
`
@Injectable()
export class AppService {
    _currentSite: any;
    
    constructor( private injector:Injector,
            @Inject(REQUEST) private dom: any,
            private http: Http,) {

    }

    load() {
        return new Promise((resolve, reject) => {
           // this.http.get('http://' + this.host + '/assets/sites/' + this.hostDomain + '.json')
            this.http.get('http://electrogo.com:8000/assets/sites/electrogo.com.json')
            .map(res => res.json())
            .catch((error: any) => {
                console.error(error);
                return Observable.throw(error.json().error || 'Server error');
              })
            .subscribe((site_data) => {
              this._currentSite = site_data;
              resolve(true);
            });
        });
    }
}
`

**Comment by MarkPieszak** [comment]
Can you try to get `REQUEST` by putting `Injector` in your constructor dependencies, and grabbing REQUEST via `Injector.get(REQUEST)` ?
