### ISSUE TITLE
Styles and js bundle not being rendered

### ISSUE THREAD

**Issue by ishankhare07** [angular/universal-starter#426]
I referred to the https://github.com/angular/universal-starter/blob/master/cli/server.js file.
I can render the html properly, but there are no styles being rendered. Also it does not contain any bundles related to my angular code (js files) or others like polyfills, bundle etc.

How do I fix this?

**Comment by Toxicable** [comment]
How are you running the solution?

**Comment by CaerusKaru** [comment]
I think the problem is here:
https://github.com/angular/universal-starter/blob/393879d29dc906e844e167e698f4f923c0c087f2/cli/server.ts#L39

Since the renderer is relying on the index.html in `src`, it's not loading any of the styles that get built into the final static `index.html` by the CLI. It should be changed to this:
```
app.set('views', join(DIST_FOLDER, 'browser'));
```

**Comment by CaerusKaru** [comment]
It looks like this was unintentional though, because the proper template is loaded, but not used:
https://github.com/angular/universal-starter/blob/393879d29dc906e844e167e698f4f923c0c087f2/cli/server.ts#L20

**Comment by rluberda** [comment]
Not sure if this help you. 
Today I worked on build:dynamic & serve:dynamic option. 
Out of the box when I run it I noticed html without style/js. 
After reviewing some code I figured out that webpack portion is not finished. 

Below is quick solution with 2 plugins.

```
// Work around for https://github.com/angular/angular-cli/issues/7200
var HtmlWebpackPlugin = require('html-webpack-plugin');
var HtmlWebpackExcludeAssetsPlugin = require('html-webpack-exclude-assets-plugin');

const path = require('path');

module.exports = {
  entry: {
    // This is our Express server for Dynamic universal
    server: './server.ts',
    // This is an example of Static prerendering (generative)
    prerender: './prerender.ts'
  },
  target: 'node',
  resolve: {
    extensions: ['.ts', '.js'],
    // alias: {
    //   'main.server': path.join(__dirname, 'dist', 'server', 'main.bundle')
    // }
  },
  // Make sure we include all node_modules etc
  externals: [/(node_modules|main\..*\.js)/,],
  output: {
    // Puts the output at the root of the dist folder
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  },
  module: {
    rules: [
      { test: /\.ts$/, loader: 'ts-loader' }
    ]
  },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'dist/browser/index.html',
            output: 'dist',
            inject: 'head',
            excludeAssets: [/server.js/, /prerender.js/]
        }),
        new HtmlWebpackExcludeAssetsPlugin()
    ]
}
```

Above script duplicate dist/browser/index.html head and create new index.html file inside dist
Then change server.ts to point to newly created index file.

```
app.get('*', (req, res) => { 
  res.render('../dist/index', { req });
});
```

Hope this make sens t and give you some help.

**Comment by MarkPieszak** [comment]
@CaerusKaru is spot on, @rluberda all you need is the update in here that he mentioned: https://github.com/angular/universal-starter/commit/df3159406e40e3963c1e315346b1d50f9009f57b

Get latest for the starter also, a few other good updates were put in this morning.

**Comment by iamonuwa** [comment]
@MarkPieszak thank you for prompt fix. Styles has been fixed but JS bundles are not rendering.

**Comment by MarkPieszak** [comment]
Which JS Bundles aren't rendering?
Are these JS files in an html file?

**Comment by iamonuwa** [comment]
@MarkPieszak the angular bundle scripts. None of them is loading...

**Comment by MarkPieszak** [comment]
The regular script bundle should be in the index file in dist/browser/index.HTML, they are done the normal angular-CLI way.

**Comment by iamonuwa** [comment]
@Toxicable I am not seeing the the scripts bundle on the index.html page when I run node dist/server

This is the bottom section of the generated html page.
There is no scripts there.
![image](https://user-images.githubusercontent.com/6551094/30822906-5b507784-a222-11e7-9098-a528425420dd.png)

**Comment by iamonuwa** [comment]
@MarkPieszak I am seeing them on the browser when I load with `cd dist/browser && http-server`, it works. But when I run `node dist/server` I get the error

**Comment by vijayswarnkar21** [comment]
Facing the same issue , I am getting all scripts files in index.html browser build but when it get served using angular universal  all the scripts excluded and only plane HTML file is being rendered.
