### ISSUE TITLE
HTTP requests happens both on server and client side

### ISSUE THREAD

**Issue by m98** [angular/universal-starter#429]
I'm using [Universal Starter CLI](https://github.com/angular/universal-starter/tree/master/cli), one of my pages makes an HTTP request to fetch an article's body when I watch the Chrome network tab, I see the same HTTP request is issued again on the client side, means one HTTP request is issued twice, _once on the server side and again on the client side_, and it cause a flicker for a short moment.

I read some other issued about the same problem here or on the Universal repository, but they were not proving helpful answer on how to solve this problem, I might solve the problem if there is a way to share variables between server and client, it seems that client side rebuild variables and set new values to them.
For example, when I have a variable and I do `variable++` on the service constructor, I get `1` from the `console.log(variable)` both on the server and client side.

@Toxicable Do you have any idea? Maybe you should add something to the **Universal Starter CLI**

**Comment by Toxicable** [comment]
an API is in design to solve this issue https://github.com/angular/universal/issues/791

**Comment by m98** [comment]
I just read that, it seemed you provided some solutions for it.
Hopefully, I can find a way to solve my problem until the API is ready to use.
Thanks @Toxicable

**Comment by Toxicable** [comment]
Untill the official API is done, there are a few alternatives 
https://github.com/angular/universal-starter/tree/master/custom-webpack/src/modules/transfer-state
https://www.npmjs.com/package/@ngx-universal/state-transfer

**Comment by Toxicable** [comment]
the PR for the offical one just opened here 
https://github.com/angular/angular/pull/19134

**Comment by m98** [comment]
Thank you
I need to upgrade to the newer version of Angular.
Do you know when is Angular next stable release?

By the way, is not there any way for sharing variables between server and client?

**Comment by Toxicable** [comment]
This API isn't available yet, the PR has not been merged.
Angular releases weekly builds
This API will allow for you to share variables from server to client

**Comment by m98** [comment]
I was thinking about a temporary trick, maybe we can watch the route change and don't make any requests if it's still the first route, and is the platform-browser :thinking:

**Comment by m98** [comment]
@Toxicable, I just saw your provided links about the alternatives, can't we implement them for the [universal-starter CLI](https://github.com/angular/universal-starter/tree/master/cli)?

Not sure if is it possible to use the [transfer-state ](https://github.com/angular/universal-starter/tree/master/custom-webpack/src/modules/transfer-state) on that used on Webpack?

I'll be glad to work on it if you can provide some help and if it's possible to use that!

**Comment by Toxicable** [comment]
Sure you can use those with the CLI, there's nothing special required to configure them, they're just not official API's

**Comment by m98** [comment]
Is not better if we can add it into the [universal-starter CLI](https://github.com/angular/universal-starter/tree/master/cli)?

**Comment by Toxicable** [comment]
No since there will be an official one soon enough. It would be confusing for us to provide one way to solve it then turn around a few days later and show another

**Comment by m98** [comment]
I'm using [transfer-state](https://github.com/angular/universal-starter/tree/master/custom-webpack/src/modules/transfer-state), and it seems to be a good temporary solution until the official API is ready to use.
Thanks @Toxicable
