### ISSUE TITLE
Prerender does not work with templateUrl or styleUrls

### ISSUE THREAD

**Issue by jongood01** [angular/universal-starter#43]
Components that have separate html and css files and reference them via templateUrl and styleUrls do not prerender but client-side still loads i.e. this doesn't work:
```typescript
@Component({
  selector: 'app',
  templateUrl: 'path/to/my/template.html',
  styleUrls: ['path/to/my/stylesheet.css'],
})
```
But this does:
```typescript
@Component({
  selector: 'app',
  template: `
<div>Here is my template</div>
`,
  styles: [`
   .classy {
        background: red;
   }
`],
```

**Comment by manekinekko** [comment]
@jongood01 can you give a link to your code?

**Comment by jongood01** [comment]
Here is the link to my repo:
https://Jongood01@bitbucket.org/Jongood01/shakecms.git

I have changed it to use multi line strings for the template and require
scss files for the styles. That is working but if you change the App
component to use app.html, it doesn't work. The app loads but not
prerendered.

**Comment by manekinekko** [comment]
Thanks @jongood01 
I reproduced your issue. However this is related to Universal not the starter. I'll open an issue in the universal repo on your behalf.

**Comment by manekinekko** [comment]
@gdi2290 I think we can close this issue. It's related to universal.
