### ISSUE TITLE
SCSS Files not converted on server side

### ISSUE THREAD

**Issue by jackbliss99** [angular/universal-starter#431]
Hello!

I have an angular universal app up and running, but the SCSS files that get imported are not first converted in to plain CSS. What this means is that the component-specific scss styling is not shown before the client bootstraps. From what I understand, this is due to an incompatibility with AoT and scss loading, possibly due to the ExtractTextPlugin? If someone could explain to me exactly why this doesn't work (which is somewhat surprising, as you'd think AoT would mean that the scss files got converted to css 'ahead of time'), or offer a solution, it would be much appreciated!

Here's tsconfig.json

    {
      "compileOnSave": false,
      "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
          "node_modules/@types"
        ],
        "lib": [
          "es2016",
          "dom"
        ]
      },
      "angularCompilerOptions": {
        "genDir": "./dist/ngfactory",
        "entryModule": "./src/app/app.module#AppModule",
        "skipMetadataEmit" : true
      }
    }

package.json

    {
      "name": "frontend",
      "version": "0.0.0",
      "license": "MIT",
      "scripts": {
        "ng": "ng",
        "build": "webpack",
        "test": "karma start ./karma.conf.js",
        "lint": "ng lint",
        "e2e": "protractor ./protractor.conf.js",
        "watch": "ng build --watch -op dist/",
        "start": "ngc && ts-node src/server.ts"
      },
      "private": true,
      "dependencies": {
        "@angular/animations": "^4.0.0",
        "@angular/common": "^4.0.0",
        "@angular/compiler": "^4.0.0",
        "@angular/core": "^4.0.0",
        "@angular/forms": "^4.0.0",
        "@angular/http": "^4.0.0",
        "@angular/platform-browser": "^4.0.0",
        "@angular/platform-browser-dynamic": "^4.0.0",
        "@angular/platform-server": "^4.4.0-RC.0",
        "@angular/router": "^4.0.0",
        "angular2-universal": "^2.1.0-rc.1",
        "body-parser": "^1.18.1",
        "core-js": "^2.4.1",
        "express": "^4.15.4",
        "preboot": "^5.0.0",
        "rxjs": "^5.4.1",
        "zone.js": "^0.8.14"
      },
      "devDependencies": {
        "@angular/cli": "1.2.4",
        "@angular/compiler-cli": "^4.0.0",
        "@angular/language-service": "^4.0.0",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "~3.0.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.0.4",
        "tslint": "~5.3.2",
        "typescript": "~2.3.3",
        "webpack-dev-server": "~2.4.5",
        "webpack": "~2.4.0",
        "autoprefixer": "^6.5.3",
        "css-loader": "^0.28.1",
        "cssnano": "^3.10.0",
        "exports-loader": "^0.6.3",
        "file-loader": "^0.10.0",
        "json-loader": "^0.5.4",
        "less-loader": "^4.0.2",
        "postcss-loader": "^1.3.3",
        "postcss-url": "^5.1.2",
        "raw-loader": "^0.5.1",
        "sass-loader": "^6.0.3",
        "script-loader": "^0.7.0",
        "source-map-loader": "^0.2.0",
        "istanbul-instrumenter-loader": "^2.0.0",
        "style-loader": "^0.13.1",
        "stylus-loader": "^3.0.1",
        "url-loader": "^0.5.7"
      }
    }

and app.component.ts

    import { Component } from '@angular/core';
    import { Router } from '@angular/router';
    
    @Component({
      selector: 'app-root',
      templateUrl: './app.template.html',
      styleUrls: ['./app.style.scss']
    })
    export class AppComponent {
    
      searchterm = "";
    
      constructor(
        private router: Router
      ){ }
    
      Search(){
        this.router.navigate(['search', this.searchterm]);
      }
    }

All the best,

Jack

**Comment by Jamie452** [comment]
+1

**Comment by poppo191** [comment]
@jackbliss99 Change style ext on .angular.json file

```
...
"defaults": {
      "styleExt": "scss", <- Change to scss
....
```

**Comment by MarkPieszak** [comment]
Did you change your angular-CLI json to indicate you're using scss now? It's CSS by default. Give that a shot.

**Comment by jackbliss99** [comment]
I did change it, and it still shows the unstyled content. In the source coming from the server, I get the following:


    <style ng-transition="Frontend">#header[_ngcontent-c0]{
      padding: 10px 30px;
      border-bottom: 1px solid #CCC;
      h1{
        color: #333;
      }
    }</style>

which is what's leading me to believe that the SCSS is not being correctly processed when the server side app builds.

**Comment by MarkPieszak** [comment]
Are you using the CLI demo here?
If you have it set to scss in the angular-cli.json, there shouldn't be any problems. This looks like it's coming from something you're manually bundling up ?

Closing for now as SCSS is working with the repo.
