### ISSUE TITLE
Relative path or get the location protocol and url for http

### ISSUE THREAD

**Issue by kalyan1102** [angular/universal-starter#432]
Hi,

I am trying to provide the relative path for the http but the server is complaining that its only support absolute URL. Is there any way I can pass the request URL dynamically? As window is not available I am not able to use location.protocol or url either.  Please point me to a working example.

Thanks in advance for the help

**Comment by kalyan1102** [comment]
@MarkPieszak can you please help me out? Thanks in advance

**Comment by Toxicable** [comment]
see https://github.com/angular/universal/issues/766

**Comment by kalyan1102** [comment]
@Toxicable thanks a lot. This helps
