### ISSUE TITLE
Double white page flash on page

### ISSUE THREAD

**Issue by amitjain28** [angular/universal-starter#436]
Double white page flash on pages when loading. it is clearly visible on Desktop and Mobile.
How can i remove it ? 
Is this due to AOT or angular pre-rendering ?

**Comment by MarkPieszak** [comment]
Do you have Http calls on that page?
You either need to setup the TransferState Http, or you need to setup your RouterModule options.

```typescript
RouterModule.forRoot([ /* your routes */, {
  preloadingStrategy: PreloadAllModules,
  initialNavigation: 'enabled'
});
```

**Comment by hesampour** [comment]
@MarkPieszak method not worked for my project.

**Comment by ashokvishwakarma** [comment]
If there is any external script you are loading, use `async` attribute to solve the flickering issue.
