### ISSUE TITLE
angular 2.1.2 angular universal + flickers on browser

### ISSUE THREAD

**Issue by amitjain28** [angular/universal-starter#439]
when bootstraping at client side since the UI is rendered twice, 1 at server-side and 1 at client-side.
Also it is is showing white flash while flickering

Can anyone help?

**Comment by MarkPieszak** [comment]
Are you doing an Http call?
Are both your withTransitions providing the same `appId`?

Lastly, try adding `initialNavigation: 'enabled'` to your RouterModule options.

```typescript
RouterModule.forRoot([ /* your routes */ ], { 
 // router options here
 initialNavigation: 'enabled' 
})
```

**Comment by naveedahmed1** [comment]
@MarkPieszak is there any way to avoid flickering for cases similar to:

```
        public userDetails: any;
        ngOnInit() {
                .....
                this.userService.getUserDetails(id).subscribe(result => {
                    this.userDetails = result;
                });
                ....
        }
```


```
<div *ngIf="userDetails">
 <user-details user="userDetails"><user-details>
</div>
```

When the component initializes on client side it sets `userDetails` to `null` which removes `user-details` from `dom`, and when `userService` returns users details (even from cache) it will be added back to `dom` again.

**Comment by Ovidiu-S** [comment]
I am having the same problem.
I am doing an http call, `initialNavigation: 'enabled'` is set.
Please provide more info on `withTransitions`

**Comment by RubensTen** [comment]
the same problem with
Angular 5
Angular universal 5

Any solution ?

**Comment by kuncevic** [comment]
Had similar issue in case of using universal prerender fixed by adding `initialNavigation: 'enabled' 
 as per `https://github.com/angular/universal-starter/issues/439#issuecomment-331549488

**Comment by inorganik** [comment]
@MarkPieszak 

> Are both your withTransitions providing the same appId?

I only have 1 in app.module.ts: `BrowserModule.withServerTransition({ appId: 'serverApp' }),`, should there be a second one somewhere?
