### ISSUE TITLE
enqueueTask/dequeueTask deprecation warning

### ISSUE THREAD

**Issue by manavsehgal** [angular/universal-starter#44]
Did fresh install - on ```npm start``` get following deprecation warnings once server is running...

```
DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask
DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask
```

**Comment by manekinekko** [comment]
Yeah. That's fine. You can ignore that for the moment

**Comment by ericmartinezr** [comment]
According to Misko this has been fixed in zone.js 0.6.0 https://github.com/angular/zone.js/issues/262, so now it's just matter of time until the next release (I guess)

**Comment by gdi2290** [comment]
closing this since the warnings will be removed in a future release
