### ISSUE TITLE
Rendering doesn't wait for async call with the angular-cli version

### ISSUE THREAD

**Issue by Scipionh** [angular/universal-starter#440]
I have just done two versions of the project, one using the webpack version, and one using the cli version.

I didn't have any troubles with the webpack version. Regarding the cli version though, the async call in the `ngOnInit ` of one of my component isn't waited, and the rendering happens without the content it fetches.
Universal waits for all the calls tracked by zone.js to finish before doing the rendering, which means that for some reasons my call isn't tracked in the `angular-cli` version. 

Is there any difference regarding how zone.js handles the tracking of the calls in both versions ?

Thanks !

**Comment by Toxicable** [comment]
It's been working in my won testing, could you provide a minimal reproduction for us?

**Comment by MarkPieszak** [comment]
How are you doing your async call, with Http or HttpClient?

**Comment by alex-masl** [comment]
Strange, but for me it did not work for fresh Angular project (i did few modifications to render app on server and async load some content using Http).
First I was playing with different version of cli/zone.
But then undo all my playing with versions and npm re-install all dependencies again keeping versions given by "ng new".
And after reinstall it worked.

**Comment by BatsShadow** [comment]
This sounds related: https://github.com/angular/universal/issues/736

**Comment by dimitarrusev** [comment]
I've noticed similar behavior recently. Async calls inside route resolves are not waited to complete on the server. Using HttpClient, Angular version: 4.4.3.
