### ISSUE TITLE
HMR for fast update

### ISSUE THREAD

**Issue by zmnv** [angular/universal-starter#447]
Hello guys, I'm a designer / low front-end.)))))))))

Can you please describe how to include webpack hmr in universal-starter repository (custom-webpack ?)?

**Comment by Toxicable** [comment]
HMR dosen't work too well with Angular so with the issues it has you end up saving more time just using normal auto reloading

**Comment by CaerusKaru** [comment]
The webpack branch has been removed and is likely no longer supported. If you can switch to the angular-cli, there’s a [guide](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) on how to enable HMR, and it runs pretty well.

**Comment by stephengardner** [comment]
HMR Works fine with Angular, but unfortunately I don't have an answer for you here.  Subbed, though.

**Comment by CaerusKaru** [comment]
Closing since `universal-starter` no longer has a Webpack branch. To use HMR with Angular CLI, please use the reference I linked above.
