### ISSUE TITLE
HttpClient does not work in Lazy Loaded Modules

### ISSUE THREAD

**Issue by Lomand** [angular/universal-starter#448]
#### What are the steps to reproduce your issue?
1. Clone `universal-starter` repo
2. Install CLI version of starter
3. Add `HttpClient ` module to `lazy.module` imports;
4. Use HttpClient in lazy loaded component, ex:
```typescript
import { NgModule, Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'; // It is for the json pipe
import { RouterModule } from '@angular/router'
import { HttpClient, HttpClientModule, HttpErrorResponse } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw';

@Component({
  selector: 'lazy-view',
  template: `<h3>i'm lazy</h3>
  <pre>
  {{posts | json}}
  </pre>`
})
export class LazyComponent implements OnInit {

  posts:any[];

  constructor(private http: HttpClient) { }

  ngOnInit() {
    const getPosts = this.http.get('https://jsonplaceholder.typicode.com/posts')
      .catch((error: HttpErrorResponse) => Observable.throw(error));

    getPosts.subscribe(res => this.posts = res)
  }
}

```
Build and serve the app with `yarn build:dynamic` and `yarn serve:dynamic`

#### What happens?
When I'm opening `/lazy` route, I have 
```
ERROR ReferenceError: XMLHttpRequest is not defined
    at BrowserXhr.build (D:\universal-starter\cli\dist\server.js:41059:61)
    at Observable._subscribe (D:\universal-starter\cli\dist\server.js:41097:57)
    at Observable._trySubscribe (D:\universal-starter\cli\dist\server.js:241:25)
    at Observable.subscribe (D:\universal-starter\cli\dist\server.js:229:65)
    at Object.subscribeToResult (D:\universal-starter\cli\dist\server.js:27618:27)
    at MergeMapSubscriber._innerSub (D:\universal-starter\cli\dist\server.js:36532:38)
    at MergeMapSubscriber._tryNext (D:\universal-starter\cli\dist\server.js:36529:14)
    at MergeMapSubscriber._next (D:\universal-starter\cli\dist\server.js:36512:18)
    at MergeMapSubscriber.Subscriber.next (D:\universal-starter\cli\dist\server.js:15443:18)
    at ScalarObservable._subscribe (D:\universal-starter\cli\dist\server.js:35867:24)
```
in the server console. This does not happen when I use `HttpClient` in non-lazy loaded modules. You can try exact same code in the `app.component`, and everything will be working flawlessly.

#### What were you expecting to happen?
To have the responce of the `get` call rendered by the Universal, no `XMLHttpRequest is not defined` error.

#### Any other comments?
OS: Windows 10
angular/cli: 1.3.2

**Comment by vikerman** [comment]
Does the Lazy loaded module have the HttpClient issue when you also load HttpModule in the main non-laze loaded server app module? Will investigate the issue - But wanted to see if the above could be a workaround. This sounds like some module configuration issue.

**Comment by Toxicable** [comment]
@vikerman The issue is with the value of `XhrFactory`
If you provide `HttpCientModule` in the `AppModule` and `LazyModule` or just in the `LazyModule` then `XhrFactory` gives you `BrowserXhr`.
Only if you provide `XhrFactory` in the `AppModule` alone will you get `ServerModule` from `XhrFactory`

**Comment by stewwan** [comment]
I don't quite understand, is there a way out of this case? I need to do a simple GET on the server.

**Comment by Lomand** [comment]
Is there any hot-fix for this issue?

**Comment by stewwan** [comment]
@lomand import httpClientModule just once on app.module (non laze)

**Comment by dottodot** [comment]
I'm seeing this issue too. The error is only server side and only on lazy loaded modules. I have also only included `HttpClientModule` in my `app.module`

**Comment by kmturley** [comment]
This works! I've created a fork with the HTTP changes you can use to test:
https://github.com/kmturley/universal-starter/commit/ceba9f874712169ab3f8945a53cd41b7f5fbae1e

**Comment by CaerusKaru** [comment]
Can this be closed?

**Comment by MrJmpl3** [comment]
If you used self sign cert , the problem is the Angular Universal used Express and the security validate the ssl certification to the server , i used a self sign ssl 
 , the solution is add the env NODE_TLS_REJECT_UNAUTHORIZED=0 to disable the verification SSL in NodeJs , warning this env is only in dev , in production is so risky

**Comment by Ismaestro** [comment]
For me, Just [this](https://github.com/angular/angular/issues/18199#issue-243593688) workarround works!
