### ISSUE TITLE
What are the needs of having a server/browser directory in the output

### ISSUE THREAD

**Issue by Scipionh** [angular/universal-starter#449]
I have recently tested the last changes you've done to the cli, and I wonder why did you change it by splitting the dist between a browser and a server folder ? Only the browser contains the index.html. But what is the logic between these two ? 

I am not familiar at all with the universal app, so I am pretty much a very beginner in this domain

**Comment by MarkPieszak** [comment]
One is your sever bundle, that sets up node/etc. separating them makes it easier to keep static files js/css separate and available in the browser portion. You wouldn't want someone to be able to see your server side node code after all 😀

**Comment by Scipionh** [comment]
I have actually modified the server.ts to chose between SPA behavior and static behavior at runtime (using the build:dynamic)

```
app.get('*', (req, res) => {
    console.time(`GET: ${req.originalUrl}`);
    if(isBot() || isOldIE()) {
        // Static
        res.render('index.html', {
            req: req,
            res: res
        });
    }
    else {
        // SPA
        res.sendFile(join(DIST_FOLDER, 'browser', 'index.html'));
    }
    console.timeEnd(`GET: ${req.originalUrl}`);
});
```

Does it make sense to do a similar thing for the static files ? 
aka:
```
app.get('*.*', express.static(join(DIST_FOLDER, 'browser'), {
  maxAge: '1y'
}));
```

**Comment by MarkPieszak** [comment]
You wouldn't need that stuff for the static files, those you always want served up!
