### ISSUE TITLE
dynamic component loader not working?

### ISSUE THREAD

**Issue by Bhushan001** [angular/universal-starter#45]
I am using this repo for loading dynamic components. i am not getting any error in browser nor on console.but my child component is also not getting loaded in browser.
Its working correctly if i am defining child component inside **app.ts** itself.
for eg. this works:
`

    import {Component, Directive, DynamicComponentLoader, ElementRef} from 'angular2/core';
    import {ROUTER_DIRECTIVES, ROUTER_PROVIDERS, RouteConfig} from 'angular2/router';

    @Component({
      selector: 'dcl-comp',
      template: `
      <div>dynamic</div>
    `})
    export class DynamicBody1Component {}

    @Directive({
      selector: '[x-large]'
      host: {
        '[style.fontSize]': 'x-large',
      }
    })
    export class XLarge {
    }

    @Component({
      selector: 'my-app',
      directives: [
        ...ROUTER_DIRECTIVES,
        XLarge
      ],
      styles: [`
        .router-link-active {
          background-color: lightgray;
        }`],
     template: `
      <div>    
        <div>
          <span x-large>Hello, {{ name }}!</span>
        </div>
        <div>
            <div #container></div>
        </div>
      </div>
      `
    })
    export class App {
      name: string = 'Angular 2';
      constructor(
        private dynamicComponentLoader: DynamicComponentLoader, 
        private elementRef: ElementRef) {}

      ngOnInit() {
        this.dynamicComponentLoader.loadIntoLocation(DynamicBody1Component, this.elementRef, 'container');

      }
    }`
But its not getting rendered when I am doing following,because  **DynamicBody1Component** is in different file.
`

    import {Component, Directive, ElementRef, Renderer,DynamicComponentLoader} from 'angular2/core';
    import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
    import {DynamicBody1Component} from './DYNAMIC-BODY-1.component';

    @Directive({
      selector: '[x-large]'
    })
    export class XLarge {
      constructor(element: ElementRef, renderer: Renderer) {
        // we must interact with the dom through Renderer for webworker/server to see the changes
        renderer.setElementStyle(element.nativeElement, 'fontSize', 'x-large');
      }
    }

    @Component({
      selector: 'app',
      directives: [
        ...ROUTER_DIRECTIVES,
        XLarge
      ],
      styles: [`
        .router-link-active {
          background-color: lightgray;
        }` ],
      template: `
      <div>    
        <div>
          <span x-large>Hello, {{ name }}!</span>
        </div>
        <div>
            <div #container></div>
        </div>
      </div>
      `
    })
    export class App {
      name: string = 'Angular 2';
      constructor(private dynamicComponentLoader: DynamicComponentLoader, private elementRef:     ElementRef) {}

      ngOnInit() {
        this.dynamicComponentLoader.loadIntoLocation(DynamicBody1Component, this.elementRef, 'container');
      }
    }`
I cant figure out why this is happening.
Any inputs?

**Comment by ericmartinezr** [comment]
It's working fine for me http://plnkr.co/edit/04bHkHexC5TTOCOJ98CD?p=preview

**Comment by Bhushan001** [comment]
@ericmartinezr I was saying while using universal-starter. its working for me in angular2,I am facing issue when I am trying to implement it using universal-starter.

**Comment by manekinekko** [comment]
Could you share the errors you have ?

**Comment by manekinekko** [comment]
@ericmartinezr could you post this issue in the Universal repo? Because I don't think it's related to the starter.

**Comment by ericmartinezr** [comment]
@manekinekko I can't reproduce his issue. I just tried it and it works perfectly.

- Created a folder to hold the dynamic component
- Imported it from app.ts
- Used DCL
- Profit

I think he needs to provide a repo for his case. The only thing I see is the name of his import `'./DYNAMIC-BODY-1.component`. I did try with a wrong name for my importing file and the console threw a huge error, so he should be seeing something similar. There's not enough info here.

@Bhushan001 can you create a repo with your project?

**Comment by manekinekko** [comment]
thanks @ericmartinezr 
@Bhushan001 yeah if you could create a repo and help us reproduce this issues, this would be great ^^

**Comment by Bhushan001** [comment]
@manekinekko @ericmartinezr  guys it worked if I am not using http service in my child component.I will be creating a repo soon ,will update you on this.

**Comment by Bhushan001** [comment]
@ericmartinezr @manekinekko i am closing this issue because it is related with httpRequest undefined.waiting for implementation of httpRequest implementation in universal
