### ISSUE TITLE
Static rendered app having page source only on the main route

### ISSUE THREAD

**Issue by Nekor4** [angular/universal-starter#451]
Hello,
Im using cli version of this repo. After static build, im serving dist/browser folder using http-server. Site is working well but when im trying to see the source of page, source appearing only on the '/' route on other routes source is empty. Which is obvious cause there is only one html file in dist/browser. So my question is how can i render files for ohter routes?

**Comment by Toxicable** [comment]
Right now we do only support rendering at the route `/` you can see this here 
https://github.com/angular/universal-starter/blob/master/cli/prerender.ts#L26
However we do have some tools in mind which could allow us to grab the routes out of an application and render out all of those routes.
But meanwhile you could wrap the renderModuleFactory and call it on your manualy added static routes, for example:
```
// Writes rendered HTML to ./dist/index.html, replacing the file if it already exists.
['/', '/home', '/about', '/signin'].forEach(route => {
  renderModuleFactory(AppServerModuleNgFactory, {
    document: index,
    url: route,
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  })
  .then(html => writeFileSync(join('browser', route.replace(///g, '-') + '-index.html'), html));
}
```
