### ISSUE TITLE
cli: Error: No provider for InjectionToken REQUEST!

### ISSUE THREAD

**Issue by peterpeterparker** [angular/universal-starter#452]
Hi,

I updated my project to the current `cli` state of this `universal-starter` project and I'm facing following error while running `npm run build:static`:

> Error: No provider for InjectionToken REQUEST!

I tried the solution described by @iliasbhal  in https://github.com/angular/universal-starter/issues/271 but still facing same error.

I tried to use `Injector.get` without success too like described by @MarkPieszak  in https://github.com/angular/universal-starter/issues/423 or @rimlin in https://github.com/angular/universal/issues/757

Therefore I allowed myself to open an issue

P.S.: Or maybe I'm just too dumb, the `request` can't be use with `static`?

Summary:

    constructor(@Inject(REQUEST) private request: Request) {
     }

or 

    constructor(private injector: Injector) {
        const req = this.injector.get('req');
    }

or 

    constructor(private injector: Injector) {
        const req = this.injector.get('request');
    }

or

    constructor(private injector: Injector) {
        const req = this.injector.get(REQUEST);
    }

all finished in same error...

**Comment by peterpeterparker** [comment]
Ok so it really just look like that I'm too dumb and that `REQUEST` can't be use when using `static`, what does make sense now when I'm think about it ;) Could someone just confirm and I'll then close this issue (wich is not one)?

**Comment by peterpeterparker** [comment]
Ok so it really just look like that I'm too dumb and that `REQUEST` can't be use when using `static`, what does make sense now when I'm think about it ;) When I use cli `dynamic` I could access the request.

**Comment by btgoodwin** [comment]
Can you share what your NPM script is for `build:static` vs. `build:dynamic`?  My CLI app doesn't have those options, and I'm having this same problem when trying to build a DI graph from within a single directive.

**Comment by btgoodwin** [comment]
Can you share what your NPM script is for `build:static` vs. `build:dynamic`?  My CLI app doesn't have those options, and I'm having this same problem when trying to build a DI graph from within a single directive.

**Comment by btgoodwin** [comment]
Can you share what your NPM script is for `build:static` vs. `build:dynamic`?  My CLI app doesn't have those options, and I'm having this same problem when trying to build a DI graph from within a single directive.

**Comment by peterpeterparker** [comment]
@btgoodwin sure

I use only `dynamic`, `static` doesn't work with my project. But here what I've got

In package.json:

    "scripts": {
        "ng": "ng",
        "start": "npm run build && npm run serve:dynamic",
        "start:dynamic": "npm run build:dynamic && npm run serve:dynamic",
        "start:static": "npm run build:static && npm run serve:static",
        "build": "ng build --extract-css",
        "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-    hashing=false",
        "build:static": "npm run build:client-and-server-bundles && npm run webpack:server && npm run generate:static",
        "build:dynamic": "npm run build:client-and-server-bundles && npm run webpack:server",
        "generate:static": "cd dist && node prerender",
        "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
        "serve:static": "cd dist/browser && http-server",
        "serve:dynamic": "node dist/server",
        "serve": "node dist/server"
  }

Then the cmds.

To test locally `npm run start`

To build prod `npm run build:dynamic`

To run prod `npm run serve:dynamic` or `npm run serve`

**Comment by btgoodwin** [comment]
Thanks. Unfortunately, that doesn't work for me.  When the app tries to load, I get weird errors about a downstream library of mine where it did some symbol mangling (`export 'ej' (imported as 'i2') was not found in 'that-library'`).  I'm using the NG CLI server (`ng serve`), which for me at least, only seems to work in non `--prod` mode.

**Comment by peterpeterparker** [comment]
looks super complicated to me @btgoodwin :( hope you will find a solution!

**Comment by btgoodwin** [comment]
For what it's worth, [here is a demo reproduction of my bug](https://angular-gitter-wmzhot.stackblitz.io/).

**Comment by peterpeterparker** [comment]
@btgoodwin try to ask your question/seek support on the https://gitter.im/angular/universal channel

**Comment by Toxicable** [comment]
@btgoodwin Your issue looks completely unrelated to Universal here 
I would advise that you don't use `ReflectiveInjector` since it is now deprecated in v5
Also there is no need for you to create your own Injector context.

**Comment by btgoodwin** [comment]
@Toxicable I agree; I came here mainly because the error and symptoms sounded similar to what I am seeing in v4 and v5.  Thanks again @peterpeterparker for posting the scripts. :-)
