### ISSUE TITLE
[Feature] cli: add a app.browser.module.ts

### ISSUE THREAD

**Issue by peterpeterparker** [angular/universal-starter#454]
Hi,

I would suggest a feature request. 

I was running the cli dynamically (`npm run build:dynamic` and then `npm run serve:dynamic`) and was then facing the following error on the server side:

> })(window, document, 'Hammer');
>    ^
> ReferenceError: window is not defined

Of course this happens because my `app.module.ts` was containing:

   import 'hammerjs';

To solve the issue in `main.ts` I bootstrap now a new file `app.browser.module.ts` I have created, which extend `app.module.ts` (like app.server.module.ts` does), where I import `hammer.js`

I thought maybe some other developers may encounter the same issue and therefore maybe you would find cool to do the same in this project?

Or maybe that's totally wrong and I would not mind to know it ;)

Best regards

**Comment by stewwan** [comment]
import hammer on main.ts

**Comment by peterpeterparker** [comment]
@stewwan you are right, thx. why searching complicated when you could be solve easily
