### ISSUE TITLE
Handle 404s

### ISSUE THREAD

**Issue by rlavoie** [angular/universal-starter#455]
There should be a way to send responses with HTTP status 404.

**Comment by Creiger** [comment]
There si a great [ServerResponseService](https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/client/app/shared/services/server-response.service.ts) available for this.

**Comment by CaerusKaru** [comment]
The method for this is to inject the `RESPONSE` token (for either Express or Hapi) and send the response code using that object.
