### ISSUE TITLE
Speed up page loading using node 

### ISSUE THREAD

**Issue by Nekor4** [angular/universal-starter#456]
Hello, 
is there any solutions to speed up page loading using node dynamic render? Something like cache rendered html to not render it twice?

**Comment by Toxicable** [comment]
I would suggest using a cache for Express.
I've discuses with others and we've concluded that it shouldn't be Universal's responsibility to handle caching.

**Comment by MarkPieszak** [comment]
Yes, you could create and handle a cache however you'd like, look into Node cacheing to get so,e ideas on how to achieve it. It's outside of the scope here for the starter as some might not want one.
