### ISSUE TITLE
question on server.ts

### ISSUE THREAD

**Issue by stewwan** [angular/universal-starter#458]
hello, this project is awesome

I need to know if there's any way to import extra stuff into the [`server.ts`](https://github.com/angular/universal-starter/blob/master/cli/server.ts) file. I needed to import a configuration file there, is there any way? or do I actually need to put everything in the same file?

**Comment by MarkPieszak** [comment]
It's a typical Node server so you can do things however you'd like, in separate files / folders, whatever 👍
