### ISSUE TITLE
Error: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required

### ISSUE THREAD

**Issue by MrCroft** [angular/universal-starter#462]
Steps to reproduce:
1. Get the [cli folder](https://github.com/angular/universal-starter/tree/master/cli) in this repo
2. Open package.json and replace all Angular versions with "5.0.0-rc.1"
3. I've also replaced the CLI version with "1.4.5" (don't know if it matters)
4. Run `npm run build:dynamic` (ignore the `prerender.ts` **error**)
5. Run `npm run serve:dynamic`

`Error: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required`

Simply commenting this line `throw staticError('\'deps\' required', provider);` in the produced `server.js` file, makes it work.

Full stack:
```
Marian@MS:/mnt/c/www/cli-universal$ npm run serve:dynamic

> ng-universal-demo@0.0.0 serve:dynamic /mnt/c/www/cli-universal
> node dist/server

/mnt/c/www/cli-universal/dist/server.js:2733
        throw staticError('\'deps\' required', provider);
        ^

Error: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required
    at staticError (/mnt/c/www/cli-universal/dist/server.js:2766:12)
    at computeDeps (/mnt/c/www/cli-universal/dist/server.js:2733:15)
    at resolveProvider (/mnt/c/www/cli-universal/dist/server.js:2528:33)
    at recursivelyProcessProviders (/mnt/c/www/cli-universal/dist/server.js:2585:53)
    at recursivelyProcessProviders (/mnt/c/www/cli-universal/dist/server.js:2574:17)
    at recursivelyProcessProviders (/mnt/c/www/cli-universal/dist/server.js:2574:17)
    at new StaticInjector (/mnt/c/www/cli-universal/dist/server.js:2485:9)
    at Function.Injector.create (/mnt/c/www/cli-universal/dist/server.js:2457:16)
    at JitCompilerFactory.createCompiler (/mnt/c/www/cli-universal/dist/server.js:113969:97)
    at Object.ngExpressEngine (/mnt/c/www/cli-universal/dist/server.js:137692:36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-universal-demo@0.0.0 serve:dynamic: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-universal-demo@0.0.0 serve:dynamic script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/Marian/.npm/_logs/2017-10-07T13_52_01_837Z-debug.log
```

Node: 8.6.0
Npm: 5.4.2
OS: Win 10 Pro (WSL Ubuntu 16.04.3 LTS)

**Comment by MarkPieszak** [comment]
If you want to use 5.x you have anything from `@nguniversal` To version 5.x as well. NgModule factory-loaded and express-engine if you're using that as well. Hope that helps!

**Comment by Toxicable** [comment]
@MarkPieszak This is actually a bug, we forgot to upgrade the module loader, but there's a PR to fix it here https://github.com/angular/universal/pull/808

**Comment by MrCroft** [comment]
@MarkPieszak just replaced `@nguniversal/*: 1.0.0-beta.3` with `5.0.0-beta.1` and now it works (other than a build error which should be solved by the PR @Toxicable mentioned).

Initially, I didn't want to go with `@nguniversal/*:1.0.0-beta.3` like the updated example since a few days ago. But I'm used to checking what the available `dist-tags` are on npm (and 5.x used to have a tag). Now it only shows `{ latest: '1.0.0-beta.3' }`. I should have checked for `versions` as well, instead of assuming that 5.x is gone.

**Comment by Toxicable** [comment]
@MrCroft See https://github.com/angular/universal/issues/821 about the dist-tags

**Comment by vikerman** [comment]
Sorry for the confusion. Can this be closed?

**Comment by MrCroft** [comment]
@vikerman If you mean from my point of view, yes - of course. This issue was just about the error thrown because I was using Angular 5 with nguniversal 1.0.0-beta.3 packages instead of 5.x.
Works fine with 5.x

I only thought that you guys wanted to wait for [angular/universal#808](https://github.com/angular/universal/pull/808) to be in the next release, before closing this one also. Only because it was mentioned here and there's no open issue about that, as far as I could (not) find one. 

But I wasn't complaining about `Argument of type '{ bootstrap: any; providers: Provider[]; }' is not assignable to parameter of type 'NgSetupOptions'` thrown when transpiling the `server.ts file`. I'm still going the old _manual_ `server.js` way. Not too found of having a webpack generated server.js file with ~120**K** lines of code.

**Comment by Toxicable** [comment]
The original issue has been fixed via https://github.com/angular/universal/commit/9136967378d53b9f25842c87b6a16ed92e16b539
If you still have any other issues feel free to open another issue specifically about it
