### ISSUE TITLE
Why is the angular cli version so old?

### ISSUE THREAD

**Issue by rhizohm** [angular/universal-starter#464]
Just curious why the version of the @angularcli is not current? Everything else in the sample uses the latest/greatest but that...

**Comment by Toxicable** [comment]
https://github.com/angular/universal-starter/blob/master/cli/package.json#L49
This is the latest version.
The `^` means that version 1.x.y will be installed

**Comment by MarkPieszak** [comment]
Yeah anything 1.3 and over should work as that's when it was all first introduced.
