### ISSUE TITLE
No provider for t!

### ISSUE THREAD

**Issue by westdabestdb** [angular/universal-starter#465]
I tried to get data from server.ts using Http and service from my angular component, but every time I tried, I got this error "**ERROR Error: Uncaught (in promise): Error: No provider for t! Error: No provider for t!**". Any fix ?

**Comment by MarkPieszak** [comment]
Are you trying to use Http (angulars Http) in server.ts, because that won't work. 
Can you make a regular XHR call, and just make sure you don't renderModuleFactory until that call is done.

**Comment by westdabestdb** [comment]
I was trying to use angular's Http in my app.service.ts, and I tried regular XHR in my service too, still same error

**Comment by MarkPieszak** [comment]
Is this when you're doing an ng serve ?
If it's from running universal, try running serve, it sounds like you might of forgot to add something to your providers array.

**Comment by westdabestdb** [comment]
i use "npm run build:dynamic && npm run serve:dynamic", let me check my providers but my service is included in providers

**Comment by westdabestdb** [comment]
My bad!! I forgot to import HttpModule and I had an error in my service. Thank you @MarkPieszak !!
