### ISSUE TITLE
How do I configure some routes to bypass the server and render purely on the client?

### ISSUE THREAD

**Issue by rhizohm** [angular/universal-starter#469]
Hi - I really want to use universal for some of an application, but then completely bypass the server for other routes and have the client do everything. 

If I use the static prerender method, it seems like if I don't include a route in the static.paths.js file, the route will get resolved by the client, but the LocationStrategy seems to fail if the URL is called directly.

If I use the dynamic method, it seems like the server attempts to render every route no matter what.

What do you recommend for configuring an application to have some routes that are prerendered but other routes that bypass server rendering entirely?

**Comment by MarkPieszak** [comment]
For dynamic, just set certain routes to go through the res.render() that's currently for * routes. And for * routes (after the more specific ones being above it) just send the res.send your dist browser index.html similar to how we have for static files and you'll be all set.

**Comment by rhizohm** [comment]
Nice! Got it!  For anyone doing this, here's the code I used for routing requests to the client:
```
  res.sendFile(join(DIST_FOLDER, 'browser','index.html'));
```
