### ISSUE TITLE
Build Dynamic vs Static

### ISSUE THREAD

**Issue by philippeboyd** [angular/universal-starter#474]
I'm trying to understand the difference between building in dynamic mode vs static mode. I've checked the checksum of each file and they're all the same apart from the index.html files of course. I understand that the the dynamic index.html file is "empty" and will populate depending on which page you're viewing while the static index.html pages are fully generated and staticly served (am I getting this right?).

My question is: Why would I deploy dynamic dist folder over the static one? (or vice versa)
Subquestion : Would there be any performance differences in using one method over the other? (Thinking big scale here and not just some simple webapp)

```
dist-dynamic
├── browser
│   ├── 0.90e6c47683ab41e392c4.chunk.js
│   ├── 3rdpartylicenses.txt
│   ├── favicon.ico
│   ├── index.html
│   ├── inline.82f055cd19840d0a2724.bundle.js
│   ├── main.cfc1526e6dfb27c324e0.bundle.js
│   ├── polyfills.80bfeb690703af4fafee.bundle.js
│   ├── styles.d41d8cd98f00b204e980.bundle.css
│   └── vendor.97728a0320fc17470890.bundle.js
├── prerender.js
├── server
│   ├── favicon.ico
│   ├── main.bundle.js
│   └── styles.bundle.css
└── server.js

2 directories, 14 files
```

```
dist-static
├── browser
│   ├── 0.90e6c47683ab41e392c4.chunk.js
│   ├── 3rdpartylicenses.txt
│   ├── favicon.ico
│   ├── index.html
│   ├── inline.82f055cd19840d0a2724.bundle.js
│   ├── lazy
│   │   ├── index.html
│   │   └── nested
│   │       └── index.html
│   ├── main.cfc1526e6dfb27c324e0.bundle.js
│   ├── polyfills.80bfeb690703af4fafee.bundle.js
│   ├── styles.d41d8cd98f00b204e980.bundle.css
│   └── vendor.97728a0320fc17470890.bundle.js
├── prerender.js
├── server
│   ├── favicon.ico
│   ├── main.bundle.js
│   └── styles.bundle.css
└── server.js

4 directories, 16 files
```
Thanks for the enlightenment.

**Comment by Toxicable** [comment]
Here are the core differances between them 
https://github.com/angular/universal-starter/tree/master/cli#static-or-dynamic

However as for when to use either, the basic answer i'd use to that is to use Dynamic when you're hosting your app on a web server and have dynamic content.
Static when you're hosting your app on a static distribution service such as a CDN and where the content is not so dynamic

**Comment by MarkPieszak** [comment]
Fabian is spot on, dynamic is more for if you need `/products/golf` `/products/shoes` to be hit, and dynamically request data. These pages could be different hour-by-hour with the latest products for example.

Static is just for static pages (where the data doesn't change).
Maybe you're app has a homepage & about us that doesn't change often, you want to statically prerender those, and just let your `/blog` route serve up regular dist/browser/index.html, or your  client-rendered Angular app.

**Comment by philippeboyd** [comment]
Great answers guys! It's 100% clear now.
Thanks!
