### ISSUE TITLE
StaticProviders in Angular 5

### ISSUE THREAD

**Issue by manfredsteyer** [angular/universal-starter#480]
Tried to upgrade the seed to Angular 5. The only issue I ran into so far is that provideModuleMap is currently returning a Provider[] while beginning with Version 5 we need a StaticProvider[]:

```
app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
     provideModuleMap(LAZY_MODULE_MAP)
  ]
}));
```

**Comment by MarkPieszak** [comment]
Manfred hey! 👋 Long time no see haha
Can you install the lazy module and express engine that's 5.x versions, and you'll be all set. 

The "latest" versions of the packages are out there for 4.x but if you install @next then you'll be all set 👍
