### ISSUE TITLE
How to use prerender.ts for route parameters

### ISSUE THREAD

**Issue by dint17** [angular/universal-starter#483]
I have setup my project with this starter project. In my application I have a component called **article.component.ts**. With routing parameters I determine which article to load from my api:

```
path: 'artikel/:id',
component: ArticleComponent,
data: {title: environment.pageName + ' - Artikel'},
resolve: {article: ArticleResolveService},
```

In the file **static.paths.ts** I only have the following:

```
export const ROUTES = [
    '/home',
    '/suche',
    '/artikel'
];
```
 
Using **npm run build:static** generates one index.html file in the folder **/article**. What I try to achieve is the following:

```
/dist
|
+-- home
  |
  +--index.html
+-- suche
  |
  +--index.html
+-- article(as it should be)
    |
    +-- 90(id from article - see routing)
        |
        +--index.html
    +-- 91
        |
        +--index.html
    +-- 92
        |
        +--index.html
```

Is there a way I can achieve this with the current setup ? Currently the prerenter.ts can only load the corresponding componets for the parent route.

**Comment by dint17** [comment]
I got this working by getting my ID's from the API on static.paths.ts and then adding one path for each article

**Comment by PuriaRad** [comment]
Hi,
I have the same problem with a rest api backend. There are a lot of nested routes with IDs and I want to create a html for each one and then set meta tags.

Would you give me an example of writing appropriate `prerender.js` and `static.paths.ts` please? 

Thank you!

**Comment by viniciusaugutis** [comment]
I need this too. Help please
