### ISSUE TITLE
Use Node JS for SSR and API concurrently

### ISSUE THREAD

**Issue by KrGyan** [angular/universal-starter#486]
Hi Guys,

Can we use the current setup for both SSR and consuming API's?

Please suggest, best suitable way !!

**Comment by MarkPieszak** [comment]
There should be some commented code in there to handle it.

Just add all your app.get(‘/api/whatever’) paths above the SSR rendering line in server.ts, create all your API paths there, and you’ll be all set!

**Comment by KrGyan** [comment]
Yup that works !!
