### ISSUE TITLE
No provider for InjectionToken MatSnackBarData

### ISSUE THREAD

**Issue by davidgk** [angular/universal-starter#493]
When I try to create a test that use into the constructor this guy:

export class ErrorStatusSnackBarComponent {

  constructor (@Inject(MAT_SNACK_BAR_DATA) public data: string) {
  }

}
Into the test I don't know how to provide this, as when I do it  the test doesn't run too because:

  Error: Invalid provider for the NgModule 'DynamicTestModule' - only instances of Provider and Type are allowed, got: [?InjectionToken MatSnackBarData?, ...] in http://localhost:9876/_karma_webpack_/vendor.bundle.js (line 42656)

Any Idea how to solve this ?

Thanks!

**Comment by Gorniv** [comment]
https://github.com/angular/material2/blob/master/src/lib/snack-bar/simple-snack-bar.ts
 and you can try look https://github.com/Angular-RU/angular-universal-starter/tree/material2

**Comment by CaerusKaru** [comment]
Is this still an issue?

**Comment by ArnoldKrumins** [comment]
providers: [{
  provide: MatDialogRef,
  useValue: {}
}, {
  provide: MAT_DIALOG_DATA,
  useValue: {} // Add any data you wish to test if it is passed/used correctly
}]

**Comment by davidgk** [comment]
Thanks Arnold , I guess after some search That I implement something quite similar that you propose. Thanks a lot.
