### ISSUE TITLE
Separate Directive for Browser and Server with a Shared Module

### ISSUE THREAD

**Issue by dottodot** [angular/universal-starter#494]
I have a Directive that I want to used in the Browser only, and normally I'd just import it into my SharedModule so that it's available in all my lazy loaded modules.

However I can't quite get my head around how I can implement a Shared Module that does this. I know I can create a dummy directive for the server side but that doesn't help in regards to lazy loaded modules. 

For services there's you can use the provide, useClass but as far as I know there's not anything similar for Modules.

**Comment by Gorniv** [comment]
try look https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/mock-server-browser/mock-server-browser.module.ts

**Comment by dottodot** [comment]
@Gorniv thanks that makes sense, hadn't thought of splitting out the environment like that.

**Comment by CaerusKaru** [comment]
@dottodot Can this be closed?
