### ISSUE TITLE
Inline template and styles when using ng g c

### ISSUE THREAD

**Issue by thibaultvanluchene** [angular/universal-starter#495]
So, when I use ```ng g c``` to generate a component in this project, it's always inline, but that's not what I want, as that's normally done with the flag ```--inline-style```

How to generate separate style and template files, like the CLI normally does?

**Comment by Toxicable** [comment]
https://github.com/angular/universal-starter/blob/master/.angular-cli.json#L85
set this to false
see https://github.com/angular/angular-cli/wiki/generate-component for more

**Comment by thibaultvanluchene** [comment]
I'll try this soon! Thanks for your reply.

**Comment by CaerusKaru** [comment]
Closing as not an issue with `universal-starter`.
