### ISSUE TITLE
developer experience

### ISSUE THREAD

**Issue by bkinsey808** [angular/universal-starter#5]
Does this project require a full build before the developer can see a change on the client reflected in the browser? Could anybody point me toward how to develop with bundling turned off until production deploy? Also, how would I go about trying to get browsersync or something like it to work with this project?

**Comment by gdi2290** [comment]
this repo is meant to be very minimal. The fullstack repo will be what you're looking for. I'll update it and get back to everyone once I get back to the states tomorrow

**Comment by bkinsey808** [comment]
Thanks! Looking forward to it. I am very impressed by the bootstrapping speed of this project, the fastest ng2 project I have come across yet. With the addition of state-of-the-art tooling, this project could be revolutionary. :)

**Comment by angelUniversal** [comment]
Full-stack repo has troubles as of 12/20/2015. This one better.
