### ISSUE TITLE
building:ssr error

### ISSUE THREAD

**Issue by hasan786786** [angular/universal-starter#502]
D:\angular4\demo2\dist\server.js:115968
            var ua = window.navigator.userAgent.toLowerCase();
                                                                        ^
ReferenceError: window is not defined
    at D:\angular4\demo2\dist\server.js:115968:49
    at D:\angular4\demo2\dist\server.js:115970:11
    at Object.<anonymous> (D:\angular4\demo2\dist\server.js:116809:3)
    at __webpack_require__ (D:\angular4\demo2\dist\server.js:20:30)
    at Object.defineProperty.value (D:\angular4\demo2\dist\server.js:63623:14)
    at __webpack_require__ (D:\angular4\demo2\dist\server.js:20:30)
    at Object.defineProperty.value (D:\angular4\demo2\dist\server.js:63398:26)
    at __webpack_require__ (D:\angular4\demo2\dist\server.js:20:30)
    at Object.<anonymous> (D:\angular4\demo2\dist\server.js:156151:26)
    at __webpack_require__ (D:\angular4\demo2\dist\server.js:20:30)

package.json
{
  "name": "demo2",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
    "build:prerender": "npm run build:client-and-server-bundles && npm run webpack:server && npm run generate:prerender",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "generate:prerender": "cd dist && node prerender",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:prerender": "cd dist && http-server",
    "serve:ssr": "node dist/server"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc.2",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@nguniversal/express-engine": "^5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "core-js": "^2.4.1",
    "express": "^4.16.2",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/hammerjs": "^2.0.35",
    "@types/node": "^8.0.30",
    "cpy-cli": "^1.0.1",
    "express": "^4.15.2",
    "http-server": "^0.10.0",
    "reflect-metadata": "^0.1.10",
    "ts-loader": "^2.3.7",
    "ts-node": "^3.3.0",
    "typescript": "~2.4.2"
  }
}

**Comment by Toxicable** [comment]
see https://github.com/angular/universal-starter#universal-gotchas

**Comment by CaerusKaru** [comment]
Closing as not an issue with the starter. To run SSR, your bundles can't have references to the global window object.
