### ISSUE TITLE
Pre-render with images

### ISSUE THREAD

**Issue by freezy** [angular/universal-starter#503]
Since the `raw-loader` used for HTML files in CLI doesn't resolve the `src` of `<img>` elements, I `require()` them in the controller and point `[src]` to it.

However, when pre-rendering, the server-side code is packed using `--output-hashing=false`, which results in the HTML served by `npm run serve:prerender` pointing to non-hashed URLs but serving hashed files. This results in 404s until the Javascript is executed and the DOM is updated with the hashed URLs, which then are correctly served.

I got this working by removing `--output-hashing=false` and replacing `main.bundle` in `prerender.ts` with something like:
```javascript
readdirSync('dist/server').filter(f => /^main\.[a-f\d]+\.bundle\.js/.test(f))[0]
```

But that seems hacky to me. What's the proper way of linking images in the template that are tied to a component and are not in the global assets folder?

**Comment by istrdev** [comment]
--output-hashing media

https://github.com/angular/angular-cli/wiki/build

**Comment by CaerusKaru** [comment]
@freezy Did @istrdev's solution work for you?

**Comment by freezy** [comment]
Sorry I didn't have the time to test it at the time, but I just did and it seems to work well!

Basically needed to replace `--output-hashing=false` with `--output-hashing=media` in `package.json`. Maybe that would be a better default?
