### ISSUE TITLE
How to handle 404 not found and redirect with status code 404

### ISSUE THREAD

**Issue by miladhamzelou** [angular/universal-starter#506]
How to handle 404 not found and redirect with status code 404 when route not found?

**Comment by dneeleman** [comment]
`import { Inject, Injectable, Optional } from '@angular/core';
import { RESPONSE } from '@nguniversal/express-engine/tokens';
import { Response } from 'express';
import { isEmpty } from 'lodash';

@Injectable()
export class StatusCodeResponseService {

    private response: Response;

    constructor(@Optional() @Inject(RESPONSE) response: any) {
        this.response = response;
    }

    /**
     * Set a status code on the response for given status code and message.
     *
     * @param {number} code
     * @param {string} message
     */
    setStatus(code: number, message?: string) {
        if (isEmpty(this.response)) {
            return;
        }

        this.response.statusCode = code;

        if (!isEmpty(message)) {
            this.response.statusMessage = message;
        }
    }

    /**
     * Set a 404 Not Found status code on the response
     *
     * @param {string} message
     */
    setNotFound(message = 'Not Found') {
        if (isEmpty(this.response)) {
            return;
        }

        this.response.statusCode = 404;
        this.response.statusMessage = message;
    }

    /**
     * Set a 500 Internal Server Error status code on the response
     *
     * @param {string} message
     */
    setInternalServerError(message = 'Internal Server Error') {
        if (isEmpty(this.response)) {
            return;
        }

        this.response.statusCode = 500;
        this.response.statusMessage = message;
    }
}
`

And then use it as so: `constructor (
        private statusCodeResponseService: StatusCodeResponseService,
    ) {
        statusCodeResponseService.setNotFound();
    }`

This is a solution I have found, and is working for us as expected.

**Comment by miladhamzelou** [comment]
Thanks @dneeleman for this solution.

**Comment by CaerusKaru** [comment]
If this is an accepted solution, please close this issue.

**Comment by hareldvd** [comment]
May I suggest a demo app I published that faces the 404 issue: https://github.com/hareldvd/Angular5-Universal-404-Demo
