### ISSUE TITLE
Angular Universal don't change Title

### ISSUE THREAD

**Issue by qlaffont** [angular/universal-starter#508]
Hi,
With your starter I try to change my title but I check the result with javascript disabled and my title is not change. Is it normal ?

Test Repo : https://github.com/qlaffont/test-universal 

Regards
Quentin

**Comment by m98** [comment]
Your repo seems to be fine, make sure that you're changing the title when it does not depend on the browser side js actions, otherwise, it should work properly.

**Comment by Dinath** [comment]
What if the title is rendering throught an HTTP request ; and changed with `title.setTitle('')` from the `@angular/platform-browser` ?
