### ISSUE TITLE
Routes with children are not being rendered in the server

### ISSUE THREAD

**Issue by hmlabs** [angular/universal-starter#512]
I have the following routes defined

 ```
{ path: 'lazy', loadChildren: './lazy/lazy.module#LazyModule'},
  {	

    path: 'campaign',
    component: MainComponent,
    children: [
      {
        path: '',
        loadChildren: './components/+campaign/campaign-create.module#CampaignCreateModule'
      }
    ],
  },
```

Lazy route renders in the server, however the routes with children defined do not.

**Comment by ZhalgasovaBota** [comment]
I have similar problem. How do you solved that issue?

**Comment by qqnc** [comment]
Any one encounter similar issue with children routes set?

**Comment by BruneXX** [comment]
I'm experiencing the same issue, is there any workaround for this?

**Comment by BruneXX** [comment]
Hi @hmlabs how did you solve that issue?
