### ISSUE TITLE
Update to Angular 5.1

### ISSUE THREAD

**Issue by marcinkunert** [angular/universal-starter#513]
Angular 5.1 [has been released](https://blog.angular.io/angular-5-1-more-now-available-27d372f5eb4e). The changelog states some changes to Angular Universal. Does it affect this project?

**Comment by m98** [comment]
This repository works fine if you Update your Angular.

**Comment by marcinkunert** [comment]
@m98 ok, thanks! Just wanted to make sure there are no major upcoming changes just after I get it working for my project.
