### ISSUE TITLE
Can this work with ng eject?

### ISSUE THREAD

**Issue by SwamyKottur** [angular/universal-starter#515]

**Comment by m98** [comment]
Could you please provide more detail on your issue?

The answer to these questions might help us:
- What's the current behavior?
- What's the expected behavior? 
- What have you tested yet?

**Comment by SwamyKottur** [comment]
@m98 

I did ng eject on cli project and tried to configure universal for such app. I believe the` ng eject` for platform server is not ready yet as i got the console error message for the same. So, the `prerender.ts` and `server.ts` files are required with the `dist/server/main.bundle` and now that i have ejected out i am unable to build a appropriate webpack file so that i can generate the similar main.bundle which would have been generated by the `ng build --prod --app 1`

Thanks,
Swamy

**Comment by MarkPieszak** [comment]
If you're ejecting your leaving the bounds of the CLI, so you'll have to handle everything yourself.
We previously had a webpack version you can find here in this branch (https://github.com/angular/universal-starter/tree/angular-5.0/custom-webpack), that might help get you going.

**Comment by SwamyKottur** [comment]
@MarkPieszak Thanks for sharing this. I will look into ti

**Comment by CaerusKaru** [comment]
@SwamyKottur Can this be closed?

**Comment by Toxicable** [comment]
As @MarkPieszak pointed out; when you eject you're accepting that you can handle the webpack config yourself. It is possible to do Universal in such a situation just we are unable to support it.

**Comment by SwamyKottur** [comment]
@CaerusKaru yes you can close this. I adapted solution from this [repo](https://github.com/qdouble/angular-webpack2-starter) for my project and now my entire project is on webpack. Thanks for looking into my ticket
