### ISSUE TITLE
Unable to load pages on new tab or view source

### ISSUE THREAD

**Issue by sharadjaiswal1411** [angular/universal-starter#516]
Hi I am using Angular5 with universal. After starting server my home page opens fine and page source is also visible. But when i try to open my inner page on browser directly.Page did not loads , it keeps loading and loading. Opening page via home page link works fine but in view source <router-outlet></router-outlet> content is blank.
Please suggest what are possible causes of this.

**Comment by kalyan11021980** [comment]
Is your router.ts config is correct and matching with your client routes? If you can share example then it will be easier to check for everyone and provide solutions!

**Comment by edenmanny25** [comment]
please provide sample  code of your app  issue to try to solve it

**Comment by sharadjaiswal1411** [comment]
Thanks guys. Issue is resolved , Problem in my  share-buttons directive. I have removed it.
