### ISSUE TITLE
webpackMerge 0.8.3 unsafe to call twice

### ISSUE THREAD

**Issue by sullivanpt** [angular/universal-starter#52]
Don't know if this is by design or a bug in webpack merge, but attempting to call it twice in a row as in the example results in the 'Client' getting some configuration data from the 'Server'.

```
module.exports = [
  // Client
  webpackMerge({}, defaultConfig, commonConfig, clientConfig),

  // Server
  webpackMerge({}, defaultConfig, commonConfig, serverConfig)
]
```

**Comment by gdi2290** [comment]
I have to replace `webpack-merge` with something like `extends` or create `webpack-default`

**Comment by sullivanpt** [comment]
I solved it by wrapping with "_.cloneDeep(webpackMerge(..."

**Comment by gdi2290** [comment]
@sullivanpt can you make a PR and use https://www.npmjs.com/package/lodash.clonedeep

**Comment by sullivanpt** [comment]
I haven't been able to reproduce with webpack-merge@0.7.3 (which is what universal-starter currently depends on) so I'm inclined to consider it a bug in @0.8.3.  Needs more investigation I think.

**Comment by sullivanpt** [comment]
Closing this in favor of survivejs/webpack-merge#12
