### ISSUE TITLE
prerender task fails

### ISSUE THREAD

**Issue by miscoo1** [angular/universal-starter#520]
I pulled this universal-starter project, prerender and ssr mode works. Then I integrate it to my project, build was successful. But it fails when the command `node prerender` is called. It fails with this error:

> Unhandled Promise rejection: Cannot read property 'create' of undefined ; Zone: <root> ; Task: Promise.then ; Value: { TypeError: Cannot read property 'create' of undefined
>     at /Users/michal/web/dist/prerender.js:5763:77
>     at ZoneDelegate.invoke (/Users/michal/web/dist/prerender.js:123269:26)
>     at Object.onInvoke (/Users/michal/web/dist/prerender.js:5024:33)
>     at ZoneDelegate.invoke (/Users/michal/web/dist/prerender.js:123268:32)
>     at Zone.run (/Users/michal/web/dist/prerender.js:123019:43)
>     at NgZone.run (/Users/michal/web/dist/prerender.js:4841:69)
>     at PlatformRef.bootstrapModuleFactory (/Users/michal/web/dist/prerender.js:5761:23)
>     at Object.renderModuleFactory (/Users/michal/web/dist/prerender.js:105514:39)
>     at /Users/michal/web/dist/prerender.js:159308:82
>     at ZoneDelegate.invoke (/Users/michal/web/dist/prerender.js:123269:26)
>   __zone_symbol__currentTask:
>    ZoneTask {
>      _zone:
>       Zone {
>         _properties: {},
>         _parent: null,
>         _name: '<root>',
>         _zoneDelegate: [Object] },
>      runCount: 0,
>      _zoneDelegates: null,
>      _state: 'notScheduled',
>      type: 'microTask',
>      source: 'Promise.then',
>      data: undefined,
>      scheduleFn: undefined,
>      cancelFn: null,
>      callback: [Function],
>      invoke: [Function] } } TypeError: Cannot read property 'create' of undefined
>     at /Users/michal/web/dist/prerender.js:5763:77
>     at ZoneDelegate.invoke (/Users/michal/web/dist/prerender.js:123269:26)
>     at Object.onInvoke (/Users/michal/web/dist/prerender.js:5024:33)
>     at ZoneDelegate.invoke (/Users/michal/web/dist/prerender.js:123268:32)
>     at Zone.run (/Users/michal/web/dist/prerender.js:123019:43)
>     at NgZone.run (/Users/michal/web/dist/prerender.js:4841:69)
>     at PlatformRef.bootstrapModuleFactory (/Users/michal/web/dist/prerender.js:5761:23)
>     at Object.renderModuleFactory (/Users/michal/web/dist/prerender.js:105514:39)
>     at /Users/michal/web/dist/prerender.js:159308:82
>     at ZoneDelegate.invoke (/Users/michal/web/dist/prerender.js:123269:26)

package.json
```
"dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@nguniversal/express-engine": "^5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "@ngx-translate/core": "^9.0.1",
    "@ngx-translate/http-loader": "^2.0.0",
    "angular-2-local-storage": "^1.0.1",
    "angular-calendar": "^0.21.3",
    "color-hash": "^1.0.3",
    "core-js": "^2.4.1",
    "enhanced-resolve": "3.3.0",
    "font-awesome": "^4.7.0",
    "ng2-datepicker": "^2.1.6",
    "ng2-validation": "^3.1.3",
    "ngx-gallery": "^4.1.1",
    "rxjs": "5.5.6",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.4",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/googlemaps": "^3.30.0",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^3.2.16",
    "@types/node": "^8.0.30",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "5.2.2",
    "ts-node": "1.2.1",
    "tslint": "^4.1.1",
    "typescript": "2.4.2",
    "webdriver-manager": "10.2.5",
    "cpy-cli": "^1.0.1",
    "express": "^4.15.2",
    "http-server": "^0.10.0",
    "reflect-metadata": "^0.1.10",
    "ts-loader": "^2.3.7"
  }
```

I tried to remove all problematic parts, but I don't identify the problem.

**Comment by miscoo1** [comment]
Issue caused by multi module project and related misconfiguration.

**Comment by mattbanks** [comment]
@mbrezovsky Don't want to open a new issue, but running into the same thing. What did you end up fixing on your end to get it working? I pulled down and integrated into a current project to get prerendering so we can deploy for SEO, but getting this `Unhandled Promise rejection` error.
