### ISSUE TITLE
innerHTML load twice in server side and client side

### ISSUE THREAD

**Issue by adisonkh** [angular/universal-starter#524]
I use the module TransferHttpCacheModule. which transfer the variable from server side render already. but if I use innerHTML client side load variable again.

--Mycode--
#home.html
--<div id="banner1" class="row" style="clear: left; height:100px; width:100%; overflow:auto;" align="center" [innerHTML]="scBannerStr">
<-/div>--

#home.ts
scBannerStr = '<script type="text/javascript">myscript</script>';

**Comment by masoudline** [comment]
@adisonkh how can you solve this problem?
