### ISSUE TITLE
Discarding entity body for GET requests

### ISSUE THREAD

**Issue by qlaffont** [angular/universal-starter#529]
Hi,
I have this error and i don't know why.
Can you help me ? I have used your starter.

Regards
Quentin

**Comment by qlaffont** [comment]
Fix with force update `ncu`

**Comment by djabif** [comment]
Hello @qlaffont, how did you solve this issue?

**Comment by qlaffont** [comment]
I have fix this issue with an update at the beginning. After that, try to cache with angular universal every request. 
If you don't do that, this errors can happened : 
1 - It's just a warning message and your app works very well
2 - It's a warning message but your app not works.

**Comment by djabif** [comment]
@qlaffont thanks for answering. What do you mean by _"an update at the beginning"_?

**Comment by qlaffont** [comment]
I have use this library npm-check-update. Do an update with ncu and after do an npm update.

**Comment by erashu212** [comment]
For me, It does not work :(

**Comment by kuchya** [comment]
from which version to which version you upgraded?? because its not working for me
