### ISSUE TITLE
Directives not working when did npm run build:ssr && npm run serve:ssr

### ISSUE THREAD

**Issue by imarshmultani** [angular/universal-starter#530]
I did built successfully angular app , but when did npm run build:ssr && npm run serve:ssr, and went to http://localhost:4000 , it did loaded the pages app of without any issue , **but any of the directives such as : load more ( (click)="LoadMoreMovies()" ), or on another component change video server ( (click)="ChangeServer()")  , does not work at all** , i've been clicking on them , i did check everywhere on google about this also , but nothing found , it works fine when did : ng serve or npm run start  , but when did production built they does not work at all , just click and nothing happens , no errors nothing... 

<img width="1553" alt="xfwaczm0s-sbe1qbh4wxva" src="https://user-images.githubusercontent.com/11553296/35070138-627e0398-fc02-11e7-8d7c-1d790215fd0a.png">

component is as below 
```typescript
import { Component, OnInit } from '@angular/core';
import { DatePipe } from '@angular/common';
import {Meta , Title} from '@angular/platform-browser';
import { MovieService} from '../movie/movie.service';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  providers: [MovieService]
})
export class HomeComponent implements OnInit {
  public latestmovies:any;
  public moviesoffset:number = 0;
  public loading_more:boolean = false;
  constructor(page_meta:Meta,page_title:Title,private movieservice:MovieService) {
    page_title.setTitle('Keewik');
    page_meta.addTags([
      {
        name:'keywords',content:'keyword,keyword,keyword,keyword,keyword'
      },
      {
        name:'description',content:'Description of the page or the site.'
      }
    ]);
   }

  ngOnInit() {
    this.GetAllMovies();
  }

  GetAllMovies(){
    this.movieservice.GetAllMovies(this.moviesoffset).subscribe(
      resultArray => {this.latestmovies = resultArray;this.moviesoffset = 12},
      error => console.log("Error :: " + error)
  );
  }

  LoadMoreMovies(){
    console.log('hello workinggg');
    this.loading_more = true;
    this.movieservice.GetAllMovies(this.moviesoffset).subscribe(
      resultArray => {
        this.latestmovies = this.latestmovies.concat(resultArray);
        this.loading_more = false
        this.moviesoffset = this.moviesoffset + 12},
      error => {console.log("Error :: " + error);this.loading_more = false;}
  );
  }

}
```

button for load more : 
```html
<button class="btn btn-info m-b-10" (click)="LoadMoreMovies()" [class.hidden]="loading_more" type="button"><span class="bold">Load More</span></button>
```

**Comment by imarshmultani** [comment]
it works fine when we go to dist folder and say: node server.js , so there is issue just with npm run build:ssr && npm run serve:ssr , closing this ,

**Comment by dineshk16feb** [comment]
I getting below issue after run "npm run build:ssr",

ERROR in multi ./src/main.server.ts
Module not found: Error: Can't resolve '/Users/Dinesh/Downloads/universal/src/main.server.ts' in '/Users/Dinesh/Downloads/universal/node_modules/@angular/cli/models/webpack-configs'
resolve '/Users/Dinesh/Downloads/universal/src/main.server.ts' in '/Users/Dinesh/Downloads/universal/node_modules/@angular/cli/models/webpack-configs'
  using description file: /Users/Dinesh/Downloads/universal/node_modules/@angular/cli/package.json (relative path: ./models/webpack-configs)
  after using description file: /Users/Dinesh/Downloads/universal/node_modules/@angular/cli/package.json (relative path: ./models/webpack-configs)
    using description file: /Users/Dinesh/Downloads/universal/package.json (relative path: ./src/main.server.ts)
      no extension
        /Users/Dinesh/Downloads/universal/src/main.server.ts doesn't exist
      .ts
        /Users/Dinesh/Downloads/universal/src/main.server.ts.ts doesn't exist
      .js
        /Users/Dinesh/Downloads/universal/src/main.server.ts.js doesn't exist
      as directory
        /Users/Dinesh/Downloads/universal/src/main.server.ts doesn't exist
[/Users/Dinesh/Downloads/universal/src/main.server.ts]
[/Users/Dinesh/Downloads/universal/src/main.server.ts.ts]
[/Users/Dinesh/Downloads/universal/src/main.server.ts.js]
[/Users/Dinesh/Downloads/universal/src/main.server.ts]
 @ multi ./src/main.server.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-io-example@1.0.0 build:client-and-server-bundles: `ng build --prod && ng build --prod --app 1 --output-hashing=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-io-example@1.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Dinesh/.npm/_logs/2018-04-23T09_56_40_205Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-io-example@1.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-io-example@1.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Dinesh/.npm/_logs/2018-04-23T09_56_40_271Z-debug.log
