### ISSUE TITLE
Is it possible to use SSR only for bots/crawlers ?

### ISSUE THREAD

**Issue by adrienlamotte** [angular/universal-starter#536]
Hello,

I'm using Angular Universal with my app, but I have some strange flickering when the page load (transition between server version and the actual app. And I does'nt work well with my route having Guards (user account pages for ex).

I only need SSR for SEO... So maybe there is a way to use SSR only for crawler bots ? And serve the classic Angular app for users ?

For now, I'm using the same `server.ts` from that repo.

Thank you !

**Comment by dneeleman** [comment]
Hi @adrienlamotte you should have a look at [`Preboot`](https://github.com/angular/preboot).
I think that library will solve your issues!

**Comment by CaerusKaru** [comment]
@adrienlamotte Can this be closed?

**Comment by adrienlamotte** [comment]
@CaerusKaru yes, thank you.

I ended up using this on particular routes (which need authentification) : 
```app.use('/account/**', express.static(join(DIST_FOLDER, 'browser')));```
