### ISSUE TITLE
Unit and e2e testing examples

### ISSUE THREAD

**Issue by Toxicable** [angular/universal-starter#539]
We should add some examples of how to unit and e2e test against Universal specific areas of the app.

**Comment by CaerusKaru** [comment]
Should this maybe be in the `@angular/universal` repo too? I can write up a unit test guide based on my work on angular/flex-layout#567, but I think it should probably go there.

This is of course assuming we want to keep the universal-starter as a "pick up and go" kind of repo. Making specialized tests here would force the user the remove them as they specialize the app.

**Comment by Toxicable** [comment]
Good point.
As discussed we'll make examples over there which we can use for testing aswell
