### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by coderrepo** [angular/universal-starter#542]
- Page loading twice and flicking the screen! 
https://ngcoderfirst.firebaseapp.com/
- When I access page url routing to home then back to requested URL. 
Ex : https://ngcoderfirst.firebaseapp.com/career

I have hosted apps in the Firebase hosting platform!

**Comment by CaerusKaru** [comment]
Duplicate of https://github.com/angular/angular/issues/15716

**Comment by wryly** [comment]
This issue is still occurring. angular/angular#15716 was closed with a request to create a new issue with minimal reproduction. This issue does that.

Any updates on a fix for this and angular/angular#15716? Should another issue be submitted?
