### ISSUE TITLE
Fresh install preboot not working

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#55]
After a clean clone and install the preboot does not seem to take effect.

I changed the client to : 

```javascript
function ngApp(req, res) {
  let baseUrl = '/';
  let url = req.originalUrl || '/';
  res.render('index', {
    directives: [ Html ],
    providers: [
      provide(APP_BASE_HREF, {useValue: baseUrl}),
      provide(REQUEST_URL, {useValue: url}),
      ROUTER_PROVIDERS,
      NODE_LOCATION_PROVIDERS,
      NODE_PRELOAD_CACHE_HTTP_PROVIDERS,
    ],
    async: true,
    preboot: true
  });
}
```

So that preboot is set to true but I don't see it updating the app.

**Comment by joaogarin** [comment]
The symptom I see in the latest version of the repo is actually the same I see in [my respository](https://github.com/joaogarin/myblog-angular2) where the promise for the bootstrap never actually finishes and so :

```javacript
.then(prebootComplete)
```
 does not actually get called at all.

**Comment by gdi2290** [comment]
@joaogarin you need to call prebootComplete for it to complete
https://github.com/joaogarin/myblog-angular2/pull/1

**Comment by gdi2290** [comment]
@joaogarin I'm working on this now

**Comment by gdi2290** [comment]
@joaogarin this is a problem with core where they're removing the script tags (as well as style tags)

**Comment by gdi2290** [comment]
thanks for the issue, everything works in latest changes so feel free to try it out again.

**Comment by joaogarin** [comment]
Yes everything looks good now great;)
