### ISSUE TITLE
[Question] is there a reason to blacklist 'rxjs/operators' ?

### ISSUE THREAD

**Issue by tunecino** [angular/universal-starter#550]
Sorry for asking this here. I'm confused about importing from `rxjs/operators` being blacklisted in **tslint.json** file while [RxJs Pipeable Operators docs](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#pipeable-operators) indicates this way of importing them:
```
import { filter, map, take, toArray } from 'rxjs/operators';
```
Is there a reason for such blacklisting? is it better to import them individually as `rxjs/operators/tap` ?

**Comment by Toxicable** [comment]
By importing from `rxjs/operators` you will pull in all operators.
Therefore you should import from `rxjs/operators/operator`

**Comment by tunecino** [comment]
Understood. Thank you for the reply @Toxicable
