### ISSUE TITLE
Missing specified styles (both through [ngStyle] or using Renderer2 .setStyle in custom component

### ISSUE THREAD

**Issue by agustinhaller** [angular/universal-starter#552]
Just added a new component to the lazy view (`<test-component>`) and set `[ngStyle]="{'padding-bottom': '100%'}"`.
When I run `npm run build:ssr && npm run serve:ssr` the `<test-component>' in the server side rendered view does not have the styles appended.

I also reported this issue here: https://github.com/angular/universal/issues/929

But I don't know if it's either the build process specified in this starter or a bug with Angular Universal itself.

Any idea what may be causing this?

**Comment by agustinhaller** [comment]
@gdi2290 any hint on what may be causing this?

**Comment by CaerusKaru** [comment]
Might be related to https://github.com/angular/angular/issues/22536? Did you try doing something like `[ngStyle]="{'paddingBottom': '100%'}"`?

**Comment by agustinhaller** [comment]
@CaerusKaru just tried `paddingBottom` instead of `padding-bottom` and no luck. What I found weird is that it's not working even using Renderer2 `setStyle()` method

**Comment by CaerusKaru** [comment]
The reason is because under the covers the `NgStyle` just uses the `setStyle` method

**Comment by agustinhaller** [comment]
In my smoke tests, this behavior was not present in Angular 5.0.2

*Working example using Angular `5.0.2`*
```javascript
this._renderer.setStyle(this._elementRef.nativeElement, 'paddingBottom', ratio_height);
console.log("_elementRef", this._elementRef.nativeElement);
```
```bash
_attrsByQName:
   { alt:
      { ownerElement: [Circular],
        localName: 'alt',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' },
     class:
      { ownerElement: [Circular],
        localName: 'class',
        prefix: null,
        namespaceURI: null,
        data: 'user-image' },
     title:
      { ownerElement: [Circular],
        localName: 'title',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' },
     style:
      { ownerElement: [Circular],
        localName: 'style',
        prefix: null,
        namespaceURI: null,
        data: 'padding-bottom:100%;' } },
```

* **NOT** working example using Angular `5.2.8`*
```javascript
this._renderer.setStyle(this._elementRef.nativeElement, 'paddingBottom', ratio_height);
console.log("_elementRef", this._elementRef.nativeElement);
```
```bash
_attrsByQName:
   { alt:
      { ownerElement: [Circular],
        localName: 'alt',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' },
     class:
      { ownerElement: [Circular],
        localName: 'class',
        prefix: null,
        namespaceURI: null,
        data: 'user-image' },
     title:
      { ownerElement: [Circular],
        localName: 'title',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' } },
```

Angular 5.0.2 was using Domino or Parse5DomAdapter? Maybe that introduced the bug.

**Comment by CaerusKaru** [comment]
The bug I referenced was introduced in 5.2.7

**Comment by agustinhaller** [comment]
Hope they merge your [PR](https://github.com/angular/angular/pull/22527) soon

**Comment by CaerusKaru** [comment]
I'm closing this issue until then, because this is definitely not an issue with universal-starter (and likewise with Universal)
