### ISSUE TITLE
How can I host this project in iis

### ISSUE THREAD

**Issue by kamalakkanni** [angular/universal-starter#564]
Hi ,

Can anyone pls guide me to host this project in iis server

Thanks

**Comment by kamalakkanni** [comment]
pls help me

**Comment by MarkPieszak** [comment]
Take a look at this comment, I believe it's possible with IIS Node:
https://github.com/angular/universal/issues/769#issuecomment-364952768

**Comment by kamalakkanni** [comment]
thanks,its working fine

**Comment by dvxdxm** [comment]
> thanks,its working fine

I'm having the same error. Can you help me? (step by step)
