### ISSUE TITLE
Request for an example on how to use HTTP and Universal in universal-starter

### ISSUE THREAD

**Issue by jhades** [angular/universal-starter#57]
Hi all, im trying to use the HTTP functionality of Angular Universal, by doing the following:

- take the latest universal starter
- add a REST API to return some test data
```
    app.use('/api/hello', (req,res) => res.send({text:"Hello World"}));
    app.use('/', ngApp);
```
- On the Home component, add an Ajax request:
```typescript
    import {Http} from 'angular2/http';

    export class Home {
        message:string;
        constructor(http:Http) {
            http.get('/api/hello')
                .subscribe(data => {
                    console.log('Hello world!!');
                    console.log(data);
            });
        }
    }
```
- The result is that on the console nothings gets logged

- I I then use `NODE_HTTP_PROVIDERS` instead of `NODE_PRELOAD_CACHE_HTTP_PROVIDERS` in server.ts, the console gives the following error:

    Listen on http://localhost:3000
    EXCEPTION: [object Object]

I did not manage to get this to work so far, do you have some insight on what I could be doing wrong?  

Would it be possible to add a small example here in the starter on how to use HTTP in Universal,  Thxs

**Comment by gdi2290** [comment]
replace `http.get('/api/hello')` with `http.get('http://localhost:3000/api/hello')` on the server you need the full url

**Comment by jhades** [comment]
Adding the full url fixed the error message, thank you. But with the following code bellow, I cannot get the result of the HTTP request to get server side rendered:

```
@Component({
  selector: 'home',
  template: `
  Home - {{message}}
  `
})
export class Home implements OnInit {

  message = "Hello initial value";

  constructor(private http:Http) {
  }

  ngOnInit() {
    this.http.get('http://localhost:3000/api/hello')
      .map(res => res.json())
      .subscribe(data => {
        console.log(data.text);
        this.message = data.text;
      });
  }
}
```

what shows on the screen is "Hello initial value", the initial value of the message variable. 

And not "Hello World" coming from the API response - which is working OK.

Do you think this is because the change detection issue #56 ?

**Comment by gdi2290** [comment]
make sure you're sending json
`app.use('/api/hello', (req,res) => res.send({text:"Hello World"}));`
should be
`app.use('/api/hello', (req,res) => res.json({text:"Hello World"}));`

**Comment by jhades** [comment]
Hi @gdi2290 , i've applied the fix as such:

    app.use('/api/hello', (req,res) => res.json({text:"Hello World"}))

and the results are the same, meaning that the content of the JSON message {text: 'Hello World'} does not get rendered to the screen.

Instead, the initial value of the message variable is displayed 'Hello initial value'.

As

**Comment by gdi2290** [comment]
just checking in to make sure this is resolved. if it's not please reopen it, thanks!

**Comment by jhades** [comment]
I confirm its working fine now, Thanks.
