### ISSUE TITLE
Error: No module factory available for dependency type: ContextElementDependency

### ISSUE THREAD

**Issue by peterpeterparker** [angular/universal-starter#581]
[X] I want to submit a bug

**Behavior**

When I serve the project, I face the error "Error: No module factory available for dependency type: ContextElementDependency"

**How to reproduce the problem**

     git clone https://github.com/angular/universal-starter
     cd universal-starter
     npm install
     npm run start

**Stacktrace**

> > ng serve
> 
> ** Angular Live Development Server is listening on localhost: 4200, open your browser on http://localhost:4200/ **
>  13% building modules 29/35 modules 6 active …ter/node_modules/html-entities/index.js✖ ｢wdm｣: Error: No module factory available for dependency type: ContextElementDependency
>     at addDependency (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:407:12)
>     at iterationOfArrayCallback (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:88:3)
>     at addDependenciesBlock (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:423:5)
>     at iterationOfArrayCallback (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:88:3)
>     at addDependenciesBlock (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:426:5)
>     at Compilation.processModuleDependencies (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:434:4)
>     at afterBuild (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:556:15)
>     at buildModule.err (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:600:11)
>     at callback (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:358:35)
>     at module.build.error (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:394:12)
>     at resolveDependencies (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ContextModule.js:233:4)
>     at ContextModule.result.resolveDependencies (/Users/me/Documents/projects/lab/universal-starter/me/@ngtools/webpack/src/angular_compiler_plugin.js:476:25)
>     at ContextModule.build (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ContextModule.js:158:8)
>     at Compilation.buildModule (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:362:10)
>     at factory.create (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:583:14)
>     at hooks.afterResolve.callAsync (/Users/me/Documents/projects/lab/universal-starter/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ContextModuleFactory.js:150:16)
> /Users/me/Documents/projects/lab/universal-starter/node_modules/neo-async/async.js:14
>     throw new Error('Callback was already called.');
>     ^
> 
> Error: Callback was already called.
>     at throwError (/Users/me/Documents/projects/lab/universal-starter/node_modules/neo-async/async.js:14:11)
>     at /Users/me/Documents/projects/lab/universal-starter/node_modules/neo-async/async.js:2805:7
>     at process._tickCallback (internal/process/next_tick.js:176:11)

**Side note**

Look like this problem was already noticed and discussed once in PR  https://github.com/angular/universal-starter/pull/574

When I run `npm ls webpack` I get

> ├─┬ angular-devkit/build-angular@0.6.0
> │ └── webpack@4.6.0 
> └── webpack@4.7.0 

I tried to install then explicitly webpack@4.6.0 but it didn't solve the issue

**Global version**

Node v9.11.1
Npm v5.8.0
Angular CLI: v6.0.0

**Comment by peterpeterparker** [comment]
Not sure but looks like the solution is to remove webpack, at least I didn't faced the error afterwards, therefore I close my issue

     npm remove webpack webpack-cli --save
     rm -r node_modules
     rm package-lock.json
     npm install

**Comment by peterpeterparker** [comment]
The webpack dependency has been now removed in this project too with https://github.com/angular/universal-starter/pull/589

**Comment by PeterParker** [comment]
@LawzPopiel -- I think that message was meant for @peterpeterparker ... :P

**Comment by peterpeterparker** [comment]
hahaha Hi @PeterParker, it's Peterpeterparker 😜
thx for mentioning me

**Comment by PeterParker** [comment]
[We meet again!](https://github.com/twbs/bootstrap/commit/6708c4dba5a1d3176b53df120706888a1e22fb05#commitcomment-27768317)

No worries. :)

**Comment by venkatinsaditya** [comment]
Exactly I don't know the issue but the build issue gone with the following steps. Thank you peterpeterparker

 npm remove webpack --save
 rm -r node_modules
 rm package-lock.json
 npm install

**Comment by karimessouabni** [comment]
worked for me thank you
