### ISSUE TITLE
Missing client bundle in result html

### ISSUE THREAD

**Issue by bromzh** [angular/universal-starter#59]
If we look into result html, we found no client bundle js plugged in:
```html
<html>
<head>...</head>
<body>
...
<server-only-app>
  <footer>Angular 2 Universal - server only rendered component</footer>
  </server-only-app>
<!-- Missing script tag here -->
  </body>
</html>
```

**Comment by gdi2290** [comment]
the script tag should be generated from
https://github.com/angular/universal-starter/blob/a686d146faee6de0f9ecb20b86cda49b4dbc527f/src/server-only-app/html.component.ts#L48

**Comment by bromzh** [comment]
@gdi2290 Yes, it should be generated, but actually doesn't. Html component hasn't the `scriptUrl` field, so template (script line) must be 
```html
<script async [attr.src]="seo.src"></script>
```
But even we change this part, result html still has no script tag. It seems that universal just delete all script tags.

**Comment by gdi2290** [comment]
@bromzh can you make a pull-request?

**Comment by bromzh** [comment]
@gdi2290 Unfortunantly I don't know how make project works for now. There are no effect when I change `scriptUrl` to `seo.src`. But if I fill index.html with code from Html component, then zone.js errors begin to appear. Since angular2 beta>10 starts using zone.js > 0.6 I dont know how to include zone.js without some hacks (like [this](https://github.com/AngularClass/angular2-webpack-starter/blob/1661e4ce847f90547e7bc875c57e8ebdfb3fef98/src/polyfills.ts#L32l)).

**Comment by micooz** [comment]
same problem. :sob:

**Comment by gdi2290** [comment]
sorry this is a problem with Angular removing the script and style tags

**Comment by gdi2290** [comment]
thanks for the issue, everything works in latest changes so feel free to try it out again.
