### ISSUE TITLE
which is best server to deploy angular universal app and how to host this

### ISSUE THREAD

**Issue by kamalakkanni** [angular/universal-starter#591]
Hi,

Can anyone tell me which is best server to deploy angular universal app and how to host this.

Thanks and Regards,
Kamalakkanni.V

**Comment by bnlambert** [comment]
I think server running nodejs is enough.

**Comment by kamalakkanni** [comment]
ok.Thanks

**Comment by hiepxanh** [comment]
cheap and almost free for development [with firebase](https://hackernoon.com/deploying-angular-universal-v6-with-firebase-c86381ddd445)

**Comment by kamalakkanni** [comment]
but for production.We need to pay money right

**Comment by cmddavid** [comment]
As long as you stay within the limits of the free tier, you won't be paying a dime on Firebase

**Comment by cmddavid** [comment]
Even if you have to pay money for it, it still saves you a lot of problems setting up a server and maintaining it etc. So it may be worth the money to stick to Firebase.

**Comment by hiepxanh** [comment]
can we close that issue ? @kamalakkanni ka
