### ISSUE TITLE
worker not defined

### ISSUE THREAD

**Issue by kamalakkanni** [angular/universal-starter#597]
Hi,

Below is my worker code

const WorkerPath=require('file-loader?name=scripts/[name].[hash].js!jsstore/dist/jsstore.worker.min.js');

export const _connection= new JsStore.Instance(new Worker(WorkerPath));

I got worker not defined error.So,

I used domino like below in server.ts

```
const template = readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();
const domino = require('domino');
const fs = require('fs');
const win = domino.createWindow(template);

global['window'] = win;
global['worker'] = win.Worker;
```

then also getting error.pls help me to fix it

Thanks

**Comment by yacineblr** [comment]
Were you able to solve this problem? If so, how?
