### ISSUE TITLE
Getting error about ngsw-worker.json

### ISSUE THREAD

**Issue by ishan123456789** [angular/universal-starter#609]
Here's the error

`
ERROR Something went wrong please try again later!
subscrib in toast called
ERROR { Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'ng
sw-worker.js'
Error: Cannot match any routes. URL Segment: 'ngsw-worker.js'
    at ApplyRedirects.noMatchError (E:\xampp\htdocs\universal-starter\dist\server.js:1
45108:16)
`
How should I fix it.I'm trying to implement starter in my present working angular 6 code and I've followed official documentation.

**Comment by ishan123456789** [comment]
Fixed using `ng add  @angular/pwa --project ng-universal-demo`

**Comment by whisher** [comment]
Hi there,
the same here

[stackoverflow.com/questions/51447558/angular-universal-pwa-error-error-uncaught-in-promise-error-cannot-matc](https://stackoverflow.com/questions/51447558/angular-universal-pwa-error-error-uncaught-in-promise-error-cannot-matc)

**Comment by Ks89** [comment]
I removed "//# sourceMappingURL=ngsw_worker.es6.js.map" from dist/appname/ngsw-worker.js and it's working.

Is this a bug of either universal or angular-cli?
My app is completely empty. It's simply the skeleton generated by angular-cli with some stupid additions.
