### ISSUE TITLE
About http example, http.get() twice, it's bad.

### ISSUE THREAD

**Issue by micooz** [angular/universal-starter#61]
It's reasonable that server get data from api then render pages. I noticed that when app bootstrapped in the browser, it of course fetches data from `data.json` in App component.

Maybe it's not necessary to fetch data **again** in the page which server respond.

After server got data, we can embed them into scripts, then client loads data from scripts. So the problem is how we hold data and how to bootstrap with data in the front-end. I knew `Redux` is a good choice, it provides a `store` to work these around.

Is there better or other ways in angular to solve these problem?

**Comment by gdi2290** [comment]
yup, we had a working solution during ng2 alpha I just need to update it. I'm going to close this issue but could you open it in this repo https://github.com/angular/universal

**Comment by gdi2290** [comment]
I created an issue https://github.com/angular/universal/issues/338 in the universal repo for you to track

**Comment by micooz** [comment]
Thanks :smile:
