### ISSUE TITLE
http requests

### ISSUE THREAD

**Issue by chriseugenerodriguez** [angular/universal-starter#615]
Hi!

Any chance you got it to print out http requests server side? I am having issue and need help with express build. Want to switch to this, but was main concern.

**Comment by m98** [comment]
Please use StackOverflow to ask questions.

I could not understand what you asked, but if you mean how to print out something on Node server, it's easy. Just do `console.log('your text')` and it supposed to work same as the way it works on the browser.

**Comment by chriseugenerodriguez** [comment]
@m98 your an idiot.
