### ISSUE TITLE
Support for angular 7

### ISSUE THREAD

**Issue by atelljohannsmothers** [angular/universal-starter#650]
After upgrading to angular 7, npm warns:

```shell
npm WARN @nguniversal/common@6.1.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/common@6.1.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@6.1.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@6.1.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@6.1.0 requires a peer of @angular/platform-server@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/module-map-ngfactory-loader@6.1.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/module-map-ngfactory-loader@6.1.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/module-map-ngfactory-loader@6.1.0 requires a peer of @angular/platform-server@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by ishan123456789** [comment]
Can you please share you updated package.json
I'm not able to use `ng update`

**Comment by jfrmm** [comment]
Hi, I'm having the same problem, after removing node_modules and package-lock.json, and running `npm update`

My package.json after the command is:

> "dependencies": {
    "@angular/animations": "^7.0.2",
    "@angular/cdk": "^7.0.3",
    "@angular/common": "^7.0.4",
    "@angular/compiler": "^7.0.4",
    "@angular/core": "^7.0.4",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^7.0.4",
    "@angular/http": "^7.0.4",
    "@angular/material": "^7.0.4",
    "@angular/platform-browser": "^7.0.4",
    "@angular/platform-browser-dynamic": "^7.0.4",
    "@angular/router": "^7.0.4",
    "@auth0/angular-jwt": "^2.0.0",
    "chart.js": "^2.7.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "ngx-cookie": "^4.1.2",
    "ngx-infinite-scroll": "^6.0.1",
    "rxjs": "^6.3.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.10.6",
    "@angular/cli": "^7.0.6",
    "@angular/compiler-cli": "^7.0.4",
    "@angular/language-service": "^7.0.4",
    "@nguniversal/express-engine": "^7.0.2",
    "@types/jasmine": "^2.8.11",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^10.12.9",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "prettier": "1.14.3",
    "protractor": "~5.4.1",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6",
    "webpack-dev-server": "^3.1.10"
  }
