### ISSUE TITLE
Preboot fails to init

### ISSUE THREAD

**Issue by cristinecula** [angular/universal-starter#66]
I have set the preboot flag to `true` in server.ts and I am getting the following error:

`Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.`

I am using the latest version @ 1b5e933fc5239fa60cb073b2e3aaa2a08e460b57

**Comment by jeffwhelpley** [comment]
Oh, weird. Haven't seen this one before. I will look into this and get back to you. Thanks for reporting.

**Comment by jeffwhelpley** [comment]
@cristinecula are you setting any preboot options? Did you literally just change the option to true and that was it or are there other differences with your code and the latest repo code?

**Comment by cristinecula** [comment]
@jeffwhelpley this is the output of `git diff`

```diff
diff --git a/src/server.ts b/src/server.ts
index 03d93de..b0fa803 100644
--- a/src/server.ts
+++ b/src/server.ts
@@ -42,7 +42,7 @@ function ngApp(req, res) {
       NODE_HTTP_PROVIDERS,
     ],
     async: true,
-    preboot: false
+    preboot: true
   });
 }

(END)
```

**Comment by gdi2290** [comment]
@cristinecula can you change the value to `preboot: { appRoot: 'app' }`

**Comment by cristinecula** [comment]
@gdi2290 that does the trick :)

**Comment by Kunepro** [comment]
To me it's not working at all.

Cloned repo.
npm install
I change this and only this in server.ts (it's a fresh install):
`preboot: false`
TO:
`preboot: { appRoot: 'app' } `
```
npm run build
npm start
```
I open localhost:3000 on Google Chrome Version 50.0.2661.86 (64-bit)
I see the page.
I open dev tools.
Network -> throttle 4G for delay.
Empty Cache & hard reload.
I type some random letters in the "Two-way binding: <this input field>".
"Universal JavaScript ftw!" remains static until the page finish to load.
Page finish to load and "Universal JavaScript ftw!" remains the same while the input field gets reset, I expected the opposite to happen!
What I'm doing wrong?

**Comment by jeffwhelpley** [comment]
@Kunepro I just tried this out again with the latest and it does work for me. In `client.ts` try to change the bootstrap to:

```
setTimeout(function () {
  bootstrap(App, [
    ...BROWSER_ROUTER_PROVIDERS,
    ...BROWSER_HTTP_PROVIDERS
  ]);
}, 3000);
```

Then test again. This obviously should do the same thing as network throttling, but just curious to see if you see different results. Let me know either way.

**Comment by Kunepro** [comment]
Hi @jeffwhelpley , nice to meet you, expecially after watching your conferences!
If I load the page from localhost with your code it looks like it works,
I edit the input field, and after the 3 seconds the string gets updated.
However, I hate to bring bad news, but when using developer's tools and network throttling the issue persists. (your code is still there)
I tested this 5 more times to don't come with false results.
Last time I checked that cache is disabled in dev tools setting, and also in dev tools networking tab, plus I deleted all history and caching from chrome.
I open a new tab, open dev tools, throttling to regular 3G, server side page loads instantly, I type some random letters in the input fields, but after the page has loaded the input field is back to "ftw" and also the "Universal JavaScript ftw!" is still like default. :(

**Comment by jeffwhelpley** [comment]
@Kunepro ahhhhh....I see the issue. hey, @gdi2290 so it looks like the express engine is currently pulling in preboot as an external file. We need to make this inline. Let's discuss at our meeting today.

@Kunepro I will post here when we are able to get this change in, but if this is a blocker for you and you are adventurous, the workaround for this is to override the express engine and have the generated preboot code inserted directly into your index.html on the server side. I recommend you wait until we get the fix in, but just wanted to let you know in case you needed a solution ASAP.

**Comment by Kunepro** [comment]
Hi @jeffwhelpley , thank you for the help.
I'm still working on the client, I can wait the official fix for the server, I'm just glad to know that it will be fixed!

**Comment by jeffwhelpley** [comment]
Try the latest and let me know.
