### ISSUE TITLE
Can we deploy Angular6-Universal and Web API on IIS Server?

### ISSUE THREAD

**Issue by AliAdravi** [angular/universal-starter#662]
I am planning to create and Angular 6 -Universal (Server side rendering) application which will use Web API  2.0 to access database.

Is this possible to deploy all these on the same server, Web API as a sub-site???

**Comment by CaerusKaru** [comment]
Duplicate of #564

**Comment by AliAdravi** [comment]
Nice answer Duplicate #564
Where is the answer, none of them have any solution
