### ISSUE TITLE
How to avoid re-rendering content inside isPlatformServer in the browser

### ISSUE THREAD

**Issue by conradolk** [angular/universal-starter#677]
I'm starting a project with Angular 7 and I was wondering whats the best way to hide "protected" HTML elements from users, based on permissions. I know the easiest way is to use a library like CASL to handle them, but I want true permission/role access check.

If the user shouldn't see a button, it must not be rendered at all, I know about ngIf and ngShow, even though it won't get to the HTML, it will be present in the minified bundle.js.

My approach was to do some tests with Angular Universal and using the isPlatformBrowser and isPlatformServer, but I found out that even if I use something like the following, the code will still be present in the bundle when Angular bootstraps in the client:
```
<ng-container *ngIf="isPlatformServerFunction() && hasAccess()">
 <button> Secret Button </button>
<ng-container>
```

¿Is there a way to render something exclusively server-side and dont let the HTML/JS slip into the front-end when it's bootstraped after the server-side rendering?

I wonder how this is handled in big applications like Facebook for example, because everyone says that it should be in the front-end, since the back-end APIs is secure, so if they get to the UI, they won't get to the API's data anyways, but I don't see admin buttons/code in Facebook's public bundle.

**Comment by robert-king** [comment]
you could try have a lazy loaded module with a canLoad guard ?

**Comment by CaerusKaru** [comment]
This bug tracker is not a support forum. If you need support please use Gitter or StackOverflow
