### ISSUE TITLE
Rebuild or reload app on file change

### ISSUE THREAD

**Issue by keatz55** [angular/universal-starter#68]
Is there a way I'm not seeing right from the start to reload the app with changes when files are modified in the src folder? Should we set it up ourselves?

**Comment by gdi2290** [comment]
in one terminal run `npm run watch` and in another run `npm run start`

**Comment by gdi2290** [comment]
can you make a pull request to include this in the readme?

**Comment by gdi2290** [comment]
I'm going to close this but please reopen or create another issue if you run into another problem thanks.

**Comment by keatz55** [comment]
Sure I can do that.
