### ISSUE TITLE
Dependency Injection not working 

### ISSUE THREAD

**Issue by Bhushan001** [angular/universal-starter#73]
So i was trying to pass an object to a child component using `@Input` , but its not working correctly.
I have used dynamic component loader to load child component and I want to pass the object to child component.
Following is my code snippet:

**app.component.ts**

    `import {Component, Directive, Renderer, DynamicComponentLoader, ElementRef} from 'angular2/core';
    import {Http} from 'angular2/http';    
    import {headingComponent} from './heading.component';

    @Directive({
      selector: '[x-large]'
    })
    export class XLarge {
      constructor(element: ElementRef, renderer: Renderer) {
        // we must interact with the dom through Renderer for webworker/server to see the changes
        renderer.setElementStyle(element.nativeElement, 'fontSize', 'x-large');
      }
    }

    @Component({
      selector: 'app',
      directives: [    
        XLarge
      ],  
      template: `
            <div>
                <div>
                <span x-large>Hello, {{ user.name }}!</span>
                </div>
                <icici-heading [user]="user"></icici-heading>      
            </div>
        `
    })
    export class App {
      public user;       
      constructor(dcl: DynamicComponentLoader, elementRef: ElementRef) {          
          dcl.loadNextToLocation(headingComponent, elementRef);
      }
      ngOnInit(){
          this.user = { "id": 11, "name": "Mr. Nice" };
      }  
    }
`
**heading.component.ts**

    `import {Component, OnInit,Input} from 'angular2/core';

    @Component({
        selector: 'icici-heading',
        template: `
            <div>
                this is not working
                {{name}}
           </div>
        `   
     })

    export class headingComponent implements OnInit {
        @Input() user;
        name: string;
        constructor() { }
        ngOnInit() { 
            this.name="heading is rendered";
        }    
    }`

**Comment by gdi2290** [comment]
@Bhushan001  when using DynamicComponentLoader you need to wire up the inputs manually.
```typescript
  constructor(dcl: DynamicComponentLoader, elementRef: ElementRef) {          
      dcl.loadNextToLocation(headingComponent, elementRef).then(compRef => {
        var input = 'user';
        compRef[input] = this.user;
        return compRef;
      });
  }
```
this is a support question about Angular 2 so I'm going to close this issue to keep the issues down
