### ISSUE TITLE
bundle.js EXCEPTION: UnsubscriptionError

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#74]
I am getting some erros on a project and also is happening on the starter where zone js is trowing some errors : 

bundle.js:30881 EXCEPTION: UnsubscriptionError

seems to be somehow related to the subscribe method. Looking at the longtrace I can see it goes back to 

```
javascript
scheduleResolveOrReject(promise, queue[i++], queue[i++], queue[i++], queue[i++]);
```
in the resolvePromise method.

By the way. I am having always longStacktrace enabled when pulling in the universal pollyfills, is this normal? I dont have it on the starter though..How to I enable / disable longtrace when using universal?

I am not doing 

```javascript
Error['stackTraceLimit'] = Infinity;
require('zone.js/dist/long-stack-trace-zone');
```

Anywhere. that would be the normal way of enabling it right?

**Comment by MarkPieszak** [comment]
ZoneJS issue apparently, logged an issue @ universal as well.
https://github.com/angular/universal/issues/350

Looks like Zone needs to be bumped up to `0.6.8` for this to work.

https://github.com/angular/zone.js/issues/310

**Comment by MarkPieszak** [comment]
This issue should be all fixed now (if you get latest) & can be closed out. @joaogarin

**Comment by joaogarin** [comment]
Yes this is gone! 👍
