### ISSUE TITLE
Path to include templateUrl and styleUrls

### ISSUE THREAD

**Issue by BojDom** [angular/universal-starter#76]
I tried with this starter to import the template file from `templateUrl: './a.html'` instead of putting the template inside the component, but the console shows <img src="https://cdn.pbrd.co/images/28ZfOcX.png"/>.
I have tried also with ./app/a.html and /src/app/a.html but everything fails, any suggestion?

**Comment by gdi2290** [comment]
the server needs a full url

**Comment by BojDom** [comment]
Now im faceing this problem ...
<img src="https://cdn.pbrd.co/images/2nto1N2.jpg"/> 
where can i read a log to investigate about it?

**Comment by BojDom** [comment]
Last error was because of a setInterval, im gonna close this

**Comment by gdi2290** [comment]
oh yeah, if you use setInterval then the server won't know when to stop before rendering
