### ISSUE TITLE
How to get the render output as a String?

### ISSUE THREAD

**Issue by jensvdh** [angular/universal-starter#77]
Hi!

Instead of sending my serverside rendered Angular App straight back to the client I'd like to access it as one long HTML string and save it in a file.

basically I'm trying to get the output of

`  res.render('index', {
    directives: [Html],
    providers: [
      NODE_ROUTER_PROVIDERS,
      NODE_HTTP_PROVIDERS
    ],
    async: true,
    preboot: false
  });`

in server.ts as a long HTML string so I can write it somewhere else instead of sending it as a response back to the client in Express.

What would be the best way to achieve this?

**Comment by gdi2290** [comment]
```typescript
var bootloader = new Bootloader({
  template: '<doctype><html><head></head><body><p>your html document as a string</p></body></html>'
  directives: [Html],
  providers: [
    NODE_ROUTER_PROVIDERS,
    NODE_HTTP_PROVIDERS
  ],
  async: true,
  preboot: false
})

bootloader.serializeApplication()
.then(html => console.log(html)
```

**Comment by gdi2290** [comment]
@jensvdh I also noticed you're located in SF. we can also meet up and I can quickly help you to get universal up and running

**Comment by jensvdh** [comment]
Hi @gdi2290 

That resolves my question. Thanks!

And thank you for the offer. I try to attend some meetups every now and then so I might have run into you. Angular Universal has been great so far but documentation is pretty lacklustre at the moment so I wasn't sure what the best place was to ask questions. Please point me to the right location if this wasn't it.

**Comment by drejohnson** [comment]
Hi @gdi2290 when I updated angular2 to 2.0.0-beta.17 and angular2-universal to 0.99.0 the above method breaks. 

`EXCEPTION: No provider for Token originUrl! (ComponentResolver -> RuntimeCompiler -> DirectiveNormalizer -> XHR -> Token originUrl)`

Here's the repo I stitched together: https://github.com/drejohnson/universal-angular2-starter.git

**Comment by gdi2290** [comment]
@drejohnson I created a PR https://github.com/drejohnson/universal-angular2-starter/pull/1

**Comment by drejohnson** [comment]
Hi @gdi2290, thanks for the PR but now I get `ORIGINAL EXCEPTION: No provider for Http!`

I created a fork of universal-starter with issue: https://github.com/drejohnson/universal-starter.

Thanks again

**Comment by gdi2290** [comment]
@drejohnson can you try https://github.com/drejohnson/universal-starter/compare/master...gdi2290:patch-1

**Comment by drejohnson** [comment]
@gdi2290 That works. Thanks!
