### ISSUE TITLE
Problem to inject $localStorage linked to window? 

### ISSUE THREAD

**Issue by blondinh** [angular/universal-starter#80]
Hello,

In debug window of Chrome i have window is not defined when I try to inject $locaStorage.
It refers to folder angular2/src/facade/browser.js

Please could you provide some informations?

**Comment by gdi2290** [comment]
`$locaStorage` doesn't exist but we can make one in Universal for you to use

**Comment by blondinh** [comment]
Yes, please!

**Comment by jeffwhelpley** [comment]
You can create this yourself, but we will eventually have some services to cover this:

https://github.com/angular/universal/issues/309
