### ISSUE TITLE
Using external html templates

### ISSUE THREAD

**Issue by danieleteti** [angular/universal-starter#81]
Using this starter-kit is it possibile to use external templates? The templateUrl attribute should contains the full file url? Where the html files should be? Is provided a build pipeline to creteate a proper dist folder with js,html,css and so on?

**Comment by Bhushan001** [comment]
#43 there is already a solution provided for this issue. you can track this issue here.and templateUrl must contain full Url in order to work correctly.

**Comment by danieleteti** [comment]
Thank you. What about the build pipeline? Is there a recommended approach?

**Comment by gdi2290** [comment]
this works but you have to set `moduleId` to `__filename` and make sure your server serves the file correctly
