### ISSUE TITLE
Unable to find module...

### ISSUE THREAD

**Issue by glemiere** [angular/universal-starter#84]
hi!

Thank you very much for your work, it is awesome! But there is something that disturbs me. I've added the module compression to my project, but when I try to import it on my server.ts, the compilation throw me that error : error TS2307: Cannot find module 'compression'.

Any idea to fix it ?

**Comment by gdi2290** [comment]
it's a typescript error where you need to install the types for compression
`typings install compression`

**Comment by glemiere** [comment]
Hi gdi2290,
Thank you for the answer, I just tried to use the command line you gave me, but it doesn't work, npm give me the following message :
`typings ERR! message Unable to find "compression" ("npm") in the registry.`

Any other idea ?

**Comment by glemiere** [comment]
I just found that :
https://github.com/DefinitelyTyped/DefinitelyTyped
https://github.com/retyped/compression-tsd-ambient

I will try to fix that issue this way ;-)

**Comment by gdi2290** [comment]
@glemiere can you run `typings install compression -SA`

**Comment by glemiere** [comment]
I just ran that command, my output is the following one :
```
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e05e1f6f83c6ac84e9d7ff8284e8089d53a788a6/express/express.d.ts" during installation from "compression"
compression
└── (No dependencies)

```
I've no error anymore but the compression is still not enabled, my code in my server.ts is the following one :

```
import * as compression from 'compression';
app.use(compression());
```

Thank you very much for your help, you're awesome! I suggest you to add that plugin in the webpack configuration to speed up that project when the node_env is not in production ;)
```
new webpack.optimize.UglifyJsPlugin({
      mangle: {
        screw_ie8 : true,
        keep_fnames: true
      }
    })
```

**Comment by glemiere** [comment]
I've moved my `app.use(compression());` and it works very well now!
Thank you very much for your help! :D
