### ISSUE TITLE
indexFile and dist?

### ISSUE THREAD

**Issue by dalgard** [angular/universal-starter#85]
The function `indexFile` in `server.ts` doesn't seem to be used anywhere. Should it perhaps be removed?

I stumbled upon it because I was looking into how `index.html` is served, since that file isn't in the `dist` folder. I find this very strange...

Is it correct that `index.html` is currently served from the `src` folder?

To be clear, I would expect to be able to distribute my application using only the contents of `dist`.

**Comment by gdi2290** [comment]
`indexFile` isn't used. someone would use it if they're looking to only service the `index.html` It was mostly used for a demo at ng-conf

**Comment by dalgard** [comment]
Thanks. Any comments in regard to my other question?

**Comment by gdi2290** [comment]
index.html is being read via express view engine then embedded with angular which is why it's never in dist. So this is only a concern with how express/server works

(closing for now but open another issue if you have more questions)
