### ISSUE TITLE
Is SystemJs starter deprecated? 

### ISSUE THREAD

**Issue by Codenator81** [angular/universal-starter#88]
I try it but it not works even after updates to angular 2 rc 1 and last universal.  I know there issues to support SystemJs in Universal

**Comment by gdi2290** [comment]
ya systemjs is deprecated

**Comment by dottodot** [comment]
Does this mean systemjs doesn't work with universal or that the systemjs branch isn't going to be updated anymore?

**Comment by jaumard** [comment]
Any news on this ?

**Comment by gerlstar** [comment]
Note in https://github.com/angular/universal-starter/tree/systemjs wouldve been nice indicating that it's deprecated.

**Comment by jeffwhelpley** [comment]
This repo is only for webpack. We won't have a systemjs version until this is resolved:

https://github.com/angular/universal/issues/283
