### ISSUE TITLE
Router not working with the latest version

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#90]
Router seems broken currently. Server side router does not map to the right views.

Just disable javascript and try out and and basically router and http will not fire anything. Tested with latest fresh version of today.

![screen shot 2016-05-21 at 11 38 32](https://cloud.githubusercontent.com/assets/2866604/15447602/919834c0-1f48-11e6-86ca-cc4da6a32a76.png)

**Comment by joaogarin** [comment]
Might be related with latest comment here https://github.com/angular/universal-starter/issues/79

**Comment by davidkaminsky** [comment]
I'm seeing this as well.

**Comment by yazeedb** [comment]
I see this as well

**Comment by gdi2290** [comment]
can you try again with the latest version?

**Comment by joaogarin** [comment]
This is fixed in latest version.
