### ISSUE TITLE
Docs/Bugs in SystemJS branch setup

### ISSUE THREAD

**Issue by jessehouchins** [angular/universal-starter#91]
The system JS branch would not correctly complete `npm install` for me (unmet dependency, wrong version of angular2-universal ironically). This also seems to prevent the server from starting. I looked at the `package.json` to see why the documented `npm watch` was not working to find that there wasn't one. So I used `npm start` instead, where I encountered `error TS2307: Cannot find module 'angular2-universal'`.

Also, It's unclear what version on node/npm should be used for this, since there is no `.nvmrc`.

**Comment by jessehouchins** [comment]
I was trying to run with node v6.1.0 and npm 3.8.6.

**Comment by vaskgjuri** [comment]
It also seems to be outdated. The mater branch has been updated with the newest version of angular, but the systemjs branch still uses old beta.

**Comment by jeffwhelpley** [comment]
Systemjs need to be address in core first. Follow the issue here:

https://github.com/angular/universal/issues/283
