### ISSUE TITLE
Styles are loaded twice 

### ISSUE THREAD

**Issue by xe4me** [angular/universal-starter#92]
Hi Guys.
I've forked and npm installed the repo and that's it , didn't touch anything else.
The problem is when I inspect the page after npm starting , I can see that every small style is loaded twice and appended at the head tag.
Attached the screenshot.
Thanks
<img width="923" alt="screen shot 2016-05-22 at 23 27 15" src="https://cloud.githubusercontent.com/assets/7995651/15457422/b0c45f9c-20cc-11e6-83a5-2ce6f9ca698c.png">

**Comment by coderabsolute** [comment]
Good catch! I wonder why? :) When you reported this issue, I notice the same.

**Comment by MarkPieszak** [comment]
Nice catch @xe4me I'll investigate this one!

**Comment by kuldeepkeshwar** [comment]
any way to avoid this ?

**Comment by xe4me** [comment]
@MarkPieszak  Any update on this ?

**Comment by gdi2290** [comment]
they're loaded twice because the client app needs to use the same id generated from the server

**Comment by xe4me** [comment]
@gdi2290 
So what does this mean ? 
I sure know that this is not normal.

**Comment by kuldeepkeshwar** [comment]
@gdi2290 @MarkPieszak any update or workaround for this ?

**Comment by gdi2290** [comment]
this will be fixed in the next release

**Comment by kuldeepkeshwar** [comment]
fixed in rc7 release

**Comment by gorkemyontem** [comment]
When I inspect I still see it twice. Is that normal?
