### ISSUE TITLE
This was rendered from the server

### ISSUE THREAD

**Issue by jaumard** [angular/universal-starter#93]
Whatever I click on menu or reload, I always have the message `This was rendered from the server!` I suppose first load was made by the server but then if I click on the menu "About" from "Home" the render is local not from the server so message is wrong...

**Comment by MarkPieszak** [comment]
You're right I'll fix that up, I'll make the message go away once the client has bootstrapped.

The `<router-outlet></router-outlet>` area is also really small, so most things always stay on the screen. I'll tweak all of that to remove some of that confusion 😉
