### ISSUE TITLE
How to inject http service in server.ts

### ISSUE THREAD

**Issue by vinodbhargava** [angular/universal-starter#99]
I am currently trying to inject http service in server.ts and then pass the returned data to `app` component to render it. 
Below is my snippet in server.ts -

`import {Http} from '@angular/http';`
`import {TemplateServiceFactory} from './app/services/template.service.factory';`

```
function test(req, res) {
      let factory = new TemplateServiceFactory();
      if(factory) {
         factory.methodOne('123').subscribe((res:any)=> {
            _templateObject = res;
         }, error => {
              console.log('error in methodOne ');
         });
      } else {
        console.log('factory is undefined');
      }
}
```

TemplateServiceFactory.ts -

`import { Injectable } from '@angular/core';`
`import { Http, Response } from '@angular/http';`
`import 'rxjs/add/operator/map';`
`import {AppSettings} from '../config/app.settings';`
`@Injectable()`
`export class TemplateServiceFactory {`
`public http: Http;
constructor() { `
`        console.log('Template service factory created.');`
`  }
    
    methodOne(_id) {
        return this.http.get(`${AppSettings.TEMPLATE_API_ENDPOINT}`+_id)
                        .map((res: Response) => res.json());
    }
}`

I am able to get the service object, but when invoking methodOne, it throws exception -
`TypeError: Cannot read property 'get' of undefined
    at TemplateServiceFactory.methodOne`

Any help would be appreciated. 
Thanks in advance.

**Comment by joaogarin** [comment]
yeah like @MarkPieszak mentions you just need to inject it in the constructor. And yeah if possible close the issue as its not an issue with universal.

**Comment by gdi2290** [comment]
to get it to "work" on the server outside of Angular2 you're looking for 
```
var injector = ReflectiveInjector.resolveAndCreate([
  {provide: NgZone, useValue: createNgZone()}, // the node http depends on zone and originurl :/
  {provide: ORIGIN_URL, useValue: 'http://localhost:3000'},
  NODE_HTTP_PROVIDERS,
  TemplateServiceFactory
]);
var factory = injector.get(TemplateServiceFactory);
factory.methodOne('123').subscribe((res: any)=> {
  _templateObject = res;
}, error => {
  console.log('error in methodOne ');
});
// OR
var nativeNodeHttp = require('http');
var fakeHttp = {
  get: function(url) {
    // nativeNodeHttp.request({ url: url }, doneCallback)
    // var fakeRx = { subscribe: function(onNextFn, onErrorFn, onCompleteFn) {}}
    return fakeRx
  }
}
var factory = new TemplateServiceFactory(fakeHttp)
```
with that said for what I think you're doing I don't think (prefetching templates to store in _templateObject) I'm not sure if this is the best solution. If you're trying to use the templateCache then I can provide a better way to inject this in the document

**Comment by vinodbhargava** [comment]
Closing this.

cheers :+1:
